// apps/AgentPit/src/components/memory/BackupSettings.vue
<script setup lang="ts">
import { ref, reactive, computed } from 'vue'
import type { BackupConfig, BackupRecord } from '@/types/memory'

interface Props {
  config?: BackupConfig
  history?: BackupRecord[]
  estimatedSize?: number
}

const props = withDefaults(defineProps<Props>(), {
  config: () => ({
    autoBackup: true,
    frequency: 'daily',
    backupType: 'incremental',
    retentionCount: 5,
    location: 'local'
  }),
  history: () => [],
  estimatedSize: () => 0
})

const emit = defineEmits<{
  configChange: [config: BackupConfig]
  manualBackup: []
  restore: [recordId: string]
}>()

const localConfig = reactive<BackupConfig>({ ...props.config })
const isBackingUp = ref(false)
const backupProgress = ref(0)
const showRestoreDialog = ref(false)
const selectedRestoreRecord = ref<BackupRecord | null>(null)

const isModified = computed(() => {
  return (
    localConfig.autoBackup !== props.config.autoBackup ||
    localConfig.frequency !== props.config.frequency ||
    localConfig.backupType !== props.config.backupType ||
    localConfig.retentionCount !== props.config.retentionCount ||
    localConfig.location !== props.config.location
  )
})

const formatFileSize = (bytes: number): string => {
  if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(1) + ' MB'
  return (bytes / (1024 * 1024)).toFixed(2) + ' GB'
}

const formatTimestamp = (timestamp: string): string => {
  return new Date(timestamp).toLocaleString('zh-CN', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit'
  })
}

const getStatus = (status: BackupRecord['status']): { color: string; label: string; icon: string } => {
  const statusMap: Record<BackupRecord['status'], { color: string; label: string; icon: string }> = {
    success: { color: '#10b981', label: '成功', icon: '✓' },
    failed: { color: '#ef4444', label: '失败', icon: '✗' },
    in_progress: { color: '#3b82f6', label: '进行中', icon: '⟳' }
  }
  return statusMap[status]
}

const handleManualBackup = async () => {
  isBackingUp.value = true
  backupProgress.value = 0

  // 模拟备份进度
  const interval = setInterval(() => {
    backupProgress.value += Math.random() * 15
    if (backupProgress.value >= 100) {
      backupProgress.value = 100
      clearInterval(interval)

      setTimeout(() => {
        isBackingUp.value = false
        backupProgress.value = 0
        emit('manualBackup')
      }, 500)
    }
  }, 200)
}

const handleRestoreClick = (record: BackupRecord) => {
  selectedRestoreRecord.value = record
  showRestoreDialog.value = true
}

const confirmRestore = () => {
  if (selectedRestoreRecord.value) {
    emit('restore', selectedRestoreRecord.value.id)
  }
  showRestoreDialog.value = false
  selectedRestoreRecord.value = null
}

const saveConfig = () => {
  emit('configChange', { ...localConfig })
}
</script>

<template>
  <div class="backup-settings__container bg-white dark:bg-gray-800 rounded-xl shadow-lg overflow-hidden">
    <!-- 标题 -->
    <div class="p-6 border-b border-gray-200 dark:border-gray-700">
      <div class="flex items-center justify-between">
        <div>
          <h2 class="text-2xl font-bold text-gray-900 dark:text-white flex items-center gap-3">
            💾 备份设置
          </h2>
          <p class="mt-2 text-sm text-gray-600 dark:text-gray-400">配置自动备份策略和管理备份记录</p>
        </div>
        <div class="text-right">
          <div class="text-xs text-gray-500 dark:text-gray-400">预计存储空间</div>
          <div class="text-lg font-semibold text-gray-900 dark:text-white">{{ formatFileSize(estimatedSize) }}</div>
        </div>
      </div>
    </div>

    <!-- 备份策略配置 -->
    <div class="p-6 space-y-6">
      <!-- 自动备份开关 -->
      <div class="flex items-center justify-between p-4 bg-gray-50 dark:bg-gray-700/50 rounded-lg">
        <div>
          <h3 class="font-medium text-gray-900 dark:text-white">自动备份</h3>
          <p class="text-sm text-gray-600 dark:text-gray-400 mt-1">开启后将按照设定的频率自动创建备份</p>
        </div>
        <button
          @click="localConfig.autoBackup = !localConfig.autoBackup"
          class="relative w-14 h-7 rounded-full transition-colors duration-200"
          :class="localConfig.autoBackup ? 'bg-blue-500' : 'bg-gray-300 dark:bg-gray-600'"
        >
          <span
            class="absolute top-0.5 left-0.5 w-6 h-6 bg-white rounded-full shadow transition-transform duration-200"
            :class="localConfig.autoBackup ? 'translate-x-7' : ''"
          ></span>
        </button>
      </div>

      <!-- 备份频率 -->
      <div v-if="localConfig.autoBackup" class="space-y-2">
        <label class="block text-sm font-medium text-gray-700 dark:text-gray-300">备份频率</label>
        <div class="grid grid-cols-3 gap-3">
          <button
            v-for="option in [
              { value: 'hourly', label: '每小时', desc: '适合高频更新数据' },
              { value: 'daily', label: '每天', desc: '推荐日常使用' },
              { value: 'weekly', label: '每周', desc: '节省存储空间' }
            ]"
            :key="option.value"
            @click="localConfig.frequency = option.value as BackupConfig['frequency']"
            class="p-3 rounded-lg border-2 transition-all text-left"
            :class="
              localConfig.frequency === option.value
                ? 'border-blue-500 bg-blue-50 dark:bg-blue-900/20'
                : 'border-gray-200 dark:border-gray-600 hover:border-gray-300 dark:hover:border-gray-500'
            "
          >
            <div class="font-medium text-sm" :class="localConfig.frequency === option.value ? 'text-blue-600 dark:text-blue-400' : 'text-gray-900 dark:text-white'">
              {{ option.label }}
            </div>
            <div class="text-xs text-gray-500 dark:text-gray-400 mt-1">{{ option.desc }}</div>
          </button>
        </div>
      </div>

      <!-- 备份类型 -->
      <div v-if="localConfig.autoBackup" class="space-y-2">
        <label class="block text-sm font-medium text-gray-700 dark:text-gray-300">备份类型</label>
        <div class="grid grid-cols-2 gap-3">
          <button
            @click="localConfig.backupType = 'incremental'"
            class="p-4 rounded-lg border-2 transition-all text-left"
            :class="
              localConfig.backupType === 'incremental'
                ? 'border-green-500 bg-green-50 dark:bg-green-900/20'
                : 'border-gray-200 dark:border-gray-600 hover:border-gray-300 dark:hover:border-gray-500'
            "
          >
            <div class="font-medium" :class="localConfig.backupType === 'incremental' ? 'text-green-600 dark:text-green-400' : 'text-gray-900 dark:text-white'">
              📦 增量备份
            </div>
            <div class="text-sm text-gray-500 dark:text-gray-400 mt-1">仅备份变更部分，速度快，空间占用小</div>
          </button>

          <button
            @click="localConfig.backupType = 'full'"
            class="p-4 rounded-lg border-2 transition-all text-left"
            :class="
              localConfig.backupType === 'full'
                ? 'border-purple-500 bg-purple-50 dark:bg-purple-900/20'
                : 'border-gray-200 dark:border-gray-600 hover:border-gray-300 dark:hover:border-gray-500'
            "
          >
            <div class="font-medium" :class="localConfig.backupType === 'full' ? 'text-purple-600 dark:text-purple-400' : 'text-gray-900 dark:text-white'">
              🔄 完整备份
            </div>
            <div class="text-sm text-gray-500 dark:text-gray-400 mt-1">完整复制所有数据，恢复更可靠</div>
          </button>
        </div>
      </div>

      <!-- 保留数量和位置 -->
      <div v-if="localConfig.autoBackup" class="grid grid-cols-2 gap-6">
        <!-- 保留数量 -->
        <div class="space-y-2">
          <label class="block text-sm font-medium text-gray-700 dark:text-gray-300">
            保留备份数量: <span class="font-bold text-blue-600 dark:text-blue-400">{{ localConfig.retentionCount }}</span> 个
          </label>
          <input
            v-model.number="localConfig.retentionCount"
            type="range"
            min="1"
            max="10"
            class="w-full h-2 bg-gray-200 dark:bg-gray-700 rounded-lg appearance-none cursor-pointer accent-blue-500"
          />
          <div class="flex justify-between text-xs text-gray-500 dark:text-gray-400">
            <span>1</span>
            <span>5</span>
            <span>10</span>
          </div>
        </div>

        <!-- 备份位置 -->
        <div class="space-y-2">
          <label class="block text-sm font-medium text-gray-700 dark:text-gray-300">备份位置</label>
          <select
            v-model="localConfig.location"
            class="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-blue-500"
          >
            <option value="local">🖥️ 本地存储</option>
            <option value="cloud">☁️ 云端存储（即将推出）</option>
          </select>
        </div>
      </div>

      <!-- 保存配置按钮 -->
      <div v-if="isModified" class="flex justify-end pt-4 border-t border-gray-200 dark:border-gray-700">
        <button
          @click="saveConfig"
          class="px-6 py-2.5 bg-blue-500 text-white font-medium rounded-lg hover:bg-blue-600 transition-colors shadow-md hover:shadow-lg"
        >
          💾 保存配置
        </button>
      </div>
    </div>

    <!-- 手动备份区域 -->
    <div class="px-6 py-4 bg-gradient-to-r from-blue-50 to-cyan-50 dark:from-blue-900/20 dark:to-cyan-900/20 border-t border-b border-gray-200 dark:border-gray-700">
      <div class="flex items-center justify-between">
        <div>
          <h3 class="font-semibold text-gray-900 dark:text-white">手动备份</h3>
          <p class="text-sm text-gray-600 dark:text-gray-400 mt-1">立即创建一次完整的备份快照</p>
        </div>
        <button
          @click="handleManualBackup"
          :disabled="isBackingUp"
          class="px-6 py-2.5 font-medium rounded-lg transition-all shadow-md"
          :class="
            isBackingUp
              ? 'bg-gray-400 text-white cursor-not-allowed'
              : 'bg-gradient-to-r from-blue-500 to-cyan-500 text-white hover:from-blue-600 hover:to-cyan-600 hover:shadow-lg'
          "
        >
          {{ isBackingUp ? `备份中 ${Math.round(backupProgress)}%` : '⚡ 立即备份' }}
        </button>
      </div>

      <!-- 进度条 -->
      <Transition name="expand">
        <div v-if="isBackingUp" class="mt-4">
          <div class="w-full h-3 bg-gray-200 dark:bg-gray-700 rounded-full overflow-hidden">
            <div
              class="h-full bg-gradient-to-r from-blue-500 to-cyan-500 rounded-full transition-all duration-300 ease-out relative"
              :style="{ width: backupProgress + '%' }"
            >
              <div class="absolute inset-0 bg-white/30 animate-pulse"></div>
            </div>
          </div>
        </div>
      </Transition>
    </div>

    <!-- 备份历史列表 -->
    <div class="p-6">
      <h3 class="text-lg font-semibold text-gray-900 dark:text-white mb-4">📋 备份历史</h3>

      <div v-if="history.length === 0" class="text-center py-12 text-gray-400">
        <p class="text-4xl mb-3">📭</p>
        <p class="text-sm">暂无备份记录</p>
      </div>

      <div v-else class="space-y-3">
        <TransitionGroup name="list" tag="div" class="space-y-3">
          <div
            v-for="record in history"
            :key="record.id"
            class="flex items-center justify-between p-4 bg-gray-50 dark:bg-gray-700/50 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors group"
          >
            <div class="flex items-center gap-4 flex-1 min-w-0">
              <!-- 状态图标 -->
              <div
                class="w-10 h-10 rounded-full flex items-center justify-center text-lg flex-shrink-0"
                :style="{ backgroundColor: getStatus(record.status).color + '20' }"
              >
                {{ getStatus(record.status).icon }}
              </div>

              <!-- 信息 -->
              <div class="flex-1 min-w-0">
                <div class="flex items-center gap-2">
                  <span
                    class="px-2 py-0.5 text-xs font-medium rounded-full"
                    :style="{ backgroundColor: getStatus(record.status).color + '20', color: getStatus(record.status).color }"
                  >
                    {{ getStatus(record.status).label }}
                  </span>
                  <span class="text-xs text-gray-500 dark:text-gray-400">
                    {{ record.type === 'full' ? '完整' : '增量' }}备份
                  </span>
                </div>
                <div class="text-sm text-gray-900 dark:text-white font-medium mt-1 truncate">
                  {{ formatTimestamp(record.timestamp) }}
                </div>
              </div>

              <!-- 大小 -->
              <div class="text-right flex-shrink-0">
                <div class="text-sm font-semibold text-gray-900 dark:text-white">{{ formatFileSize(record.size) }}</div>
              </div>
            </div>

            <!-- 操作按钮 -->
            <div class="opacity-0 group-hover:opacity-100 transition-opacity ml-4 flex-shrink-0">
              <button
                v-if="record.status === 'success'"
                @click="handleRestoreClick(record)"
                class="px-3 py-1.5 text-xs font-medium text-blue-600 dark:text-blue-400 bg-blue-50 dark:bg-blue-900/30 rounded-lg hover:bg-blue-100 dark:hover:bg-blue-900/50 transition-colors"
              >
                🔄 恢复
              </button>
            </div>
          </div>
        </TransitionGroup>
      </div>
    </div>

    <!-- 恢复确认对话框 -->
    <Teleport to="body">
      <Transition name="fade">
        <div v-if="showRestoreDialog && selectedRestoreRecord" class="fixed inset-0 z-50 flex items-center justify-center bg-black/50" @click="showRestoreDialog = false">
          <div class="bg-white dark:bg-gray-800 rounded-xl shadow-2xl p-6 max-w-md w-full mx-4" @click.stop>
            <div class="text-center mb-6">
              <div class="w-16 h-16 mx-auto mb-4 bg-yellow-100 dark:bg-yellow-900/30 rounded-full flex items-center justify-center text-4xl">
                ⚠️
              </div>
              <h3 class="text-xl font-bold text-gray-900 dark:text-white mb-2">确认恢复备份？</h3>
              <p class="text-sm text-gray-600 dark:text-gray-400">
                此操作将使用以下备份数据覆盖当前数据：
              </p>
              <div class="mt-4 p-3 bg-gray-50 dark:bg-gray-700 rounded-lg text-left space-y-1">
                <div class="text-sm"><strong>时间:</strong> {{ formatTimestamp(selectedRestoreRecord.timestamp) }}</div>
                <div class="text-sm"><strong>大小:</strong> {{ formatFileSize(selectedRestoreRecord.size) }}</div>
                <div class="text-sm"><strong>类型:</strong> {{ selectedRestoreRecord.type === 'full' ? '完整' : '增量' }}备份</div>
              </div>
              <p class="mt-4 text-xs text-red-500 font-medium">⚠️ 恢复操作不可撤销，请确保已做好当前数据的备份！</p>
            </div>

            <div class="flex gap-3">
              <button
                @click="showRestoreDialog = false"
                class="flex-1 px-4 py-2.5 text-gray-700 dark:text-gray-300 bg-gray-100 dark:bg-gray-700 hover:bg-gray-200 dark:hover:bg-gray-600 rounded-lg font-medium transition-colors"
              >
                取消
              </button>
              <button
                @click="confirmRestore"
                class="flex-1 px-4 py-2.5 bg-red-500 text-white hover:bg-red-600 rounded-lg font-medium transition-colors"
              >
                确认恢复
              </button>
            </div>
          </div>
        </div>
      </Transition>
    </Teleport>
  </div>
</template>

<style scoped>
.expand-enter-active,
.expand-leave-active {
  transition: all 0.3s ease;
}
.expand-enter-from,
.expand-leave-to {
  opacity: 0;
  max-height: 0;
}

.list-enter-active,
.list-leave-active {
  transition: all 0.3s ease;
}
.list-enter-from {
  opacity: 0;
  transform: translateX(-20px);
}
.list-leave-to {
  opacity: 0;
  transform: translateX(20px);
}

.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.2s ease;
}
.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}
</style>

// apps/AgentPit/src-react-backup-20260410/components/memory/BackupSettings.tsx
import { useState } from 'react'
import { backupRecords, syncDevices } from '../../data/mockMemory'

const formatFileSize = (bytes: number): string => {
  if (bytes === 0) return '0 B'
  const k = 1024
  const sizes = ['B', 'KB', 'MB', 'GB']
  const i = Math.floor(Math.log(bytes) / Math.log(k))
  return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i]
}

const BackupSettings = () => {
  const [autoBackup, setAutoBackup] = useState(true)
  const [backupFrequency, setBackupFrequency] = useState<'daily' | 'weekly' | 'monthly'>('daily')
  const [backupTime, setBackupTime] = useState('02:00')
  const [backupScope, setBackupScope] = useState<'all' | 'selective'>('all')
  const [isBackingUp, setIsBackingUp] = useState(false)
  const [showImportModal, setShowImportModal] = useState(false)
  const [showExportModal, setShowExportModal] = useState(false)
  const [activeTab, setActiveTab] = useState<'backup' | 'sync' | 'history'>('backup')

  const latestBackup = backupRecords[0]
  const totalBackupSize = backupRecords.reduce((sum, b) => sum + b.size, 0)

  const handleManualBackup = () => {
    setIsBackingUp(true)
    setTimeout(() => {
      setIsBackingUp(false)
      alert('备份完成！')
    }, 2000)
  }

  return (
    <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
      <div className="border-b border-gray-200 px-6 py-4">
        <h2 className="text-xl font-semibold text-gray-900 flex items-center gap-2 mb-4">
          <span>💾</span>
          数据备份与同步
        </h2>

        <div className="flex bg-gray-100 rounded-lg p-1 w-fit">
          {([
            { value: 'backup' as const, label: '备份设置' },
            { value: 'sync' as const, label: '设备同步' },
            { value: 'history' as const, label: '版本历史' }
          ]).map(({ value, label }) => (
            <button
              key={value}
              onClick={() => setActiveTab(value)}
              className={`px-4 py-1.5 rounded-md text-sm font-medium transition-all ${
                activeTab === value ? 'bg-white text-primary-600 shadow-sm' : 'text-gray-600 hover:text-gray-900'
              }`}
            >
              {label}
            </button>
          ))}
        </div>
      </div>

      <div className="p-6">
        {activeTab === 'backup' && (
          <div className="space-y-6">
            <div className="bg-gradient-to-r from-blue-50 to-indigo-50 rounded-xl p-5 border border-blue-200">
              <h3 className="font-semibold text-gray-900 mb-3">当前备份状态</h3>
              <div className="grid grid-cols-3 gap-4">
                <div>
                  <p className="text-xs text-gray-600 mb-1">上次备份时间</p>
                  <p className="text-lg font-semibold text-gray-900">
                    {latestBackup ? new Date(latestBackup.timestamp).toLocaleString('zh-CN') : '-'}
                  </p>
                </div>
                <div>
                  <p className="text-xs text-gray-600 mb-1">最新备份大小</p>
                  <p className="text-lg font-semibold text-gray-900">
                    {latestBackup ? formatFileSize(latestBackup.size) : '-'}
                  </p>
                </div>
                <div>
                  <p className="text-xs text-gray-600 mb-1">状态</p>
                  <span className={`inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-sm font-medium ${
                    latestBackup?.status === 'success' ? 'bg-green-100 text-green-800' :
                    latestBackup?.status === 'failed' ? 'bg-red-100 text-red-800' :
                    'bg-yellow-100 text-yellow-800'
                  }`}>
                    <span className={`w-2 h-2 rounded-full ${
                      latestBackup?.status === 'success' ? 'bg-green-500' :
                      latestBackup?.status === 'failed' ? 'bg-red-500' :
                      'bg-yellow-500'
                    }`} />
                    {latestBackup?.status === 'success' ? '成功' :
                     latestBackup?.status === 'failed' ? '失败' : '进行中'}
                  </span>
                </div>
              </div>

              <div className="mt-4 pt-4 border-t border-blue-200/50">
                <div className="flex items-center justify-between text-sm">
                  <span className="text-gray-700">总备份数据量</span>
                  <span className="font-semibold text-gray-900">{formatFileSize(totalBackupSize)}</span>
                </div>
                <div className="mt-2 h-2 bg-blue-200 rounded-full overflow-hidden">
                  <div
                    className="h-full bg-gradient-to-r from-blue-500 to-indigo-600 rounded-full"
                    style={{ width: `${Math.min(totalBackupSize / (10 * 1024 * 1024 * 1024) * 100, 100)}%` }}
                  />
                </div>
              </div>
            </div>

            <div className="flex items-center justify-between p-4 bg-gray-50 rounded-lg">
              <div>
                <h4 className="font-medium text-gray-900">手动备份</h4>
                <p className="text-sm text-gray-600 mt-0.5">立即创建一份完整的数据备份</p>
              </div>
              <button
                onClick={handleManualBackup}
                disabled={isBackingUp}
                className={`px-6 py-2.5 rounded-lg font-medium transition-all flex items-center gap-2 ${
                  isBackingUp
                    ? 'bg-gray-300 text-gray-600 cursor-not-allowed'
                    : 'bg-primary-600 text-white hover:bg-primary-700 hover:shadow-lg'
                }`}
              >
                {isBackingUp ? (
                  <>
                    <svg className="animate-spin w-4 h-4" viewBox="0 0 24 24" fill="none">
                      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                    </svg>
                    备份中...
                  </>
                ) : (
                  <>🔄 立即备份</>
                )}
              </button>
            </div>

            <div className="border-t pt-6">
              <h3 className="font-semibold text-gray-900 mb-4">自动备份计划</h3>

              <div className="space-y-4">
                <div className="flex items-center justify-between p-4 border border-gray-200 rounded-lg">
                  <div className="flex items-center gap-3">
                    <input
                      type="checkbox"
                      checked={autoBackup}
                      onChange={(e) => setAutoBackup(e.target.checked)}
                      className="w-5 h-5 rounded border-gray-300 text-primary-600 focus:ring-primary-500"
                    />
                    <div>
                      <p className="font-medium text-gray-900">启用自动备份</p>
                      <p className="text-sm text-gray-600">系统将按计划自动创建备份</p>
                    </div>
                  </div>
                </div>

                {autoBackup && (
                  <>
                    <div className="grid grid-cols-2 gap-4">
                      <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1.5">备份频率</label>
                        <select
                          value={backupFrequency}
                          onChange={(e) => setBackupFrequency(e.target.value as typeof backupFrequency)}
                          className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 outline-none"
                        >
                          <option value="daily">每日备份</option>
                          <option value="weekly">每周备份</option>
                          <option value="monthly">每月备份</option>
                        </select>
                      </div>
                      <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1.5">备份时间</label>
                        <input
                          type="time"
                          value={backupTime}
                          onChange={(e) => setBackupTime(e.target.value)}
                          className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 outline-none"
                        />
                      </div>
                    </div>

                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-2">备份范围</label>
                      <div className="flex gap-3">
                        <button
                          onClick={() => setBackupScope('all')}
                          className={`flex-1 px-4 py-2.5 rounded-lg border-2 font-medium transition-all ${
                            backupScope === 'all'
                              ? 'border-primary-500 bg-primary-50 text-primary-700'
                              : 'border-gray-200 text-gray-700 hover:border-gray-300'
                          }`}
                        >
                          📦 全部数据
                        </button>
                        <button
                          onClick={() => setBackupScope('selective')}
                          className={`flex-1 px-4 py-2.5 rounded-lg border-2 font-medium transition-all ${
                            backupScope === 'selective'
                              ? 'border-primary-500 bg-primary-50 text-primary-700'
                              : 'border-gray-200 text-gray-700 hover:border-gray-300'
                          }`}
                        >
                          ✅ 选择性备份
                        </button>
                      </div>
                    </div>
                  </>
                )}
              </div>
            </div>

            <div className="border-t pt-6">
              <h3 className="font-semibold text-gray-900 mb-4">数据导入/导出</h3>
              <div className="grid grid-cols-2 gap-4">
                <button
                  onClick={() => setShowImportModal(true)}
                  className="p-4 border-2 border-dashed border-gray-300 rounded-lg hover:border-primary-400 hover:bg-primary-50 transition-all group"
                >
                  <div className="text-center">
                    <span className="text-3xl block mb-2 group-hover:scale-110 transition-transform">📥</span>
                    <p className="font-medium text-gray-900">导入数据</p>
                    <p className="text-sm text-gray-600 mt-1">从备份文件恢复数据</p>
                  </div>
                </button>
                <button
                  onClick={() => setShowExportModal(true)}
                  className="p-4 border-2 border-dashed border-gray-300 rounded-lg hover:border-primary-400 hover:bg-primary-50 transition-all group"
                >
                  <div className="text-center">
                    <span className="text-3xl block mb-2 group-hover:scale-110 transition-transform">📤</span>
                    <p className="font-medium text-gray-900">导出数据</p>
                    <p className="text-sm text-gray-600 mt-1">导出为备份文件</p>
                  </div>
                </button>
              </div>
            </div>

            <div className="border-t pt-6">
              <h3 className="font-semibold text-gray-900 mb-4">云服务集成</h3>
              <div className="bg-gradient-to-r from-emerald-50 to-teal-50 rounded-lg p-4 border border-emerald-200">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    <span className="text-3xl">☁️</span>
                    <div>
                      <p className="font-medium text-gray-900">云端存储已连接</p>
                      <p className="text-sm text-gray-600">数据将自动同步至云端存储服务</p>
                    </div>
                  </div>
                  <span className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-green-100 text-green-800 rounded-full text-sm font-medium">
                    <span className="w-2 h-2 rounded-full bg-green-500 animate-pulse" />
                    已连接
                  </span>
                </div>
              </div>
            </div>
          </div>
        )}

        {activeTab === 'sync' && (
          <div className="space-y-4">
            <h3 className="font-semibold text-gray-900 mb-4">已连接设备</h3>

            {syncDevices.map(device => (
              <div key={device.id} className="border border-gray-200 rounded-lg p-4 hover:border-primary-300 transition-colors">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-4">
                    <div className={`w-12 h-12 rounded-xl flex items-center justify-center text-2xl ${
                      device.type === 'desktop' ? 'bg-blue-100' :
                      device.type === 'mobile' ? 'bg-purple-100' :
                      'bg-orange-100'
                    }`}>
                      {device.type === 'desktop' ? '💻' : device.type === 'mobile' ? '📱' : '📟'}
                    </div>
                    <div>
                      <h4 className="font-medium text-gray-900">{device.name}</h4>
                      <p className="text-sm text-gray-600 mt-0.5">
                        最后同步：{new Date(device.lastSync).toLocaleString('zh-CN')}
                      </p>
                      <p className="text-xs text-gray-500 mt-0.5">
                        存储使用：{formatFileSize(device.storageUsed)}
                      </p>
                    </div>
                  </div>

                  <div className="flex items-center gap-3">
                    <span className={`px-3 py-1 rounded-full text-sm font-medium ${
                      device.status === 'synced' ? 'bg-green-100 text-green-800' :
                      device.status === 'syncing' ? 'bg-blue-100 text-blue-800' :
                      'bg-red-100 text-red-800'
                    }`}>
                      {device.status === 'synced' ? '✓ 已同步' :
                       device.status === 'syncing' ? '⟳ 同步中...' : '⚠ 同步错误'}
                    </span>
                    <button className="px-3 py-1.5 bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-lg text-sm font-medium transition-colors">
                      管理
                    </button>
                  </div>
                </div>
              </div>
            ))}

            <button className="w-full mt-4 py-3 border-2 border-dashed border-gray-300 rounded-lg text-gray-600 hover:border-primary-400 hover:text-primary-600 transition-all font-medium">
              ➕ 添加新设备
            </button>
          </div>
        )}

        {activeTab === 'history' && (
          <div className="space-y-3">
            <h3 className="font-semibold text-gray-900 mb-4">备份版本历史</h3>

            {backupRecords.map(backup => (
              <div
                key={backup.id}
                className="border border-gray-200 rounded-lg p-4 hover:border-primary-300 transition-colors"
              >
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-4">
                    <div className={`w-10 h-10 rounded-lg flex items-center justify-center ${
                      backup.status === 'success' ? 'bg-green-100' :
                      backup.status === 'failed' ? 'bg-red-100' :
                      'bg-yellow-100'
                    }`}>
                      {backup.status === 'success' ? '✅' :
                       backup.status === 'failed' ? '❌' : '⏳'}
                    </div>
                    <div>
                      <div className="flex items-center gap-2">
                        <h4 className="font-medium text-gray-900">{backup.version}</h4>
                        <span className={`px-2 py-0.5 rounded text-xs font-medium ${
                          backup.type === 'full' ? 'bg-purple-100 text-purple-800' : 'bg-blue-100 text-blue-800'
                        }`}>
                          {backup.type === 'full' ? '全量' : '增量'}
                        </span>
                      </div>
                      <p className="text-sm text-gray-600 mt-0.5">{backup.description}</p>
                      <div className="flex items-center gap-3 mt-1 text-xs text-gray-500">
                        <span>{new Date(backup.timestamp).toLocaleString('zh-CN')}</span>
                        <span>·</span>
                        <span>{formatFileSize(backup.size)}</span>
                      </div>
                    </div>
                  </div>

                  <div className="flex items-center gap-2">
                    {backup.status === 'success' && (
                      <>
                        <button className="px-3 py-1.5 bg-blue-50 text-blue-700 hover:bg-blue-100 rounded-lg text-sm font-medium transition-colors">
                          恢复到此版本
                        </button>
                        <button className="px-3 py-1.5 bg-gray-100 text-gray-700 hover:bg-gray-200 rounded-lg text-sm font-medium transition-colors">
                          下载
                        </button>
                      </>
                    )}
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {showImportModal && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50" onClick={() => setShowImportModal(false)}>
          <div className="bg-white rounded-xl p-6 w-[480px] shadow-2xl" onClick={e => e.stopPropagation()}>
            <h3 className="text-lg font-semibold text-gray-900 mb-4">导入数据</h3>
            <div className="border-2 border-dashed border-gray-300 rounded-lg p-8 text-center hover:border-primary-400 transition-colors cursor-pointer">
              <p className="text-4xl mb-3">📁</p>
              <p className="font-medium text-gray-900 mb-1">点击或拖拽文件到此处</p>
              <p className="text-sm text-gray-500">支持 .zip, .tar.gz 格式的备份文件</p>
            </div>
            <div className="flex justify-end gap-3 mt-6">
              <button onClick={() => setShowImportModal(false)} className="px-4 py-2 text-gray-700 hover:bg-gray-100 rounded-lg transition-colors">
                取消
              </button>
              <button className="px-6 py-2 bg-primary-600 text-white rounded-lg hover:bg-primary-700 transition-colors font-medium">
                开始导入
              </button>
            </div>
          </div>
        </div>
      )}

      {showExportModal && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50" onClick={() => setShowExportModal(false)}>
          <div className="bg-white rounded-xl p-6 w-[480px] shadow-2xl" onClick={e => e.stopPropagation()}>
            <h3 className="text-lg font-semibold text-gray-900 mb-4">导出数据</h3>
            <div className="space-y-3 mb-4">
              <label className="flex items-center gap-2 p-3 border border-gray-200 rounded-lg cursor-pointer hover:border-primary-300 transition-colors">
                <input type="radio" name="exportType" defaultChecked className="text-primary-600" />
                <div>
                  <p className="font-medium text-gray-900">完整备份</p>
                  <p className="text-sm text-gray-600">导出所有数据和设置</p>
                </div>
              </label>
              <label className="flex items-center gap-2 p-3 border border-gray-200 rounded-lg cursor-pointer hover:border-primary-300 transition-colors">
                <input type="radio" name="exportType" className="text-primary-600" />
                <div>
                  <p className="font-medium text-gray-900">仅记忆数据</p>
                  <p className="text-sm text-gray-600">只导出记忆条目和搜索索引</p>
                </div>
              </label>
              <label className="flex items-center gap-2 p-3 border border-gray-200 rounded-lg cursor-pointer hover:border-primary-300 transition-colors">
                <input type="radio" name="exportType" className="text-primary-600" />
                <div>
                  <p className="font-medium text-gray-900">自定义范围</p>
                  <p className="text-sm text-gray-600">选择需要导出的内容类型</p>
                </div>
              </label>
            </div>
            <div className="flex justify-end gap-3 mt-6">
              <button onClick={() => setShowExportModal(false)} className="px-4 py-2 text-gray-700 hover:bg-gray-100 rounded-lg transition-colors">
                取消
              </button>
              <button onClick={() => setShowExportModal(false)} className="px-6 py-2 bg-primary-600 text-white rounded-lg hover:bg-primary-700 transition-colors font-medium">
                开始导出
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

export default BackupSettings
