// apps/AgentPit/src/components/memory/MemorySearch.vue
<script setup lang="ts">
import { ref, reactive, computed, watch } from 'vue'
import { useDebounce } from '@/composables/useDebounce'
import type { SearchResult, SearchFilter } from '@/types/memory'

interface Props {
  data?: SearchResult[]
}

const props = withDefaults(defineProps<Props>(), {
  data: () => []
})

const emit = defineEmits<{
  resultSelect: [result: SearchResult]
}>()

const searchQuery = ref('')
const debouncedSearch = useDebounce(searchQuery, 300)
const searchHistory = ref<string[]>([])
const showFilters = ref(false)
const sortBy = ref<'relevance' | 'time' | 'size'>('relevance')
const filter = reactive<SearchFilter>({
  dateRange: undefined,
  fileType: undefined,
  tags: []
})

const availableTags = computed(() => {
  const tagSet = new Set<string>()
  props.data.forEach(item => item.tags?.forEach(tag => tagSet.add(tag)))
  return Array.from(tagSet)
})

const filteredResults = computed(() => {
  let results = [...props.data]

  // 搜索过滤
  if (debouncedSearch.value) {
    const query = debouncedSearch.value.toLowerCase()
    results = results.filter(item =>
      item.title.toLowerCase().includes(query) ||
      item.content.toLowerCase().includes(query)
    )
  }

  // 时间范围过滤
  if (filter.dateRange) {
    const start = new Date(filter.dateRange.start).getTime()
    const end = new Date(filter.dateRange.end).getTime()
    results = results.filter(item => {
      const itemTime = new Date(item.timestamp).getTime()
      return itemTime >= start && itemTime <= end
    })
  }

  // 文件类型过滤
  if (filter.fileType) {
    results = results.filter(item => item.type === filter.fileType)
  }

  // 标签过滤
  if (filter.tags && filter.tags.length > 0) {
    results = results.filter(item =>
      filter.tags!.some(tag => item.tags?.includes(tag))
    )
  }

  // 排序
  switch (sortBy.value) {
    case 'relevance':
      results.sort((a, b) => b.relevance - a.relevance)
      break
    case 'time':
      results.sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime())
      break
    case 'size':
      results.sort((a, b) => (b.size || 0) - (a.size || 0))
      break
  }

  return results
})

const highlightText = (text: string, query: string): string => {
  if (!query) return text
  const regex = new RegExp(`(${query.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')})`, 'gi')
  return text.replace(regex, '<mark class="bg-yellow-200 dark:bg-yellow-800 px-0.5 rounded">$1</mark>')
}

const addToHistory = (query: string) => {
  if (!query.trim()) return
  const history = searchHistory.value.filter(h => h !== query)
  history.unshift(query)
  searchHistory.value = history.slice(0, 10)
}

const selectFromHistory = (query: string) => {
  searchQuery.value = query
}

const clearHistory = () => {
  searchHistory.value = []
}

const toggleTag = (tag: string) => {
  const index = filter.tags?.indexOf(tag) ?? -1
  if (index > -1) {
    filter.tags?.splice(index, 1)
  } else {
    filter.tags?.push(tag)
  }
}

const clearFilters = () => {
  filter.dateRange = undefined
  filter.fileType = undefined
  filter.tags = []
}

watch(debouncedSearch, (newVal) => {
  if (newVal) {
    addToHistory(newVal)
  }
})
</script>

<template>
  <div class="memory-search__container bg-white dark:bg-gray-800 rounded-xl shadow-lg overflow-hidden">
    <!-- 搜索栏 -->
    <div class="p-4 border-b border-gray-200 dark:border-gray-700">
      <div class="relative">
        <input
          v-model="searchQuery"
          type="text"
          placeholder="搜索记忆内容..."
          class="w-full px-4 py-3 pl-12 pr-12 border border-gray-300 dark:border-gray-600 rounded-xl bg-gray-50 dark:bg-gray-700 text-gray-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all"
        />
        <span class="absolute left-4 top-1/2 -translate-y-1/2 text-xl">🔍</span>
        <button
          v-if="searchQuery"
          @click="searchQuery = ''"
          class="absolute right-4 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600 dark:hover:text-gray-300"
        >
          ✕
        </button>
      </div>

      <!-- 搜索历史 -->
      <Transition name="slide">
        <div v-if="searchHistory.length > 0 && !debouncedSearch" class="mt-3 flex items-center gap-2 flex-wrap">
          <span class="text-xs text-gray-500 dark:text-gray-400">最近搜索:</span>
          <button
            v-for="(item, index) in searchHistory.slice(0, 5)"
            :key="index"
            @click="selectFromHistory(item)"
            class="px-3 py-1 text-xs bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300 rounded-full hover:bg-gray-200 dark:hover:bg-gray-600 transition-colors"
          >
            {{ item }}
          </button>
          <button
            @click="clearHistory"
            class="text-xs text-red-500 hover:text-red-600 transition-colors"
          >
            清除
          </button>
        </div>
      </Transition>
    </div>

    <!-- 筛选和排序工具栏 -->
    <div class="flex items-center justify-between px-4 py-3 bg-gray-50 dark:bg-gray-900 border-b border-gray-200 dark:border-gray-700">
      <div class="flex items-center gap-3">
        <button
          @click="showFilters = !showFilters"
          class="px-3 py-1.5 text-sm font-medium text-gray-700 dark:text-gray-300 bg-white dark:bg-gray-800 border border-gray-300 dark:border-gray-600 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors flex items-center gap-1"
        >
          🔽 筛选
          <span v-if="filter.dateRange || filter.fileType || (filter.tags && filter.tags.length > 0)" class="ml-1 w-2 h-2 bg-blue-500 rounded-full"></span>
        </button>

        <!-- 排序选择 -->
        <select
          v-model="sortBy"
          class="px-3 py-1.5 text-sm bg-white dark:bg-gray-800 border border-gray-300 dark:border-gray-600 rounded-lg text-gray-700 dark:text-gray-300 focus:outline-none focus:ring-2 focus:ring-blue-500"
        >
          <option value="relevance">相关度排序</option>
          <option value="time">时间排序</option>
          <option value="size">大小排序</option>
        </select>
      </div>

      <div class="text-sm font-medium" :class="filteredResults.length > 0 ? 'text-gray-900 dark:text-white' : 'text-gray-500 dark:text-gray-400'">
        {{ filteredResults.length }} 条结果
      </div>
    </div>

    <!-- 高级筛选面板 -->
    <Transition name="expand">
      <div v-if="showFilters" class="px-4 py-4 bg-gray-50 dark:bg-gray-900 border-b border-gray-200 dark:border-gray-700 space-y-4">
        <!-- 时间范围 -->
        <div>
          <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">时间范围</label>
          <div class="flex gap-3">
            <input
              v-model="filter.dateRange!.start"
              type="date"
              class="flex-1 px-3 py-2 text-sm border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-blue-500"
            />
            <span class="self-center text-gray-400">至</span>
            <input
              v-model="filter.dateRange!.end"
              type="date"
              class="flex-1 px-3 py-2 text-sm border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-blue-500"
            />
          </div>
        </div>

        <!-- 文件类型 -->
        <div>
          <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">文件类型</label>
          <select
            v-model="filter.fileType"
            class="w-full px-3 py-2 text-sm border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-blue-500"
          >
            <option value="">全部类型</option>
            <option value="document">文档</option>
            <option value="image">图片</option>
            <option value="video">视频</option>
            <option value="code">代码</option>
            <option value="other">其他</option>
          </select>
        </div>

        <!-- 标签筛选 -->
        <div v-if="availableTags.length > 0">
          <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">标签</label>
          <div class="flex flex-wrap gap-2">
            <button
              v-for="tag in availableTags"
              :key="tag"
              @click="toggleTag(tag)"
              class="px-3 py-1 text-xs rounded-full transition-colors"
              :class="filter.tags?.includes(tag)
                ? 'bg-blue-500 text-white'
                : 'bg-gray-200 dark:bg-gray-700 text-gray-700 dark:text-gray-300 hover:bg-gray-300 dark:hover:bg-gray-600'"
            >
              {{ tag }}
            </button>
          </div>
        </div>

        <button
          @click="clearFilters"
          class="w-full py-2 text-sm text-red-600 dark:text-red-400 hover:bg-red-50 dark:hover:bg-red-900/20 rounded-lg transition-colors"
        >
          清除所有筛选
        </button>
      </div>
    </Transition>

    <!-- 搜索结果列表 -->
    <div class="divide-y divide-gray-200 dark:divide-gray-700 max-h-[500px] overflow-y-auto">
      <!-- 有结果 -->
      <TransitionGroup name="list" v-if="filteredResults.length > 0">
        <div
          v-for="result in filteredResults"
          :key="result.id"
          @click="emit('resultSelect', result)"
          class="memory-search__result-item p-4 hover:bg-gray-50 dark:hover:bg-gray-700/50 cursor-pointer transition-colors"
        >
          <div class="flex items-start justify-between gap-4">
            <div class="flex-1 min-w-0">
              <h3
                class="text-base font-semibold text-gray-900 dark:text-white mb-1 line-clamp-1"
                v-html="highlightText(result.title, debouncedSearch)"
              ></h3>
              <p
                class="text-sm text-gray-600 dark:text-gray-400 line-clamp-2 mb-2"
                v-html="highlightText(result.content, debouncedSearch)"
              ></p>
              <div class="flex items-center gap-3 text-xs text-gray-500 dark:text-gray-400">
                <span class="px-2 py-0.5 bg-gray-100 dark:bg-gray-700 rounded">{{ result.type }}</span>
                <span>{{ new Date(result.timestamp).toLocaleDateString('zh-CN') }}</span>
                <span v-if="result.size">{{ (result.size / 1024).toFixed(1) }} KB</span>
              </div>
              <div v-if="result.tags && result.tags.length > 0" class="flex gap-1.5 mt-2 flex-wrap">
                <span
                  v-for="tag in result.tags"
                  :key="tag"
                  class="px-2 py-0.5 text-xs bg-blue-50 dark:bg-blue-900/30 text-blue-600 dark:text-blue-400 rounded"
                >
                  #{{ tag }}
                </span>
              </div>
            </div>
            <div class="text-right flex-shrink-0">
              <div class="text-lg font-bold" :class="result.relevance > 0.8 ? 'text-green-500' : result.relevance > 0.5 ? 'text-yellow-500' : 'text-gray-400'">
                {{ Math.round(result.relevance * 100) }}%
              </div>
              <div class="text-xs text-gray-400">相关度</div>
            </div>
          </div>
        </div>
      </TransitionGroup>

      <!-- 无结果 -->
      <div v-else-if="debouncedSearch" class="flex flex-col items-center justify-center py-16 text-gray-400">
        <p class="text-5xl mb-4">🔍</p>
        <p class="text-lg font-medium">未找到匹配结果</p>
        <p class="text-sm mt-2">尝试使用不同的关键词或调整筛选条件</p>
      </div>

      <!-- 空状态（未搜索） -->
      <div v-else class="flex flex-col items-center justify-center py-16 text-gray-400">
        <p class="text-5xl mb-4">💭</p>
        <p class="text-lg font-medium">输入关键词开始搜索</p>
        <p class="text-sm mt-2">支持全文检索，可按时间、类型、标签筛选</p>
      </div>
    </div>
  </div>
</template>

<style scoped>
.slide-enter-active,
.slide-leave-active {
  transition: all 0.3s ease;
}
.slide-enter-from,
.slide-leave-to {
  opacity: 0;
  transform: translateY(-10px);
}

.expand-enter-active,
.expand-leave-active {
  transition: all 0.3s ease;
  overflow: hidden;
}
.expand-enter-from,
.expand-leave-to {
  opacity: 0;
  max-height: 0;
}
.expand-enter-to,
.expand-leave-from {
  max-height: 400px;
}

.list-enter-active,
.list-leave-active {
  transition: all 0.3s ease;
}
.list-enter-from {
  opacity: 0;
  transform: translateX(-20px);
}
.list-leave-to {
  opacity: 0;
  transform: translateX(20px);
}

.line-clamp-1 {
  display: -webkit-box;
  -webkit-line-clamp: 1;
  -webkit-box-orient: vertical;
  overflow: hidden;
}

.line-clamp-2 {
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}
</style>

// apps/AgentPit/src-react-backup-20260410/components/memory/MemorySearch.tsx
import { useState, useMemo } from 'react'
import { memoryEntries, searchHistory, savedSearches, MemoryEntry } from '../../data/mockMemory'

type SortOption = 'relevance' | 'time' | 'frequency'
type ViewMode = 'list' | 'card'

const typeIcons = {
  conversation: '💬',
  note: '📝',
  bookmark: '🔖',
  event: '📅',
  learning: '📚',
  idea: '💡'
}

const typeLabels = {
  conversation: '对话记录',
  note: '笔记',
  bookmark: '书签',
  event: '事件',
  learning: '学习',
  idea: '想法'
}

const typeColors = {
  conversation: 'bg-blue-100 text-blue-800',
  note: 'bg-green-100 text-green-800',
  bookmark: 'bg-yellow-100 text-yellow-800',
  event: 'bg-purple-100 text-purple-800',
  learning: 'bg-indigo-100 text-indigo-800',
  idea: 'bg-pink-100 text-pink-800'
}

const MemorySearch = () => {
  const [searchQuery, setSearchQuery] = useState('')
  const [showAdvanced, setShowAdvanced] = useState(false)
  const [selectedTypes, setSelectedTypes] = useState<string[]>([])
  const [selectedTags, setSelectedTags] = useState<string[]>([])
  const [dateRange, setDateRange] = useState<{ start: string; end: string }>({ start: '', end: '' })
  const [sortBy, setSortBy] = useState<SortOption>('relevance')
  const [viewMode, setViewMode] = useState<ViewMode>('list')
  const [activeTab, setActiveTab] = useState<'results' | 'history' | 'saved'>('results')

  const allTags = useMemo(() => {
    const tagsSet = new Set<string>()
    memoryEntries.forEach(entry => entry.tags.forEach(tag => tagsSet.add(tag)))
    return Array.from(tagsSet).sort()
  }, [])

  const filteredResults = useMemo(() => {
    let results = [...memoryEntries]

    if (searchQuery.trim()) {
      const query = searchQuery.toLowerCase()
      results = results.filter(entry =>
        entry.title.toLowerCase().includes(query) ||
        entry.content.toLowerCase().includes(query) ||
        entry.tags.some(tag => tag.toLowerCase().includes(query))
      )
      results.forEach(entry => {
        const titleMatch = entry.title.toLowerCase().includes(query) ? 0.4 : 0
        const contentMatch = (entry.content.toLowerCase().match(new RegExp(query, 'g')) || []).length * 0.05
        const tagMatch = entry.tags.some(tag => tag.toLowerCase().includes(query)) ? 0.3 : 0
        entry.relevanceScore = Math.min(1, titleMatch + contentMatch + tagMatch)
      })
    }

    if (selectedTypes.length > 0) {
      results = results.filter(entry => selectedTypes.includes(entry.type))
    }

    if (selectedTags.length > 0) {
      results = results.filter(entry =>
        selectedTags.some(tag => entry.tags.includes(tag))
      )
    }

    if (dateRange.start) {
      results = results.filter(entry => entry.timestamp >= dateRange.start)
    }
    if (dateRange.end) {
      results = results.filter(entry => entry.timestamp <= dateRange.end + 'T23:59:59')
    }

    switch (sortBy) {
      case 'relevance':
        results.sort((a, b) => (b.relevanceScore || 0) - (a.relevanceScore || 0))
        break
      case 'time':
        results.sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime())
        break
      case 'frequency':
        results.sort((a, b) => b.tags.length - a.tags.length)
        break
    }

    return results
  }, [searchQuery, selectedTypes, selectedTags, dateRange, sortBy])

  const toggleType = (type: string) => {
    setSelectedTypes(prev =>
      prev.includes(type) ? prev.filter(t => t !== type) : [...prev, type]
    )
  }

  const toggleTag = (tag: string) => {
    setSelectedTags(prev =>
      prev.includes(tag) ? prev.filter(t => t !== tag) : [...prev, tag]
    )
  }

  const clearFilters = () => {
    setSearchQuery('')
    setSelectedTypes([])
    setSelectedTags([])
    setDateRange({ start: '', end: '' })
  }

  return (
    <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
      <div className="border-b border-gray-200 px-6 py-4">
        <h2 className="text-xl font-semibold text-gray-900 flex items-center gap-2 mb-4">
          <span>🔍</span>
          记忆检索
        </h2>

        <div className="flex items-center gap-3 mb-3">
          <div className="flex-1 relative">
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="搜索记忆内容（支持模糊匹配）..."
              className="w-full px-4 py-2.5 pl-11 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent outline-none"
            />
            <span className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400">🔍</span>
            {searchQuery && (
              <button
                onClick={() => setSearchQuery('')}
                className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600"
              >
                ✕
              </button>
            )}
          </div>

          <button
            onClick={() => setShowAdvanced(!showAdvanced)}
            className={`px-4 py-2.5 rounded-lg font-medium transition-colors flex items-center gap-2 ${
              showAdvanced || selectedTypes.length > 0 || selectedTags.length > 0
                ? 'bg-primary-600 text-white'
                : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
            }`}
          >
            ⚙️ 高级搜索
          </button>
        </div>

        {showAdvanced && (
          <div className="bg-gray-50 rounded-lg p-4 space-y-4 animate-in slide-in-from-top">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">类型筛选</label>
              <div className="flex flex-wrap gap-2">
                {Object.entries(typeLabels).map(([key, label]) => (
                  <button
                    key={key}
                    onClick={() => toggleType(key)}
                    className={`px-3 py-1.5 rounded-full text-sm font-medium transition-all flex items-center gap-1.5 ${
                      selectedTypes.includes(key)
                        ? `${typeColors[key as keyof typeof typeColors]} ring-2 ring-offset-1 ring-primary-500`
                        : 'bg-white border border-gray-300 text-gray-700 hover:border-primary-300'
                    }`}
                  >
                    <span>{typeIcons[key as keyof typeof typeIcons]}</span>
                    {label}
                  </button>
                ))}
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">标签筛选</label>
              <div className="flex flex-wrap gap-2 max-h-32 overflow-y-auto">
                {allTags.map(tag => (
                  <button
                    key={tag}
                    onClick={() => toggleTag(tag)}
                    className={`px-3 py-1 rounded-full text-xs font-medium transition-all ${
                      selectedTags.includes(tag)
                        ? 'bg-primary-100 text-primary-700 ring-2 ring-offset-1 ring-primary-500'
                        : 'bg-white border border-gray-300 text-gray-600 hover:border-primary-300'
                    }`}
                  >
                    #{tag}
                  </button>
                ))}
              </div>
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">开始日期</label>
                <input
                  type="date"
                  value={dateRange.start}
                  onChange={(e) => setDateRange(prev => ({ ...prev, start: e.target.value }))}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 outline-none text-sm"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">结束日期</label>
                <input
                  type="date"
                  value={dateRange.end}
                  onChange={(e) => setDateRange(prev => ({ ...prev, end: e.target.value }))}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 outline-none text-sm"
                />
              </div>
            </div>

            {(selectedTypes.length > 0 || selectedTags.length > 0 || dateRange.start || dateRange.end) && (
              <button onClick={clearFilters} className="text-sm text-red-600 hover:text-red-700 font-medium">
                🗑️ 清除所有筛选条件
              </button>
            )}
          </div>
        )}

        <div className="flex items-center justify-between mt-4 pt-4 border-t border-gray-200">
          <div className="flex items-center gap-4">
            <div className="flex bg-gray-100 rounded-lg p-1">
              {(['results', 'history', 'saved'] as const).map(tab => (
                <button
                  key={tab}
                  onClick={() => setActiveTab(tab)}
                  className={`px-4 py-1.5 rounded-md text-sm font-medium transition-all ${
                    activeTab === tab
                      ? 'bg-white text-primary-600 shadow-sm'
                      : 'text-gray-600 hover:text-gray-900'
                  }`}
                >
                  {tab === 'results' ? `搜索结果 (${filteredResults.length})` :
                   tab === 'history' ? `搜索历史` : `已保存搜索`}
                </button>
              ))}
            </div>
          </div>

          <div className="flex items-center gap-3">
            <select
              value={sortBy}
              onChange={(e) => setSortBy(e.target.value as SortOption)}
              className="px-3 py-1.5 border border-gray-300 rounded-lg text-sm focus:ring-2 focus:ring-primary-500 outline-none"
            >
              <option value="relevance">相关度排序</option>
              <option value="time">时间排序</option>
              <option value="frequency">频率排序</option>
            </select>

            <div className="flex bg-gray-100 rounded-lg p-1">
              {(['list', 'card'] as ViewMode[]).map(mode => (
                <button
                  key={mode}
                  onClick={() => setViewMode(mode)}
                  className={`px-3 py-1.5 rounded-md text-sm font-medium transition-all ${
                    viewMode === mode
                      ? 'bg-white text-primary-600 shadow-sm'
                      : 'text-gray-600 hover:text-gray-900'
                  }`}
                >
                  {mode === 'list' ? '☰' : '▦'}
                </button>
              ))}
            </div>
          </div>
        </div>
      </div>

      <div className="p-6 min-h-[500px]">
        {activeTab === 'results' && (
          <>
            {filteredResults.length === 0 ? (
              <div className="text-center py-16">
                <p className="text-6xl mb-4">🔎</p>
                <p className="text-xl font-medium text-gray-900 mb-2">未找到匹配结果</p>
                <p className="text-gray-500">尝试调整搜索关键词或筛选条件</p>
              </div>
            ) : viewMode === 'list' ? (
              <div className="space-y-3">
                {filteredResults.map((entry) => (
                  <div
                    key={entry.id}
                    className="border border-gray-200 rounded-lg p-4 hover:border-primary-300 hover:shadow-md transition-all cursor-pointer group"
                  >
                    <div className="flex items-start justify-between mb-2">
                      <div className="flex items-center gap-3 flex-1">
                        <span className="text-2xl">{typeIcons[entry.type]}</span>
                        <div className="flex-1">
                          <h3 className="font-semibold text-gray-900 group-hover:text-primary-600 transition-colors">
                            {entry.title}
                          </h3>
                          <div className="flex items-center gap-3 mt-1 text-sm text-gray-500">
                            <span>{entry.source}</span>
                            <span>·</span>
                            <span>{new Date(entry.timestamp).toLocaleDateString('zh-CN', {
                              month: 'short',
                              day: 'numeric',
                              hour: '2-digit',
                              minute: '2-digit'
                            })}</span>
                          </div>
                        </div>
                      </div>
                      <div className="flex items-center gap-2 ml-4">
                        <span className={`px-2 py-1 rounded-full text-xs font-medium ${typeColors[entry.type]}`}>
                          {typeLabels[entry.type]}
                        </span>
                        {searchQuery && (
                          <span className="text-sm font-semibold text-primary-600 bg-primary-50 px-2 py-1 rounded">
                            {(entry.relevanceScore || 0).toFixed(0)}%
                          </span>
                        )}
                      </div>
                    </div>
                    <p className="text-sm text-gray-600 line-clamp-2 ml-11">{entry.summary}</p>
                    <div className="flex items-center gap-2 mt-2 ml-11">
                      {entry.tags.slice(0, 5).map(tag => (
                        <span key={tag} className="text-xs text-gray-500 bg-gray-100 px-2 py-0.5 rounded">
                          #{tag}
                        </span>
                      ))}
                      {entry.tags.length > 5 && (
                        <span className="text-xs text-gray-400">+{entry.tags.length - 5}</span>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                {filteredResults.map((entry) => (
                  <div
                    key={entry.id}
                    className="border border-gray-200 rounded-lg p-4 hover:border-primary-300 hover:shadow-md transition-all cursor-pointer group"
                  >
                    <div className="flex items-center gap-2 mb-3">
                      <span className="text-xl">{typeIcons[entry.type]}</span>
                      <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${typeColors[entry.type]}`}>
                        {typeLabels[entry.type]}
                      </span>
                    </div>
                    <h3 className="font-semibold text-gray-900 group-hover:text-primary-600 transition-colors mb-2 line-clamp-2">
                      {entry.title}
                    </h3>
                    <p className="text-sm text-gray-600 line-clamp-3 mb-3">{entry.summary}</p>
                    <div className="flex items-center justify-between text-xs text-gray-500">
                      <span>{entry.source}</span>
                      {searchQuery && <span className="font-semibold text-primary-600">{(entry.relevanceScore || 0).toFixed(0)}%</span>}
                    </div>
                    <div className="flex flex-wrap gap-1 mt-2">
                      {entry.tags.slice(0, 3).map(tag => (
                        <span key={tag} className="text-xs text-gray-500 bg-gray-100 px-1.5 py-0.5 rounded">
                          #{tag}
                        </span>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            )}
          </>
        )}

        {activeTab === 'history' && (
          <div className="space-y-2">
            {searchHistory.map((item) => (
              <div
                key={item.id}
                onClick={() => setSearchQuery(item.query)}
                className="flex items-center justify-between p-3 rounded-lg hover:bg-gray-50 cursor-pointer transition-colors group"
              >
                <div className="flex items-center gap-3">
                  <span className="text-gray-400 group-hover:text-primary-600">🕐</span>
                  <span className="font-medium text-gray-900">{item.query}</span>
                </div>
                <div className="flex items-center gap-3 text-sm text-gray-500">
                  <span>{item.resultCount} 条结果</span>
                  <span>{new Date(item.timestamp).toLocaleString('zh-CN')}</span>
                </div>
              </div>
            ))}
            {searchHistory.length === 0 && (
              <div className="text-center py-12 text-gray-500">
                暂无搜索历史记录
              </div>
            )}
          </div>
        )}

        {activeTab === 'saved' && (
          <div className="space-y-3">
            {savedSearches.map((item) => (
              <div
                key={item.id}
                className="border border-gray-200 rounded-lg p-4 hover:border-primary-300 transition-colors"
              >
                <div className="flex items-center justify-between mb-2">
                  <h4 className="font-semibold text-gray-900">{item.name}</h4>
                  <span className="text-xs text-gray-500">{new Date(item.createdAt).toLocaleDateString('zh-CN')}</span>
                </div>
                <p className="text-sm text-gray-600 mb-3">{item.query || '(使用高级筛选)'}</p>
                <div className="flex flex-wrap gap-2">
                  {item.filters.types.map(type => (
                    <span key={type} className={`px-2 py-0.5 rounded-full text-xs ${typeColors[type as keyof typeof typeColors]}`}>
                      {typeLabels[type as keyof typeof typeLabels]}
                    </span>
                  ))}
                  {item.filters.tags.map(tag => (
                    <span key={tag} className="px-2 py-0.5 rounded-full text-xs bg-gray-100 text-gray-600">
                      #{tag}
                    </span>
                  ))}
                </div>
              </div>
            ))}
            {savedSearches.length === 0 && (
              <div className="text-center py-12 text-gray-500">
                暂无保存的搜索条件
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  )
}

export default MemorySearch
