// apps/AgentPit/src/components/settings/HelpCenter.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import { useDebounce } from '../../composables/useDebounce'
import { faqData, versionInfo } from '../../data/mockSettings'

const searchQuery = ref('')
const debouncedSearch = useDebounce(() => searchQuery.value, 300)
const expandedId = ref<string | null>(null)
const activeCategory = ref<string | null>(null)

const categories = [
  { id: 'getting-started', label: '🚀 快速入门', count: 0 },
  { id: 'features', label: '🔧 功能使用', count: 0 },
  { id: 'billing', label: '💰 计费与支付', count: 0 },
  { id: 'security', label: '🔐 安全与隐私', count: 0 },
  { id: 'troubleshooting', label: '❌ 故障排除', count: 0 },
]

categories.forEach(cat => {
  cat.count = faqData.filter(f => f.category === cat.id).length
})

const filteredFAQs = computed(() => {
  const q = debouncedSearch.value.toLowerCase().trim()
  let result = faqData
  if (activeCategory.value) {
    result = result.filter(f => f.category === activeCategory.value)
  }
  if (q) {
    result = result.filter(f =>
      f.title.toLowerCase().includes(q) ||
      f.content.toLowerCase().includes(q) ||
      f.tags.some(t => t.toLowerCase().includes(q))
    )
  }
  return result
})

const groupedFAQs = computed(() => {
  const groups: Record<string, typeof faqData> = {}
  categories.forEach(cat => { groups[cat.id] = [] })
  filteredFAQs.value.forEach(faq => {
    if (!groups[faq.category]) groups[faq.category] = []
    groups[faq.category].push(faq)
  })
  return groups
})

function toggleExpand(id: string) {
  expandedId.value = expandedId.value === id ? null : id
}

function setCategory(catId: string | null) {
  activeCategory.value = catId
  expandedId.value = null
}

function renderMarkdown(text: string): string {
  return text
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
    .replace(/\n/g, '<br/>')
    .replace(/- (.*)/g, '<li>$1</li>')
    .replace(/(\d+)\. (.*)/g, '$2')
}
</script>

<template>
  <div class="help-center">
    <h3 class="text-lg font-bold text-gray-900 dark:text-white mb-6">❓ 帮助中心</h3>

    <!-- 搜索框 -->
    <div class="relative mb-6">
      <svg class="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"/></svg>
      <input
v-model="searchQuery" type="text" placeholder="搜索问题、关键词..."
        class="w-full pl-12 pr-4 py-3 rounded-xl border border-gray-200 dark:border-gray-600 bg-white dark:bg-gray-800 text-gray-900 dark:text-white focus:ring-2 focus:ring-indigo-400 outline-none" />
      <span v-if="searchQuery && !debouncedSearch" class="absolute right-4 top-1/2 -translate-y-1/2 text-xs text-gray-400">搜索中...</span>
    </div>

    <!-- 分类筛选 -->
    <div class="flex flex-wrap gap-2 mb-6">
      <button
:class="[
        'px-3 py-1.5 rounded-full text-sm font-medium transition-all',
        !activeCategory ? 'bg-indigo-500 text-white shadow-md' : 'bg-gray-100 dark:bg-gray-700 text-gray-600 dark:text-gray-400 hover:bg-gray-200'
      ]" @click="setCategory(null)">
        全部 ({{ faqData.length }})
      </button>
      <button
v-for="cat in categories" :key="cat.id" :class="[
        'px-3 py-1.5 rounded-full text-sm font-medium transition-all',
        activeCategory === cat.id ? 'bg-indigo-500 text-white shadow-md' : 'bg-gray-100 dark:bg-gray-700 text-gray-600 dark:text-gray-400 hover:bg-gray-200'
      ]" @click="setCategory(cat.id)">{{ cat.label }} ({{ cat.count }})</button>
    </div>

    <!-- FAQ 折叠面板列表 -->
    <div class="space-y-3">
      <template v-for="(faqs, categoryId) in groupedFAQs" :key="categoryId">
        <div v-if="faqs.length > 0">
          <p class="text-sm font-semibold text-gray-500 dark:text-gray-400 mb-2 mt-4 first:mt-0">
            {{ categories.find(c => c.id === categoryId)?.label }}
          </p>

          <TransitionGroup name="faq-list">
            <div
v-for="faq in faqs" :key="faq.id"
              class="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 overflow-hidden transition-all hover:border-indigo-200 dark:hover:border-indigo-800">
              <button
class="w-full flex items-center justify-between p-4 text-left group"
                @click="toggleExpand(faq.id)">
                <div class="flex items-center gap-3 flex-1 min-w-0">
                  <span class="text-lg flex-shrink-0">{{ expandedId === faq.id ? '📖' : '💡' }}</span>
                  <span class="font-medium text-gray-900 dark:text-white group-hover:text-indigo-600 dark:group-hover:text-indigo-400 transition-colors truncate">{{ faq.title }}</span>
                </div>
                <svg
class="w-5 h-5 text-gray-400 transition-transform duration-200 flex-shrink-0 ml-2"
                  :class="{ 'rotate-180': expandedId === faq.id }" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"/>
                </svg>
              </button>

              <Transition name="accordion">
                <div v-if="expandedId === faq.id" class="px-4 pb-4 overflow-hidden">
                  <div class="pl-10 pr-2 pt-2 border-t border-gray-100 dark:border-gray-700">
                    <div
class="prose prose-sm dark:prose-invert max-w-none text-sm text-gray-600 dark:text-gray-400 leading-relaxed space-y-2"
                      v-html="renderMarkdown(faq.content)">
                    </div>
                    <div class="flex flex-wrap gap-1.5 mt-3 pt-2 border-t border-gray-100 dark:border-gray-700">
                      <span v-for="tag in faq.tags" :key="tag" class="px-2 py-0.5 text-xs bg-indigo-50 dark:bg-indigo-900/30 text-indigo-600 dark:text-indigo-400 rounded-full">{{ tag }}</span>
                    </div>
                  </div>
                </div>
              </Transition>
            </div>
          </TransitionGroup>
        </div>
      </template>

      <div v-if="filteredFAQs.length === 0" class="text-center py-12 text-gray-400">
        <span class="text-4xl block mb-3">🔍</span>
        <p>未找到相关问题</p>
        <p class="text-sm mt-1">尝试使用其他关键词搜索</p>
      </div>
    </div>

    <!-- 联系客服和快捷键 -->
    <div class="grid grid-cols-1 sm:grid-cols-2 gap-4 mt-8 pt-6 border-t border-gray-200 dark:border-gray-700">
      <div class="p-4 bg-gradient-to-br from-green-50 to-emerald-50 dark:from-green-900/20 dark:to-emerald-900/20 rounded-xl">
        <h4 class="font-semibold text-gray-900 dark:text-white mb-2">💬 联系客服</h4>
        <div class="space-y-2 text-sm">
          <a href="#" class="flex items-center gap-2 text-green-700 dark:text-green-400 hover:underline">
            <span>💬</span> 在线聊天
          </a>
          <a href="#" class="flex items-center gap-2 text-green-700 dark:text-green-400 hover:underline">
            <span>📧</span> support@example.com
          </a>
          <a href="#" class="flex items-center gap-2 text-green-700 dark:text-green-400 hover:underline">
            <span>📞</span> 400-123-4567
          </a>
        </div>
      </div>

      <div class="p-4 bg-gradient-to-br from-blue-50 to-indigo-50 dark:from-blue-900/20 dark:to-indigo-900/20 rounded-xl">
        <h4 class="font-semibold text-gray-900 dark:text-white mb-2">⌨️ 常用快捷键</h4>
        <div class="space-y-1.5 text-xs">
          <div class="flex justify-between"><span class="text-gray-600 dark:text-gray-400">全局搜索</span><kbd class="px-1.5 py-0.5 bg-gray-200 dark:bg-gray-700 rounded text-gray-700 dark:text-gray-300 font-mono">Ctrl+K</kbd></div>
          <div class="flex justify-between"><span class="text-gray-600 dark:text-gray-400">切换侧边栏</span><kbd class="px-1.5 py-0.5 bg-gray-200 dark:bg-gray-700 rounded text-gray-700 dark:text-gray-300 font-mono">Ctrl+B</kbd></div>
          <div class="flex justify-between"><span class="text-gray-600 dark:text-gray-400">保存内容</span><kbd class="px-1.5 py-0.5 bg-gray-200 dark:bg-gray-700 rounded text-gray-700 dark:text-gray-300 font-mono">Ctrl+S</kbd></div>
          <div class="flex justify-between"><span class="text-gray-600 dark:text-gray-400">关闭弹窗</span><kbd class="px-1.5 py-0.5 bg-gray-200 dark:bg-gray-700 rounded text-gray-700 dark:text-gray-300 font-mono">Esc</kbd></div>
          <div class="flex justify-between"><span class="text-gray-600 dark:text-gray-400">快捷键帮助</span><kbd class="px-1.5 py-0.5 bg-gray-200 dark:bg-gray-700 rounded text-gray-700 dark:text-gray-300 font-mono">Ctrl+/</kbd></div>
        </div>
      </div>
    </div>

    <!-- 版本信息 -->
    <div class="mt-6 text-center text-xs text-gray-400">
      <p>{{ versionInfo.version }} · 发布于 {{ versionInfo.releaseDate }}</p>
      <p class="mt-1">© 2026 AgentPit Team. All rights reserved.</p>
    </div>
  </div>
</template>

<style scoped>
.faq-list-enter-active, .faq-list-leave-active { transition: all 0.3s ease; }
.faq-list-enter-from { opacity: 0; transform: translateY(-10px); }
.faq-list-leave-to { opacity: 0; transform: translateY(10px); }

.accordion-enter-active, .accordion-leave-active {
  transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
  overflow: hidden;
}
.accordion-enter-from, .accordion-leave-to {
  max-height: 0;
  opacity: 0;
  padding-top: 0;
  padding-bottom: 0;
}
.accordion-enter-to, .accordion-leave-from {
  max-height: 500px;
  opacity: 1;
}

.prose strong { color: inherit; font-weight: 600; }
.prose li::before { content: "• "; color: #6366f1; font-weight: bold; margin-right: 4px; }
.prose br + li::before { display: none; }
</style>

// apps/AgentPit/src/components/settings/HelpCenter.tsx
import { useState } from 'react'
import { faqData, helpArticles, updateLogs } from '../../data/mockSettings'

type ActiveTab = 'faq' | 'articles' | 'contact' | 'updates' | null
type FAQCategory = FAQItem['category'] | 'all'
type ArticleView = 'list' | 'detail'

interface FAQItem {
  id: string
  category: string
  title: string
  summary: string
  content: string
  tags: string[]
  updatedAt: string
  helpful: number
  notHelpful: number
}

const HelpCenter = () => {
  const [searchQuery, setSearchQuery] = useState('')
  const [selectedCategory, setSelectedCategory] = useState<FAQCategory>('all')
  const [expandedFAQ, setExpandedFAQ] = useState<string | null>(null)
  const [activeTab, setActiveTab] = useState<ActiveTab>('faq')
  const [articleView, setArticleView] = useState<ArticleView>('list')
  const [selectedArticle, setSelectedArticle] = useState<string | null>(null)
  const [showContactForm, setShowContactForm] = useState(false)
  const [feedbackMessage, setFeedbackMessage] = useState('')

  const categories = [
    { key: 'all' as FAQCategory, label: '全部', icon: '📚' },
    { key: 'getting-started' as FAQCategory, label: '入门指南', icon: '🚀' },
    { key: 'features' as FAQCategory, label: '功能说明', icon: '📖' },
    { key: 'faq' as FAQCategory, label: '常见问题', icon: '❓' },
    { key: 'troubleshooting' as FAQCategory, label: '故障排除', icon: '🔧' },
    { key: 'support' as FAQCategory, label: '联系客服', icon: '💬' },
  ]

  const filteredFAQs = faqData.filter(faq => {
    const matchesCategory = selectedCategory === 'all' || faq.category === selectedCategory
    const matchesSearch = !searchQuery ||
      faq.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
      faq.summary.toLowerCase().includes(searchQuery.toLowerCase()) ||
      faq.tags.some(tag => tag.toLowerCase().includes(searchQuery.toLowerCase()))
    return matchesCategory && matchesSearch
  })

  const handleVote = (_faqId: string, helpful: boolean) => {
    setFeedbackMessage(helpful ? '感谢您的反馈！' : '我们会努力改进！')
    setTimeout(() => setFeedbackMessage(''), 3000)
  }

  return (
    <div className="space-y-6">
      <div className="bg-white rounded-xl shadow p-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-6">帮助中心</h2>

        <div className="space-y-8">
          <div className="relative">
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="搜索帮助文档、常见问题..."
              className="w-full px-6 py-4 pl-14 text-lg border border-gray-300 rounded-xl focus:outline-none focus:ring-2 focus:ring-primary-500"
            />
            <span className="absolute left-5 top-1/2 -translate-y-1/2 text-2xl text-gray-400">🔍</span>
          </div>

          <div className="flex space-x-2 bg-gray-100 rounded-lg p-1 overflow-x-auto">
            {[
              { key: 'faq' as ActiveTab, label: '常见问题', icon: '❓' },
              { key: 'articles' as ActiveTab, label: '帮助文章', icon: '📄' },
              { key: 'contact' as ActiveTab, label: '联系客服', icon: '💬' },
              { key: 'updates' as ActiveTab, label: '更新日志', icon: '📋' },
            ].map(tab => (
              <button
                key={tab.key}
                onClick={() => setActiveTab(tab.key)}
                className={`px-5 py-2.5 rounded-md text-sm font-medium transition-colors flex items-center space-x-2 whitespace-nowrap ${
                  activeTab === tab.key ? 'bg-white shadow text-primary-600' : 'text-gray-600 hover:text-gray-900'
                }`}
              >
                <span>{tab.icon}</span>
                <span>{tab.label}</span>
              </button>
            ))}
          </div>

          {activeTab === 'faq' && (
            <div>
              <div className="flex items-center justify-between">
                <h3 className="text-lg font-semibold text-gray-900">FAQ 分类</h3>
              </div>
              <div className="flex flex-wrap gap-2">
                {categories.map(cat => (
                  <button
                    key={cat.key}
                    onClick={() => setSelectedCategory(cat.key)}
                    className={`px-4 py-2 rounded-full font-medium transition-all ${
                      selectedCategory === cat.key
                        ? 'bg-primary-600 text-white shadow-md'
                        : 'bg-white border border-gray-200 text-gray-700 hover:border-primary-300'
                    }`}
                  >
                    {cat.icon} {cat.label}
                  </button>
                ))}
              </div>

              <div className="space-y-3 max-h-[600px] overflow-y-auto pr-2">
                {filteredFAQs.length > 0 ? filteredFAQs.map(faq => (
                  <div
                    key={faq.id}
                    className={`border rounded-xl overflow-hidden transition-all ${
                      expandedFAQ === faq.id ? 'border-primary-300 shadow-md' : 'border-gray-200 hover:border-gray-300'
                    }`}
                  >
                    <button
                      onClick={() => setExpandedFAQ(expandedFAQ === faq.id ? null : faq.id)}
                      className="w-full p-5 text-left flex items-start justify-between bg-white hover:bg-gray-50 transition-colors"
                    >
                      <div className="flex-1 pr-4">
                        <h4 className="font-semibold text-gray-900 mb-1">{faq.title}</h4>
                        <p className="text-sm text-gray-600">{faq.summary}</p>
                        <div className="flex items-center space-x-2 mt-2">
                          {faq.tags.slice(0, 3).map(tag => (
                            <span key={tag} className="px-2 py-0.5 bg-gray-100 text-gray-600 rounded text-xs">
                              {tag}
                            </span>
                          ))}
                          <span className="text-xs text-gray-400">更新于 {faq.updatedAt}</span>
                        </div>
                      </div>
                      <span className={`transform transition-transform ${expandedFAQ === faq.id ? 'rotate-180' : ''}`}>
                        ▼
                      </span>
                    </button>

                    {expandedFAQ === faq.id && (
                      <div className="p-5 bg-gray-50 border-t border-gray-200">
                        <div className="prose prose-sm max-w-none text-gray-700 whitespace-pre-line leading-relaxed">
                          {faq.content}
                        </div>
                        <div className="mt-6 pt-4 border-t border-gray-200">
                          <p className="text-sm text-gray-600 mb-3">这篇文章对您有帮助吗？</p>
                          <div className="flex space-x-3">
                            <button
                              onClick={() => handleVote(faq.id, true)}
                              className="flex items-center space-x-2 px-4 py-2 bg-green-50 text-green-700 rounded-lg hover:bg-green-100 transition-colors"
                            >
                              <span>👍</span>
                              <span>有帮助 ({faq.helpful})</span>
                            </button>
                            <button
                              onClick={() => handleVote(faq.id, false)}
                              className="flex items-center space-x-2 px-4 py-2 bg-red-50 text-red-700 rounded-lg hover:bg-red-100 transition-colors"
                            >
                              <span>👎</span>
                              <span>没帮助 ({faq.notHelpful})</span>
                            </button>
                          </div>
                        </div>
                      </div>
                    )}
                  </div>
                )) : (
                  <div className="text-center py-12">
                    <p className="text-5xl mb-4">🔍</p>
                    <h4 className="text-xl font-semibold text-gray-900 mb-2">未找到相关内容</h4>
                    <p className="text-gray-500 mb-4">尝试使用其他关键词搜索，或浏览其他分类</p>
                    <button
                      onClick={() => { setSearchQuery(''); setSelectedCategory('all') }}
                      className="px-6 py-2 bg-primary-600 text-white rounded-lg hover:bg-primary-700 transition-colors"
                    >
                      清除筛选
                    </button>
                  </div>
                )}
              </div>
            </div>
          )}

          {activeTab === 'articles' && (
            <div>
              {articleView === 'list' ? (
                <div className="space-y-4">
                  <h3 className="text-lg font-semibold text-gray-900 mb-4">帮助文章列表</h3>
                  {helpArticles.map(article => (
                    <button
                      key={article.id}
                      onClick={() => { setSelectedArticle(article.id); setArticleView('detail') }}
                      className="w-full p-6 bg-white border border-gray-200 rounded-xl hover:bg-gray-50 hover:border-primary-300 transition-all text-left group"
                    >
                      <div className="flex items-start justify-between mb-3">
                        <h4 className="font-semibold text-lg text-gray-900 group-hover:text-primary-600 transition-colors">
                          {article.title}
                        </h4>
                        <span className="text-xs text-gray-500 flex-shrink-0 ml-4">{article.readTime}分钟阅读</span>
                      </div>
                      <p className="text-sm text-gray-600 mb-3 line-clamp-2">{article.summary}</p>
                      <div className="flex items-center justify-between">
                        <div className="flex flex-wrap gap-2">
                          {article.tags.map(tag => (
                            <span key={tag} className="px-2 py-1 bg-gray-100 text-gray-600 rounded text-xs">
                              {tag}
                            </span>
                          ))}
                        </div>
                        <span className="text-xs text-gray-400">更新于 {article.updatedAt}</span>
                      </div>
                    </button>
                  ))}
                </div>
              ) : (
                <div>
                  <button
                    onClick={() => { setArticleView('list'); setSelectedArticle(null) }}
                    className="mb-4 text-primary-600 hover:text-primary-700 font-medium"
                  >
                    ← 返回文章列表
                  </button>
                  {(() => {
                    const article = helpArticles.find(a => a.id === selectedArticle)
                    if (!article) return null
                    return (
                      <article className="prose prose-lg max-w-none">
                        <h1 className="text-3xl font-bold text-gray-900 mb-4">{article.title}</h1>
                        <div className="flex items-center space-x-4 text-sm text-gray-500 mb-6 pb-6 border-b border-gray-200">
                          <span>更新时间：{article.updatedAt}</span>
                          <span>阅读时长：{article.readTime}分钟</span>
                        </div>
                        <div className="whitespace-pre-line text-gray-700 leading-relaxed">{article.content}</div>
                        <div className="mt-8 pt-6 border-t border-gray-200">
                          <h3 className="font-semibold text-gray-900 mb-4">相关文章推荐</h3>
                          <div className="grid grid-cols-2 gap-4">
                            {helpArticles.filter(a => a.id !== article.id).slice(0, 2).map(related => (
                              <button
                                key={related.id}
                                onClick={() => setSelectedArticle(related.id)}
                                className="p-4 bg-gray-50 rounded-lg hover:bg-gray-100 transition-colors text-left"
                              >
                                <h4 className="font-medium text-gray-900 mb-1">{related.title}</h4>
                                <p className="text-sm text-gray-500 truncate">{related.summary}</p>
                              </button>
                            ))}
                          </div>
                        </div>
                      </article>
                    )
                  })()}
                </div>
              )}
            </div>
          )}

          {activeTab === 'contact' && (
            <div className="space-y-6">
              {!showContactForm ? (
                <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                  <button
                    onClick={() => setShowContactForm(true)}
                    className="p-8 bg-gradient-to-br from-blue-50 to-indigo-50 border-2 border-blue-200 rounded-xl hover:shadow-lg transition-all group"
                  >
                    <div className="w-16 h-16 bg-blue-100 rounded-2xl flex items-center justify-center text-3xl mx-auto mb-4 group-hover:scale-110 transition-transform">
                      💬
                    </div>
                    <h4 className="font-bold text-gray-900 text-center mb-2">在线客服</h4>
                    <p className="text-sm text-gray-600 text-center">实时聊天，平均响应 &lt; 5分钟</p>
                    <p className="text-xs text-blue-600 text-center mt-3 font-medium">工作时间：9:00 - 22:00</p>
                  </button>

                  <a
                    href="mailto:support@example.com"
                    className="p-8 bg-gradient-to-br from-green-50 to-emerald-50 border-2 border-green-200 rounded-xl hover:shadow-lg transition-all group block"
                  >
                    <div className="w-16 h-16 bg-green-100 rounded-2xl flex items-center justify-center text-3xl mx-auto mb-4 group-hover:scale-110 transition-transform">
                      📧
                    </div>
                    <h4 className="font-bold text-gray-900 text-center mb-2">邮件支持</h4>
                    <p className="text-sm text-gray-600 text-center">24小时内回复</p>
                    <p className="text-xs text-green-600 text-center mt-3 font-medium">support@example.com</p>
                  </a>

                  <button
                    onClick={() => setShowContactForm(true)}
                    className="p-8 bg-gradient-to-br from-purple-50 to-pink-50 border-2 border-purple-200 rounded-xl hover:shadow-lg transition-all group"
                  >
                    <div className="w-16 h-16 bg-purple-100 rounded-2xl flex items-center justify-center text-3xl mx-auto mb-4 group-hover:scale-110 transition-transform">
                      📝
                    </div>
                    <h4 className="font-bold text-gray-900 text-center mb-2">反馈表单</h4>
                    <p className="text-sm text-gray-600 text-center">提交详细问题描述</p>
                    <p className="text-xs text-purple-600 text-center mt-3 font-medium">1-3个工作日回复</p>
                  </button>
                </div>
              ) : (
                <div className="max-w-2xl mx-auto">
                  <button
                    onClick={() => setShowContactForm(false)}
                    className="mb-4 text-primary-600 hover:text-primary-700 font-medium"
                  >
                    ← 返回联系方式
                  </button>
                  <div className="bg-white border border-gray-200 rounded-xl p-8">
                    <h3 className="text-2xl font-bold text-gray-900 mb-6">联系我们</h3>
                    <form className="space-y-5" onSubmit={(e) => e.preventDefault()}>
                      <div className="grid grid-cols-2 gap-4">
                        <div>
                          <label className="block text-sm font-medium text-gray-700 mb-2">姓名 *</label>
                          <input type="text" required className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500" placeholder="您的姓名" />
                        </div>
                        <div>
                          <label className="block text-sm font-medium text-gray-700 mb-2">邮箱 *</label>
                          <input type="email" required className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500" placeholder="your@email.com" />
                        </div>
                      </div>
                      <div>
                        <label className="block text-sm font-medium text-gray-700 mb-2">问题类型</label>
                        <select className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500">
                          <option>技术问题</option>
                          <option>账户问题</option>
                          <option>功能建议</option>
                          <option>其他问题</option>
                        </select>
                      </div>
                      <div>
                        <label className="block text-sm font-medium text-gray-700 mb-2">详细描述 *</label>
                        <textarea rows={6} required className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 resize-none" placeholder="请详细描述您遇到的问题或建议..." />
                      </div>
                      <button
                        type="submit"
                        onClick={() => alert('反馈已提交，我们将尽快与您联系！')}
                        className="w-full py-3 bg-primary-600 text-white rounded-lg hover:bg-primary-700 transition-colors font-medium"
                      >
                        提交反馈
                      </button>
                    </form>
                  </div>
                </div>
              )}

              <div className="bg-gradient-to-r from-yellow-50 to-orange-50 rounded-xl p-6 border border-yellow-200 mt-6">
                <h4 className="font-semibold text-gray-900 mb-3">💡 获取更快帮助的技巧</h4>
                <ul className="text-sm text-gray-600 space-y-2 list-disc list-inside">
                  <li>先在上方搜索框中查找相关文档，90%的问题都能快速解决</li>
                  <li>提供详细的错误信息和截图可以帮助我们更快定位问题</li>
                  <li>描述问题时请包含您的操作系统和浏览器版本信息</li>
                  <li>紧急问题建议直接使用在线客服获取即时支持</li>
                </ul>
              </div>
            </div>
          )}

          {activeTab === 'updates' && (
            <div className="space-y-6">
              <h3 className="text-lg font-semibold text-gray-900 mb-4">版本更新历史</h3>
              {updateLogs.map((log, index) => (
                <div key={index} className="bg-white border border-gray-200 rounded-xl overflow-hidden hover:shadow-md transition-shadow">
                  <div className="bg-gradient-to-r from-primary-500 to-primary-600 px-6 py-4 flex items-center justify-between">
                    <div className="flex items-center space-x-4">
                      <span className="text-2xl font-bold text-white">{log.version}</span>
                      <span className="text-white/80">{log.date}</span>
                    </div>
                    <span className="px-3 py-1 bg-white/20 text-white rounded-full text-sm font-medium">
                      最新版本
                    </span>
                  </div>
                  <div className="p-6">
                    <ul className="space-y-3">
                      {log.features.map((feature, fIndex) => (
                        <li key={fIndex} className="flex items-start space-x-3">
                          <span className="text-green-500 mt-1">✓</span>
                          <span className="text-gray-700">{feature}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>
              ))}

              <div className="bg-blue-50 border border-blue-200 rounded-xl p-6">
                <h4 className="font-semibold text-blue-900 mb-2">🔔 订阅更新通知</h4>
                <p className="text-sm text-blue-800 mb-4">第一时间获取新功能发布和重要更新通知</p>
                <button className="px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors font-medium">
                  订阅更新
                </button>
              </div>
            </div>
          )}
        </div>
      </div>

      {feedbackMessage && (
        <div className="fixed top-20 right-6 bg-green-500 text-white px-6 py-4 rounded-xl shadow-2xl flex items-center space-x-3 animate-slide-in z-50">
          <span className="text-2xl">✓</span>
          <span className="font-medium">{feedbackMessage}</span>
        </div>
      )}
    </div>
  )
}

export default HelpCenter
