// apps/AgentPit/src/components/settings/ThemePreferences.tsx
import { useState } from 'react'
import { type ThemeSettings, defaultThemeSettings } from '../../data/mockSettings'

const ThemePreferences = () => {
  const [settings, setSettings] = useState<ThemeSettings>(defaultThemeSettings)
  const [showSuccessMessage, setShowSuccessMessage] = useState(false)

  const themeModes = [
    { value: 'light' as const, label: '浅色模式', icon: '☀️', desc: '明亮清爽的界面风格' },
    { value: 'dark' as const, label: '深色模式', icon: '🌙', desc: '护眼舒适的暗色主题' },
    { value: 'system' as const, label: '跟随系统', icon: '💻', desc: '自动适应系统设置' },
  ]

  const fontSizes = [
    { value: 'small' as const, label: '小', size: '14px', preview: '示例文字 Aa' },
    { value: 'medium' as const, label: '中', size: '16px', preview: '示例文字 Aa' },
    { value: 'large' as const, label: '大', size: '18px', preview: '示例文字 Aa' },
    { value: 'xlarge' as const, label: '特大', size: '20px', preview: '示例文字 Aa' },
  ]

  const layoutDensities = [
    { value: 'comfortable' as const, label: '舒适', desc: '适中的间距和留白' },
    { value: 'compact' as const, label: '紧凑', desc: '更紧凑的布局，显示更多内容' },
    { value: 'spacious' as const, label: '宽松', desc: '更大的间距，更轻松的视觉体验' },
  ]

  const sidebarModes = [
    { value: 'always' as const, label: '始终显示', icon: '📌' },
    { value: 'auto' as const, label: '自动隐藏', icon: '👁️' },
    { value: 'hidden' as const, label: '不显示', icon: '🚫' },
  ]

  const presetColors = [
    '#6366f1', '#8b5cf6', '#ec4899', '#ef4444',
    '#f97316', '#eab308', '#22c55e', '#14b8a6',
    '#06b6d4', '#3b82f6', '#64748b', '#000000',
  ]

  const handleSave = () => {
    setShowSuccessMessage(true)
    setTimeout(() => setShowSuccessMessage(false), 3000)
  }

  return (
    <div className="space-y-6">
      <div className="bg-white rounded-xl shadow p-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-6">主题和外观</h2>

        <div className="space-y-10">
          <div>
            <h3 className="text-lg font-semibold text-gray-900 mb-4">主题模式</h3>
            <div className="grid grid-cols-3 gap-4">
              {themeModes.map(mode => (
                <button
                  key={mode.value}
                  onClick={() => setSettings({ ...settings, mode: mode.value })}
                  className={`p-6 rounded-xl border-2 transition-all ${
                    settings.mode === mode.value
                      ? 'border-primary-500 bg-primary-50 shadow-lg'
                      : 'border-gray-200 hover:border-gray-300 bg-white'
                  }`}
                >
                  <span className="text-4xl block mb-3">{mode.icon}</span>
                  <p className="font-semibold text-gray-900">{mode.label}</p>
                  <p className="text-sm text-gray-500 mt-1">{mode.desc}</p>
                  {settings.mode === mode.value && (
                    <div className="mt-3 flex items-center justify-center space-x-1 text-primary-600">
                      <span>✓</span>
                      <span className="text-sm font-medium">已选择</span>
                    </div>
                  )}
                </button>
              ))}
            </div>
          </div>

          <div>
            <h3 className="text-lg font-semibold text-gray-900 mb-4">自定义主题色</h3>
            <div className="flex items-center space-x-6">
              <div className="flex flex-wrap gap-3">
                {presetColors.map(color => (
                  <button
                    key={color}
                    onClick={() => setSettings({ ...settings, primaryColor: color })}
                    className={`w-12 h-12 rounded-full transition-all transform hover:scale-110 ${
                      settings.primaryColor === color ? 'ring-4 ring-offset-2 ring-primary-300 scale-110' : ''
                    }`}
                    style={{ backgroundColor: color }}
                  />
                ))}
              </div>
              <div className="flex-1 max-w-xs">
                <label className="block text-sm font-medium text-gray-700 mb-2">自定义颜色</label>
                <input
                  type="color"
                  value={settings.primaryColor}
                  onChange={(e) => setSettings({ ...settings, primaryColor: e.target.value })}
                  className="w-full h-12 rounded-lg cursor-pointer"
                />
              </div>
            </div>
          </div>

          <div>
            <h3 className="text-lg font-semibold text-gray-900 mb-4">字体大小</h3>
            <div className="grid grid-cols-4 gap-4">
              {fontSizes.map(size => (
                <button
                  key={size.value}
                  onClick={() => setSettings({ ...settings, fontSize: size.value })}
                  className={`p-4 rounded-xl border-2 transition-all ${
                    settings.fontSize === size.value
                      ? 'border-primary-500 bg-primary-50'
                      : 'border-gray-200 hover:border-gray-300 bg-white'
                  }`}
                >
                  <p style={{ fontSize: size.size }} className="font-medium text-gray-900 mb-1">{size.preview}</p>
                  <p className="text-sm text-gray-500">{size.label}</p>
                </button>
              ))}
            </div>
          </div>

          <div>
            <h3 className="text-lg font-semibold text-gray-900 mb-4">布局密度</h3>
            <div className="grid grid-cols-3 gap-4">
              {layoutDensities.map(density => (
                <button
                  key={density.value}
                  onClick={() => setSettings({ ...settings, layoutDensity: density.value })}
                  className={`p-5 rounded-xl border-2 transition-all ${
                    settings.layoutDensity === density.value
                      ? 'border-primary-500 bg-primary-50 shadow-md'
                      : 'border-gray-200 hover:border-gray-300 bg-white'
                  }`}
                >
                  <p className="font-semibold text-gray-900 mb-1">{density.label}</p>
                  <p className="text-sm text-gray-500">{density.desc}</p>
                </button>
              ))}
            </div>
          </div>

          <div>
            <h3 className="text-lg font-semibold text-gray-900 mb-4">侧边栏设置</h3>
            <div className="grid grid-cols-3 gap-4">
              {sidebarModes.map(mode => (
                <button
                  key={mode.value}
                  onClick={() => setSettings({ ...settings, sidebarMode: mode.value })}
                  className={`p-5 rounded-xl border-2 transition-all flex items-center space-x-3 ${
                    settings.sidebarMode === mode.value
                      ? 'border-primary-500 bg-primary-50 shadow-md'
                      : 'border-gray-200 hover:border-gray-300 bg-white'
                  }`}
                >
                  <span className="text-2xl">{mode.icon}</span>
                  <p className="font-semibold text-gray-900">{mode.label}</p>
                </button>
              ))}
            </div>
          </div>

          <div>
            <div className="flex items-center justify-between p-6 bg-gradient-to-r from-blue-50 to-indigo-50 rounded-xl border border-blue-200">
              <div className="flex items-start space-x-4">
                <div className="w-12 h-12 bg-blue-100 rounded-xl flex items-center justify-center text-2xl">♿</div>
                <div>
                  <h4 className="font-semibold text-gray-900">减少动画模式</h4>
                  <p className="text-sm text-gray-600 mt-1">减少或关闭动画效果，提升无障碍访问体验，适合对动态效果敏感的用户</p>
                </div>
              </div>
              <label className="relative inline-flex items-center cursor-pointer ml-4">
                <input
                  type="checkbox"
                  checked={settings.reduceMotion}
                  onChange={(e) => setSettings({ ...settings, reduceMotion: e.target.checked })}
                  className="sr-only peer"
                />
                <div className="w-14 h-7 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-blue-300 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-6 after:w-6 after:transition-all peer-checked:bg-blue-600"></div>
              </label>
            </div>
          </div>

          <div className="pt-6 border-t border-gray-200">
            <h3 className="text-lg font-semibold text-gray-900 mb-4">实时预览</h3>
            <div className={`rounded-xl p-6 ${settings.mode === 'dark' ? 'bg-gray-800' : 'bg-gray-50'} border-2 ${settings.layoutDensity === 'compact' ? 'p-4' : settings.layoutDensity === 'spacious' ? 'p-8' : 'p-6'}`}>
              <div className="space-y-4" style={{ fontSize: settings.fontSize === 'small' ? '14px' : settings.fontSize === 'large' ? '18px' : settings.fontSize === 'xlarge' ? '20px' : '16px' }}>
                <div className="flex items-center space-x-3">
                  <div className="w-10 h-10 rounded-full flex items-center justify-center text-white font-bold" style={{ backgroundColor: settings.primaryColor }}>
                    U
                  </div>
                  <div className="flex-1">
                    <div className="h-3 bg-gray-300 dark:bg-gray-600 rounded w-32 mb-2"></div>
                    <div className="h-2 bg-gray-200 dark:bg-gray-700 rounded w-48"></div>
                  </div>
                </div>
                <div className="space-y-2">
                  <div className="h-24 bg-white dark:bg-gray-700 rounded-lg border border-gray-200 dark:border-gray-600 p-4">
                    <div className="h-3 bg-gray-200 dark:bg-gray-600 rounded w-24 mb-3"></div>
                    <div className="space-y-2">
                      <div className="h-2 bg-gray-200 dark:bg-gray-600 rounded"></div>
                      <div className="h-2 bg-gray-200 dark:bg-gray-600 rounded w-5/6"></div>
                    </div>
                  </div>
                  <div className="flex space-x-2">
                    <div className="h-9 rounded-lg flex-1" style={{ backgroundColor: settings.primaryColor }}></div>
                    <div className="h-9 bg-gray-200 dark:bg-gray-700 rounded-lg px-4 w-20"></div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className="flex justify-end pt-4 border-t border-gray-200">
            <button
              onClick={handleSave}
              className="px-8 py-3 bg-primary-600 text-white rounded-lg hover:bg-primary-700 transition-colors font-medium shadow-md hover:shadow-lg"
            >
              保存设置
            </button>
          </div>
        </div>
      </div>

      {showSuccessMessage && (
        <div className="fixed top-20 right-6 bg-green-500 text-white px-6 py-4 rounded-xl shadow-2xl flex items-center space-x-3 animate-slide-in z-50">
          <span className="text-2xl">✓</span>
          <span className="font-medium">主题设置保存成功！</span>
        </div>
      )}
    </div>
  )
}

export default ThemePreferences

// apps/AgentPit/src/components/settings/ThemePreferences.vue
<script setup lang="ts">
import { ref, reactive, watch, onMounted, provide } from 'vue'
import { useAppStore } from '../../stores/useAppStore'
import { defaultThemeSettings, presetColors } from '../../data/mockSettings'

const appStore = useAppStore()
const settings = reactive({ ...defaultThemeSettings })
const customColor = ref('')
const showCustomPicker = ref(false)
const showSuccessToast = ref(false)

const themeModes = [
  { value: 'light' as const, label: '亮色模式', icon: '☀️', desc: '明亮清爽的界面风格' },
  { value: 'dark' as const, label: '暗色模式', icon: '🌙', desc: '护眼暗色主题，适合夜间使用' },
  { value: 'system' as const, label: '跟随系统', icon: '💻', desc: '自动匹配操作系统主题偏好' },
]

const fontSizes = [
  { value: 'small' as const, label: '小', size: '14px' },
  { value: 'medium' as const, label: '中', size: '16px' },
  { value: 'large' as const, label: '大', size: '18px' },
  { value: 'xlarge' as const, label: '特大', size: '20px' },
]

const densityOptions = [
  { value: 'comfortable' as const, label: '舒适', spacing: '16px' },
  { value: 'compact' as const, label: '紧凑', spacing: '8px' },
  { value: 'minimal' as const, label: '极简', spacing: '4px' },
]

function applyTheme() {
  appStore.setTheme(settings.mode)
  document.documentElement.style.setProperty('--primary-color', settings.primaryColor)

  const fontMap: Record<string, string> = { small: '14px', medium: '16px', large: '18px', xlarge: '20px' }
  document.documentElement.style.setProperty('--base-font-size', fontMap[settings.fontSize] || '16px')

  if (settings.highContrast) {
    document.documentElement.classList.add('high-contrast')
  } else {
    document.documentElement.classList.remove('high-contrast')
  }

  localStorage.setItem('theme-preferences', JSON.stringify(settings))
}

function saveTheme() {
  applyTheme()
  showSuccessToast.value = true
  setTimeout(() => { showSuccessToast.value = false }, 2500)
}

function resetToDefault() {
  Object.assign(settings, defaultThemeSettings)
  customColor.value = ''
  applyTheme()
}

watch(() => settings.mode, () => applyTheme())
watch(() => settings.primaryColor, () => applyTheme())
watch(() => settings.fontSize, () => applyTheme())

onMounted(() => {
  const saved = localStorage.getItem('theme-preferences')
  if (saved) {
    try { Object.assign(settings, JSON.parse(saved)) } catch {}
  }
  provide('themeSettings', settings)
})

provide('updateTheme', saveTheme)
</script>

<template>
  <div class="theme-preferences">
    <h3 class="text-lg font-bold text-gray-900 dark:text-white mb-6">🎨 主题偏好设置</h3>

    <div class="space-y-8">
      <!-- 主题模式选择 -->
      <div>
        <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-3">主题模式</label>
        <div class="grid grid-cols-1 sm:grid-cols-3 gap-3">
          <button
v-for="mode in themeModes" :key="mode.value" :class="[
              'relative p-4 rounded-xl border-2 transition-all duration-200 text-left',
              settings.mode === mode.value
                ? 'border-indigo-500 bg-indigo-50 dark:bg-indigo-900/30 shadow-md'
                : 'border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 hover:border-gray-300 dark:hover:border-gray-600'
            ]"
            @click="settings.mode = mode.value">
            <span class="text-2xl">{{ mode.icon }}</span>
            <p :class="['font-medium mt-2', settings.mode === mode.value ? 'text-indigo-700 dark:text-indigo-300' : 'text-gray-900 dark:text-white']">{{ mode.label }}</p>
            <p class="text-xs text-gray-500 mt-0.5">{{ mode.desc }}</p>
            <div
v-if="settings.mode === mode.value"
              class="absolute top-2 right-2 w-5 h-5 rounded-full bg-indigo-500 flex items-center justify-center">
              <svg class="w-3 h-3 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="3" d="M5 13l4 4L19 7"/></svg>
            </div>
          </button>
        </div>
      </div>

      <!-- 实时预览 -->
      <div>
        <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-3">实时预览</label>
        <div class="bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-xl p-5 space-y-3">
          <div class="flex items-center gap-2">
            <div class="w-10 h-10 rounded-full bg-gradient-to-br from-indigo-400 to-purple-500"></div>
            <div>
              <p class="font-medium text-gray-900 dark:text-white" :style="{ fontSize: fontSizes.find(f => f.value === settings.fontSize)?.size || '16px' }">示例用户名</p>
              <p class="text-xs text-gray-500" :style="{ fontSize: `calc(${fontSizes.find(f => f.value === settings.fontSize)?.size || '16px'} - 3px)` }">user@example.com</p>
            </div>
          </div>
          <button class="px-4 py-2 rounded-lg text-white text-sm font-medium" :style="{ backgroundColor: settings.primaryColor }">
            示例按钮
          </button>
          <div class="flex gap-2">
            <span class="px-2 py-1 text-xs rounded-full bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400">标签一</span>
            <span class="px-2 py-1 text-xs rounded-full bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400">标签二</span>
          </div>
        </div>
      </div>

      <!-- 强调色选择 -->
      <div>
        <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-3">强调色</label>
        <div class="flex flex-wrap gap-3">
          <button
v-for="color in presetColors" :key="color.value" :class="[
              'w-10 h-10 rounded-xl transition-all duration-200 ring-2 ring-offset-2 dark:ring-offset-gray-800',
              settings.primaryColor === color.value ? 'ring-indigo-400 scale-110' : 'ring-transparent hover:scale-105'
            ]"
            :style="{ backgroundColor: color.value }"
            :title="color.name"
            @click="settings.primaryColor = color.value; showCustomPicker = false">
          </button>
          <button
:class="[
              'w-10 h-10 rounded-xl flex items-center justify-center text-lg transition-all duration-200 ring-2 ring-offset-2 dark:ring-offset-gray-800',
              showCustomPicker ? 'ring-indigo-400' : 'ring-transparent'
            ]"
            style="background: conic-gradient(red, yellow, lime, aqua, blue, magenta, red);"
            @click="showCustomPicker = !showCustomPicker; customColor && (settings.primaryColor = customColor)">
            🎨
          </button>
        </div>
        <input
v-if="showCustomPicker" v-model="customColor" type="color"
          class="mt-2 w-12 h-8 rounded cursor-pointer" @input="(e: Event) => settings.primaryColor = (e.target as HTMLInputElement).value" />
      </div>

      <!-- 字体大小 -->
      <div>
        <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-3">字体大小</label>
        <div class="grid grid-cols-4 gap-2">
          <button
v-for="size in fontSizes" :key="size.value" :class="[
              'py-2.5 px-3 rounded-lg border-2 text-sm font-medium transition-all',
              settings.fontSize === size.value
                ? 'border-indigo-500 bg-indigo-50 dark:bg-indigo-900/30 text-indigo-700 dark:text-indigo-300'
                : 'border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 text-gray-700 dark:text-gray-300 hover:border-gray-300'
            ]"
            @click="settings.fontSize = size.value">
            {{ size.label }}
          </button>
        </div>
      </div>

      <!-- 布局密度 -->
      <div>
        <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-3">布局密度</label>
        <div class="grid grid-cols-3 gap-2">
          <button
v-for="opt in densityOptions" :key="opt.value" :class="[
              'py-2.5 px-3 rounded-lg border-2 text-sm font-medium transition-all',
              settings.layoutDensity === opt.value
                ? 'border-indigo-500 bg-indigo-50 dark:bg-indigo-900/30 text-indigo-700 dark:text-indigo-300'
                : 'border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 text-gray-700 dark:text-gray-300 hover:border-gray-300'
            ]"
            @click="settings.layoutDensity = opt.value">
            {{ opt.label }}
          </button>
        </div>
      </div>

      <!-- 开关选项 -->
      <div class="space-y-4">
        <div class="flex items-center justify-between p-4 bg-gray-50 dark:bg-gray-700/50 rounded-xl">
          <div>
            <p class="font-medium text-gray-900 dark:text-white">动画效果</p>
            <p class="text-xs text-gray-500 mt-0.5">启用或禁用全局过渡动画</p>
          </div>
          <button
:class="['relative w-12 h-7 rounded-full transition-colors', settings.reduceMotion ? 'bg-gray-300' : 'bg-indigo-500']"
            @click="settings.reduceMotion = !settings.reduceMotion">
            <span :class="['absolute top-0.5 w-6 h-6 bg-white rounded-full shadow transition-transform', settings.reduceMotion ? 'left-0.5' : 'left-[22px]']"></span>
          </button>
        </div>

        <div class="flex items-center justify-between p-4 bg-gray-50 dark:bg-gray-700/50 rounded-xl">
          <div>
            <p class="font-medium text-gray-900 dark:text-white">高对比度模式</p>
            <p class="text-xs text-gray-500 mt-0.5">提升视觉对比度，辅助无障碍访问</p>
          </div>
          <button
:class="['relative w-12 h-7 rounded-full transition-colors', settings.highContrast ? 'bg-yellow-500' : 'bg-gray-300']"
            @click="settings.highContrast = !settings.highContrast">
            <span :class="['absolute top-0.5 w-6 h-6 bg-white rounded-full shadow transition-transform', settings.highContrast ? 'left-[22px]' : 'left-0.5']"></span>
          </button>
        </div>
      </div>

      <!-- 操作按钮 -->
      <div class="flex justify-end gap-3 pt-4 border-t border-gray-200 dark:border-gray-700">
        <button class="px-5 py-2.5 text-sm text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white border border-gray-300 dark:border-gray-600 rounded-lg transition-colors" @click="resetToDefault">
          重置默认
        </button>
        <button class="px-6 py-2.5 text-sm bg-indigo-500 text-white rounded-lg hover:bg-indigo-600 transition-colors font-medium shadow-md" @click="saveTheme">
          保存主题设置
        </button>
      </div>
    </div>

    <!-- 成功提示 -->
    <Transition name="toast">
      <div v-if="showSuccessToast" class="fixed top-4 right-4 z-50 bg-green-500 text-white px-5 py-3 rounded-xl shadow-lg flex items-center gap-2">
        <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"/></svg>
        <span class="font-medium">主题已保存并应用！</span>
      </div>
    </Transition>
  </div>
</template>

<style scoped>
.toast-enter-active, .toast-leave-active { transition: all 0.3s ease; }
.toast-enter-from { transform: translateX(100%); opacity: 0; }
.toast-leave-to { transform: translateX(100%); opacity: 0; }
</style>
