// apps/Flexloop/src-react-backup-20260410/components/customize/AgentCreatorWizard.tsx
import { useState, useEffect } from 'react'
import BasicInfoForm from './BasicInfoForm'
import AppearanceCustomizer from './AppearanceCustomizer'
import AbilityConfigurator from './AbilityConfigurator'
import BusinessModelSetup from './BusinessModelSetup'
import AgentPreview from './AgentPreview'
import { defaultAgentConfig, type AgentConfig } from '../../data/mockCustomize'

type WizardStep = 1 | 2 | 3 | 4 | 5

const steps = [
  { id: 1, title: '基础信息', icon: '📝', description: '配置名称、角色和目标用户' },
  { id: 2, title: '形象定制', icon: '🎨', description: '设置外观、主题和对话样式' },
  { id: 3, title: '能力配置', icon: '⚡', description: '选择和配置智能体能力' },
  { id: 4, title: '商业模式', icon: '💰', description: '设置盈利模式和定价策略' },
  { id: 5, title: '预览发布', icon: '🚀', description: '预览并发布您的智能体' }
] as const

const AgentCreatorWizard = () => {
  const [currentStep, setCurrentStep] = useState<WizardStep>(1)
  const [agentConfig, setAgentConfig] = useState<AgentConfig>(defaultAgentConfig)
  const [stepValidation, setStepValidation] = useState<Record<number, boolean>>({
    1: false,
    2: true,
    3: true,
    4: true,
    5: true
  })
  const [savedDrafts, setSavedDrafts] = useState<string[]>([])
  const [showSuccessModal, setShowSuccessModal] = useState(false)
  const [autoSaveTimer, setAutoSaveTimer] = useState<NodeJS.Timeout | null>(null)

  useEffect(() => {
    return () => {
      if (autoSaveTimer) clearTimeout(autoSaveTimer)
    }
  }, [autoSaveTimer])

  useEffect(() => {
    if (autoSaveTimer) clearTimeout(autoSaveTimer)
    const timer = setTimeout(() => {
      saveDraft()
    }, 5000)
    setAutoSaveTimer(timer)
  }, [agentConfig])

  const updateBasicInfo = (basicInfo: any) => {
    setAgentConfig(prev => ({ ...prev, basicInfo }))
  }

  const updateAppearance = (appearance: any) => {
    setAgentConfig(prev => ({ ...prev, appearance }))
  }

  const updateAbilities = (abilities: any) => {
    setAgentConfig(prev => ({ ...prev, abilities }))
  }

  const updateBusinessModel = (businessModel: any) => {
    setAgentConfig(prev => ({ ...prev, businessModel }))
  }

  const handleValidationChange = (step: number, isValid: boolean) => {
    setStepValidation(prev => ({ ...prev, [step]: isValid }))
  }

  const handleNext = () => {
    if (currentStep < 5) {
      setCurrentStep((prev) => (prev + 1) as WizardStep)
      window.scrollTo({ top: 0, behavior: 'smooth' })
    }
  }

  const handlePrev = () => {
    if (currentStep > 1) {
      setCurrentStep((prev) => (prev - 1) as WizardStep)
      window.scrollTo({ top: 0, behavior: 'smooth' })
    }
  }

  const handleJumpToStep = (step: number) => {
    setCurrentStep(step as WizardStep)
    window.scrollTo({ top: 0, behavior: 'smooth' })
  }

  const saveDraft = () => {
    const draftKey = `draft_${Date.now()}`
    setSavedDrafts(prev => [...prev.slice(-4), draftKey])
    localStorage.setItem('agent_draft', JSON.stringify(agentConfig))
  }

  const loadDraft = () => {
    const savedDraft = localStorage.getItem('agent_draft')
    if (savedDraft) {
      try {
        const parsed = JSON.parse(savedDraft)
        setAgentConfig(parsed)
      } catch (e) {
        console.error('Failed to parse draft')
      }
    }
  }

  const handlePublish = () => {
    setShowSuccessModal(true)
  }

  const canProceedToNext = () => {
    if (currentStep === 1) return stepValidation[1]
    return true
  }

  const renderStepContent = () => {
    switch (currentStep) {
      case 1:
        return (
          <BasicInfoForm
            data={agentConfig.basicInfo}
            onChange={updateBasicInfo}
            onValidationChange={(isValid) => handleValidationChange(1, isValid)}
          />
        )

      case 2:
        return (
          <AppearanceCustomizer
            data={agentConfig.appearance}
            onChange={updateAppearance}
          />
        )

      case 3:
        return (
          <AbilityConfigurator
            data={agentConfig.abilities}
            roleType={agentConfig.basicInfo.roleType}
            onChange={updateAbilities}
          />
        )

      case 4:
        return (
          <BusinessModelSetup
            data={agentConfig.businessModel}
            onChange={updateBusinessModel}
          />
        )

      case 5:
        return (
          <AgentPreview
            data={agentConfig}
            onEditStep={handleJumpToStep}
            onPublish={handlePublish}
          />
        )

      default:
        return null
    }
  }

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="max-w-7xl mx-auto px-4 py-8">
        {/* 页面标题 */}
        <div className="mb-8 text-center">
          <h1 className="text-4xl font-bold text-gray-900 mb-3">
            🤖 智能体创建向导
          </h1>
          <p className="text-lg text-gray-600">
            跟随引导步骤，轻松打造专属AI智能体
          </p>
        </div>

        {/* 草稿保存提示 */}
        {savedDrafts.length > 0 && (
          <div className="mb-6 bg-blue-50 border border-blue-200 rounded-lg p-3 flex items-center justify-between">
            <div className="flex items-center space-x-2">
              <span>💾</span>
              <span className="text-sm text-blue-800">已自动保存草稿</span>
              <span className="text-xs text-blue-600">({savedDrafts.length}个版本)</span>
            </div>
            <button
              onClick={loadDraft}
              className="text-xs px-3 py-1 bg-blue-100 text-blue-700 rounded hover:bg-blue-200 transition-colors"
            >
              恢复草稿
            </button>
          </div>
        )}

        <div className="flex flex-col lg:flex-row gap-8">
          {/* 左侧：步骤导航 */}
          <div className="lg:w-72 flex-shrink-0">
            <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6 sticky top-6">
              <nav className="space-y-2">
                {steps.map((step) => {
                  const isCompleted = step.id < currentStep
                  const isCurrent = step.id === currentStep
                  const isAccessible = step.id <= currentStep || stepValidation[step.id - 1]

                  return (
                    <button
                      key={step.id}
                      onClick={() => isAccessible && handleJumpToStep(step.id)}
                      disabled={!isAccessible}
                      className={`w-full flex items-center space-x-3 p-3 rounded-lg transition-all duration-200 ${
                        isCurrent
                          ? 'bg-gradient-to-r from-primary-500 to-primary-600 text-white shadow-md'
                          : isCompleted
                          ? 'text-green-700 bg-green-50 hover:bg-green-100 cursor-pointer'
                          : isAccessible
                          ? 'text-gray-700 hover:bg-gray-100 cursor-pointer'
                          : 'text-gray-400 cursor-not-allowed'
                      }`}
                    >
                      <div className={`w-10 h-10 rounded-full flex items-center justify-center text-lg font-bold flex-shrink-0 ${
                        isCurrent ? 'bg-white/20' :
                        isCompleted ? 'bg-green-500 text-white' :
                        'bg-gray-100'
                      }`}>
                        {isCompleted ? '✓' : step.icon}
                      </div>
                      <div className="text-left flex-1 min-w-0">
                        <p className="font-semibold text-sm truncate">{step.title}</p>
                        <p className={`text-xs ${isCurrent ? 'text-white/80' : 'text-gray-500'} truncate`}>
                          {step.description}
                        </p>
                      </div>
                    </button>
                  )
                })}
              </nav>

              {/* 进度条 */}
              <div className="mt-6 pt-6 border-t border-gray-200">
                <div className="mb-2 flex justify-between text-xs text-gray-500">
                  <span>完成进度</span>
                  <span>{currentStep}/5 步</span>
                </div>
                <div className="w-full h-2.5 bg-gray-200 rounded-full overflow-hidden">
                  <div
                    className="h-full bg-gradient-to-r from-primary-500 to-primary-600 transition-all duration-500 ease-out"
                    style={{ width: `${(currentStep / 5) * 100}%` }}
                  ></div>
                </div>

                {/* 完成度检查 */}
                <div className="mt-4 space-y-2">
                  {steps.map((step) => (
                    <div key={step.id} className="flex items-center justify-between text-xs">
                      <span className={step.id <= currentStep ? 'text-green-600 font-medium' : 'text-gray-400'}>
                        {step.id < currentStep ? '✓' : step.id === currentStep ? '●' : '○'} {step.title}
                      </span>
                      {step.id === currentStep && (
                        <span className="px-2 py-0.5 bg-primary-100 text-primary-700 rounded-full font-medium">
                          进行中
                        </span>
                      )}
                      {step.id < currentStep && (
                        <span className="text-green-600">已完成</span>
                      )}
                    </div>
                  ))}
                </div>
              </div>

              {/* 快捷操作 */}
              <div className="mt-6 pt-6 border-t border-gray-200 space-y-2">
                <button
                  onClick={saveDraft}
                  className="w-full px-4 py-2 text-sm border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 transition-colors"
                >
                  💾 手动保存草稿
                </button>
                <button
                  onClick={() => {
                    if (confirm('确定要重置所有配置吗？')) {
                      setAgentConfig(defaultAgentConfig)
                      setCurrentStep(1)
                    }
                  }}
                  className="w-full px-4 py-2 text-sm border border-red-300 text-red-600 rounded-lg hover:bg-red-50 transition-colors"
                >
                  🔄 重置所有配置
                </button>
              </div>
            </div>
          </div>

          {/* 右侧：内容区域 */}
          <div className="flex-1 min-w-0">
            <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6 lg:p-8">
              {/* 步骤标题 */}
              <div className="mb-6 pb-6 border-b border-gray-200">
                <h2 className="text-2xl font-bold text-gray-900 flex items-center">
                  <span className="mr-3">{steps[currentStep - 1].icon}</span>
                  步骤 {currentStep}: {steps[currentStep - 1].title}
                </h2>
                <p className="mt-2 text-gray-600">{steps[currentStep - 1].description}</p>
              </div>

              {/* 步骤内容 */}
              <div className="animate-fadeIn">
                {renderStepContent()}
              </div>

              {/* 导航按钮 */}
              {currentStep < 5 && (
                <div className="mt-8 pt-6 border-t border-gray-200 flex items-center justify-between">
                  <button
                    onClick={handlePrev}
                    disabled={currentStep === 1}
                    className={`px-6 py-2.5 rounded-lg font-medium transition-all duration-200 ${
                      currentStep === 1
                        ? 'text-gray-400 cursor-not-allowed'
                        : 'text-gray-700 hover:bg-gray-100 border border-gray-300'
                    }`}
                  >
                    ← 上一步
                  </button>

                  <div className="flex items-center space-x-2">
                    {steps.map((_, index) => (
                      <div
                        key={index}
                        className={`w-2.5 h-2.5 rounded-full transition-all duration-300 ${
                          index + 1 === currentStep
                            ? 'bg-primary-600 scale-125'
                            : index + 1 < currentStep
                            ? 'bg-green-500'
                            : 'bg-gray-300'
                        }`}
                      ></div>
                    ))}
                  </div>

                  <button
                    onClick={handleNext}
                    disabled={!canProceedToNext()}
                    className="px-6 py-2.5 bg-gradient-to-r from-primary-500 to-primary-600 text-white rounded-lg font-medium hover:from-primary-600 hover:to-primary-700 transition-all duration-200 shadow-md hover:shadow-lg disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    下一步 →
                  </button>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>

      {/* 发布成功模态框 */}
      {showSuccessModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-2xl shadow-2xl max-w-md w-full p-8 text-center animate-fadeIn">
            <div className="w-24 h-24 bg-gradient-to-r from-green-400 to-emerald-500 rounded-full flex items-center justify-center mx-auto mb-6">
              <span className="text-5xl">🎉</span>
            </div>
            <h2 className="text-3xl font-bold text-gray-900 mb-3">发布成功！</h2>
            <p className="text-gray-600 mb-6">
              您的智能体 "<strong>{agentConfig.basicInfo.name}</strong>" 已成功发布，
              现在可以在市场上被其他用户发现和使用。
            </p>
            <div className="bg-gray-50 rounded-lg p-4 mb-6 text-left space-y-2 text-sm">
              <div className="flex justify-between">
                <span className="text-gray-600">智能体ID</span>
                <span className="font-mono font-medium">AGENT-{Date.now().toString(36).toUpperCase()}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-gray-600">状态</span>
                <span className="text-green-600 font-medium">✓ 已上线</span>
              </div>
              <div className="flex justify-between">
                <span className="text-gray-600">访问链接</span>
                <a href="#" className="text-primary-600 hover:underline font-medium">查看 →</a>
              </div>
            </div>
            <div className="flex space-x-3">
              <button
                onClick={() => setShowSuccessModal(false)}
                className="flex-1 px-6 py-2.5 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 transition-colors font-medium"
              >
                继续编辑
              </button>
              <button
                onClick={() => {
                  setShowSuccessModal(false)
                  window.location.href = '/customize/my-agents'
                }}
                className="flex-1 px-6 py-2.5 bg-gradient-to-r from-primary-500 to-primary-600 text-white rounded-lg font-medium hover:from-primary-600 hover:to-primary-700 transition-all"
              >
                查看我的智能体
              </button>
            </div>
          </div>
        </div>
      )}

      <style>{`
        @keyframes fadeIn {
          from { opacity: 0; transform: translateY(10px); }
          to { opacity: 1; transform: translateY(0); }
        }
        .animate-fadeIn {
          animation: fadeIn 0.3s ease-out;
        }
      `}</style>
    </div>
  )
}

export default AgentCreatorWizard

// apps/AgentPit/src/components/customize/AgentCreatorWizard.vue
<script setup lang="ts">
import { ref, reactive, computed, provide, watch } from 'vue'
import BasicInfoForm from './BasicInfoForm.vue'
import AppearanceCustomizer from './AppearanceCustomizer.vue'
import AbilityConfigurator from './AbilityConfigurator.vue'
import BusinessModelSetup from './BusinessModelSetup.vue'
import AgentPreview from './AgentPreview.vue'
import { abilities, agentTemplates, defaultAgentConfig, type AgentConfig } from '../../data/mockCustomize'

interface Props {
  editAgent?: AgentConfig | null
}

const props = defineProps<Props>()
const emit = defineEmits<{
  complete: [config: AgentConfig]
  cancel: []
}>()

const currentStep = ref(1)
const totalSteps = 5
const isSubmitting = ref(false)

const steps = [
  { id: 1, title: '选择模板', icon: '📋', description: '从预设模板开始' },
  { id: 2, title: '基本信息', icon: '📝', description: '名称、描述和头像' },
  { id: 3, title: '外观定制', icon: '🎨', description: '颜色、字体和布局' },
  { id: 4, title: '能力配置', icon: '⚙️', description: '技能和参数设置' },
  { id: 5, title: '商业模式', icon: '💰', description: '定价和服务范围' }
]

const agentConfig = reactive<AgentConfig>(
  props.editAgent ? JSON.parse(JSON.stringify(props.editAgent)) : JSON.parse(JSON.stringify(defaultAgentConfig))
)
const selectedTemplateId = ref<string>('')

provide('agentConfig', agentConfig)

const progressPercent = computed(() => Math.round((currentStep.value / totalSteps) * 100))
const canGoNext = computed(() => {
  switch (currentStep.value) {
    case 1: return selectedTemplateId.value !== ''
    case 2: return agentConfig.basicInfo.name.length >= 2 && agentConfig.basicInfo.category !== ''
    default: return true
  }
})
const isLastStep = computed(() => currentStep.value === totalSteps)
const isFirstStep = computed(() => currentStep.value === 1)

const completedSteps = computed(() => {
  const completed: number[] = []
  if (selectedTemplateId.value) completed.push(1)
  if (agentConfig.basicInfo.name.length >= 2) completed.push(2)
  if (currentStep.value > 3) completed.push(3)
  if (currentStep.value > 4) completed.push(4)
  return completed
})

const applyTemplate = (templateId: string) => {
  selectedTemplateId.value = templateId
  const template = agentTemplates.find(t => t.id === templateId)
  if (template) {
    agentConfig.basicInfo.category = template.category
    template.recommendedAbilities.forEach(abilityId => {
      if (!agentConfig.abilities.enabledAbilities[abilityId]) {
        const ability = abilities.find((a: any) => a.id === abilityId)
        agentConfig.abilities.enabledAbilities[abilityId] = {
          enabled: true,
          proficiency: 75,
          params: ability ? { ...ability.defaultParams } : {}
        }
      }
    })
  }
}

const goNext = () => {
  if (canGoNext.value && currentStep.value < totalSteps) {
    currentStep.value++
  }
}

const goPrev = () => {
  if (currentStep.value > 1) {
    currentStep.value--
  }
}

const handleSubmit = async () => {
  isSubmitting.value = true
  await new Promise(resolve => setTimeout(resolve, 800))
  emit('complete', { ...agentConfig })
  isSubmitting.value = false
}

const handleCancel = () => {
  emit('cancel')
}

watch(currentStep, (_newVal) => {
  window.scrollTo({ top: 0, behavior: 'smooth' })
})

watch(selectedTemplateId, (val) => {
  if (val && currentStep.value === 1) {
    applyTemplate(val)
  }
})
</script>

<template>
  <div class="max-w-6xl mx-auto">
    <div class="mb-8">
      <div class="flex items-center justify-between mb-3">
        <h2 class="text-xl font-bold text-gray-900 dark:text-white">创建智能体</h2>
        <span class="text-sm font-medium px-3 py-1 rounded-full bg-blue-50 dark:bg-blue-900/30 text-blue-600 dark:text-blue-400">
          {{ progressPercent }}% 完成
        </span>
      </div>

      <div class="relative">
        <div class="absolute top-[18px] left-0 right-0 h-0.5 bg-gray-200 dark:bg-gray-700">
          <div
            class="h-full bg-gradient-to-r from-blue-500 to-purple-500 transition-all duration-500 ease-out rounded-full"
            :style="{ width: `${progressPercent}%` }"
          ></div>
        </div>

        <div class="relative flex justify-between">
          <button
            v-for="step in steps"
            :key="step.id"
            type="button"
            class="flex flex-col items-center group focus:outline-none"
            :disabled="currentStep + 1 < step.id"
            :aria-label="`步骤 ${step.id}: ${step.title}`"
            :aria-current="currentStep === step.id ? 'step' : undefined"
            @click="currentStep >= step.id && (currentStep = step.id)"
          >
            <div
              class="w-9 h-9 rounded-full flex items-center justify-center text-sm font-bold transition-all duration-300 border-2 relative z-10"
              :class="{
                'bg-blue-500 border-blue-500 text-white shadow-lg shadow-blue-200 dark:shadow-blue-900/50 scale-110': currentStep === step.id,
                'bg-green-500 border-green-500 text-white': completedSteps.includes(step.id) && currentStep !== step.id,
                'bg-white dark:bg-gray-800 border-gray-300 dark:border-gray-600 text-gray-400 hover:border-gray-400': !completedSteps.includes(step.id) && currentStep !== step.id,
                'cursor-pointer hover:border-blue-300': currentStep >= step.id,
                'cursor-not-allowed opacity-50': currentStep + 1 < step.id
              }"
            >
              <span v-if="completedSteps.includes(step.id) && currentStep !== step.id">✓</span>
              <span v-else>{{ step.icon }}</span>
            </div>
            <span
              class="mt-1.5 text-[11px] font-medium whitespace-nowrap transition-colors hidden sm:block"
              :class="{
                'text-blue-600 dark:text-blue-400': currentStep === step.id,
                'text-green-600 dark:text-green-400': completedSteps.includes(step.id) && currentStep !== step.id,
                'text-gray-400 dark:text-gray-500': !completedSteps.includes(step.id) && currentStep !== step.id
              }"
            >{{ step.title }}</span>
          </button>
        </div>
      </div>
    </div>

    <div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
      <div class="lg:col-span-2">
        <TransitionGroup name="step" tag="div" class="relative min-h-[420px]">
          <div v-if="currentStep === 1" key="step-1" class="w-full">
            <div class="mb-4 p-4 rounded-xl bg-gray-50 dark:bg-gray-800 border border-gray-200 dark:border-gray-700">
              <p class="text-sm text-gray-600 dark:text-gray-400">选择一个基础模板，我们将为您预填充推荐配置，您可以在后续步骤中自由调整。</p>
            </div>
            <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <button
                v-for="template in agentTemplates"
                :key="template.id"
                type="button"
                class="p-5 rounded-xl border-2 text-left transition-all hover:shadow-md group"
                :class="
                  selectedTemplateId === template.id
                    ? 'border-blue-500 bg-blue-50/50 dark:bg-blue-900/20 shadow-md'
                    : 'border-gray-200 dark:border-gray-700 hover:border-blue-300 dark:hover:border-blue-600 bg-white dark:bg-gray-800'
                "
                @click="applyTemplate(template.id)"
              >
                <div class="flex items-start gap-3">
                  <span class="text-3xl">{{ template.icon }}</span>
                  <div class="flex-1 min-w-0">
                    <h4 class="font-semibold text-gray-900 dark:text-white group-hover:text-blue-600 dark:group-hover:text-blue-400 transition-colors">{{ template.name }}</h4>
                    <p class="text-xs text-gray-500 dark:text-gray-400 mt-1 line-clamp-2">{{ template.description }}</p>
                    <div class="flex flex-wrap gap-1 mt-2">
                      <span
                        v-for="(abilityId, idx) in template.recommendedAbilities.slice(0, 3)"
                        :key="idx"
                        class="text-[10px] px-1.5 py-0.5 bg-gray-100 dark:bg-gray-700 text-gray-500 dark:text-gray-400 rounded"
                      >{{ abilityId.split('-')[0] }}</span>
                    </div>
                  </div>
                  <div
                    v-if="selectedTemplateId === template.id"
                    class="w-5 h-5 rounded-full bg-blue-500 flex items-center justify-center shrink-0 mt-0.5"
                  >
                    <svg class="w-3 h-3 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="3" d="M5 13l4 4L19 7" /></svg>
                  </div>
                </div>
              </button>
            </div>
          </div>

          <div v-if="currentStep === 2" key="step-2" class="w-full">
            <BasicInfoForm v-model="agentConfig.basicInfo" />
          </div>

          <div v-if="currentStep === 3" key="step-3" class="w-full">
            <AppearanceCustomizer v-model="agentConfig.appearance" />
          </div>

          <div v-if="currentStep === 4" key="step-4" class="w-full">
            <AbilityConfigurator v-model="agentConfig.abilities" />
          </div>

          <div v-if="currentStep === 5" key="step-5" class="w-full">
            <BusinessModelSetup v-model="agentConfig.businessModel" />
          </div>
        </TransitionGroup>
      </div>

      <div class="lg:col-span-1">
        <div class="sticky top-4 space-y-4">
          <AgentPreview :config="agentConfig" />

          <div class="flex gap-3 pt-2">
            <button
              v-if="!isFirstStep"
              type="button"
              class="flex-1 py-2.5 border border-gray-300 dark:border-gray-600 rounded-xl text-sm font-medium text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-800 transition-colors"
              @click="goPrev"
            >
              上一步
            </button>
            <button
              v-if="!isLastStep"
              type="button"
              :disabled="!canGoNext"
              class="flex-1 py-2.5 bg-blue-500 hover:bg-blue-600 disabled:bg-gray-300 disabled:cursor-not-allowed text-white rounded-xl text-sm font-medium transition-colors shadow-sm"
              @click="goNext"
            >
              下一步
            </button>
            <button
              v-else
              type="button"
              :disabled="isSubmitting"
              class="flex-1 py-2.5 bg-gradient-to-r from-green-500 to-emerald-500 hover:from-green-600 hover:to-emerald-600 disabled:opacity-70 text-white rounded-xl text-sm font-medium transition-all shadow-md"
              @click="handleSubmit"
            >
              <span v-if="isSubmitting" class="inline-flex items-center gap-1.5">
                <svg class="animate-spin w-4 h-4" fill="none" viewBox="0 0 24 24"><circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle><path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"></path></svg>
                创建中...
              </span>
              <span v-else>完成创建 ✓</span>
            </button>
          </div>

          <button
            type="button"
            class="w-full py-2 text-sm text-gray-400 hover:text-red-500 transition-colors"
            @click="handleCancel"
          >
            取消并返回
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.step-enter-active {
  transition: all 0.35s cubic-bezier(0.4, 0, 0.2, 1);
}
.step-leave-active {
  transition: all 0.25s cubic-bezier(0.4, 0, 0.2, 1);
}
.step-enter-from {
  opacity: 0;
  transform: translateX(30px);
}
.step-leave-to {
  opacity: 0;
  transform: translateX(-30px);
}
.line-clamp-2 {
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}
</style>
