// apps/AgentPit/src/components/collaboration/AgentSelector.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import type { Agent } from '../../data/mockCollaboration'
import { presetAgents } from '../../data/mockCollaboration'
import AgentStatusCard from './AgentStatusCard.vue'

const props = withDefaults(defineProps<{
  mode?: 'single' | 'multiple'
  preselected?: string[]
}>(), {
  mode: 'multiple',
  preselected: () => []
})

const emit = defineEmits<{
  (e: 'update:selected', agents: Agent[]): void
  (e: 'configure', agent: Agent): void
}>()

const searchQuery = ref('')
const selectedAgents = ref<Agent[]>([])
const draggedAgent = ref<Agent | null>(null)
const showDetails = ref(true)

const filteredAgents = computed(() => {
  if (!searchQuery.value.trim()) return presetAgents

  const query = searchQuery.value.toLowerCase()
  return presetAgents.filter(agent =>
    agent.name.toLowerCase().includes(query) ||
    agent.role.toLowerCase().includes(query) ||
    agent.specialty.some(s => s.toLowerCase().includes(query)) ||
    agent.skills.some(s => s.toLowerCase().includes(query))
  )
})

const selectedCount = computed(() => selectedAgents.value.length)

const toggleAgentSelection = (agent: Agent) => {
  if (props.mode === 'single') {
    selectedAgents.value = [agent]
    emit('update:selected', selectedAgents.value)
    return
  }

  const index = selectedAgents.value.findIndex(a => a.id === agent.id)
  if (index > -1) {
    selectedAgents.value.splice(index, 1)
  } else {
    selectedAgents.value.push(agent)
  }
  emit('update:selected', [...selectedAgents.value])
}

const isSelected = (agentId: string) => {
  return selectedAgents.value.some(a => a.id === agentId)
}

const selectAllOnline = () => {
  const onlineAgents = presetAgents.filter(a => a.status === 'online' || a.status === 'idle')
  selectedAgents.value = onlineAgents
  emit('update:selected', [...selectedAgents.value])
}

const clearSelection = () => {
  selectedAgents.value = []
  emit('update:selected', [])
}

// Drag and Drop handlers
const onDragStart = (event: DragEvent, agent: Agent) => {
  draggedAgent.value = agent
  if (event.dataTransfer) {
    event.dataTransfer.effectAllowed = 'move'
    event.dataTransfer.setData('text/plain', agent.id)
  }
  const target = event.target as HTMLElement
  target.classList.add('opacity-50')
}

const onDragEnd = (event: DragEvent) => {
  draggedAgent.value = null
  const target = event.target as HTMLElement
  target.classList.remove('opacity-50')
}

const onDragOver = (event: DragEvent) => {
  event.preventDefault()
  if (event.dataTransfer) {
    event.dataTransfer.dropEffect = 'move'
  }
}

const onDrop = (event: DragEvent, targetAgent: Agent) => {
  event.preventDefault()
  if (!draggedAgent.value || draggedAgent.value.id === targetAgent.id) return

  // Reorder agents in selection
  const draggedIndex = selectedAgents.value.findIndex(a => a.id === draggedAgent.value!.id)
  const targetIndex = selectedAgents.value.findIndex(a => a.id === targetAgent.id)

  if (draggedIndex > -1 && targetIndex > -1) {
    const newSelected = [...selectedAgents.value]
    const [removed] = newSelected.splice(draggedIndex, 1)
    newSelected.splice(targetIndex, 0, removed)
    selectedAgents.value = newSelected
    emit('update:selected', [...selectedAgents.value])
  }
}

// Initialize with preselected agents
if (props.preselected.length > 0) {
  selectedAgents.value = presetAgents.filter(a => props.preselected.includes(a.id))
}
</script>

<template>
  <div class="h-full flex flex-col bg-white dark:bg-gray-800 rounded-lg border border-gray-200 dark:border-gray-700">
    <!-- Header -->
    <div class="p-4 border-b border-gray-200 dark:border-gray-700">
      <h2 class="text-lg font-semibold text-gray-900 dark:text-white mb-3">智能体选择器</h2>

      <!-- Search -->
      <div class="relative mb-3">
        <input
          v-model="searchQuery"
          type="text"
          placeholder="搜索智能体..."
          class="w-full px-3 py-2 pl-9 text-sm border border-gray-300 dark:border-gray-600 rounded-lg bg-gray-50 dark:bg-gray-700 text-gray-900 dark:text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-blue-500"
        />
        <svg class="absolute left-3 top-2.5 w-4 h-4 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
        </svg>
      </div>

      <!-- Actions -->
      <div class="flex items-center justify-between gap-2">
        <div class="flex items-center gap-2">
          <button
            @click="selectAllOnline"
            class="px-3 py-1.5 text-xs font-medium text-green-600 dark:text-green-400 bg-green-50 dark:bg-green-900/20 hover:bg-green-100 dark:hover:bg-green-900/30 rounded transition-colors"
          >
            ✓ 全选在线
          </button>
          <button
            @click="clearSelection"
            class="px-3 py-1.5 text-xs font-medium text-red-600 dark:text-red-400 bg-red-50 dark:bg-red-900/20 hover:bg-red-100 dark:hover:bg-red-900/30 rounded transition-colors"
          >
            ✕ 清空
          </button>
        </div>
        <span class="text-xs text-gray-500 dark:text-gray-400">
          已选 {{ selectedCount }}/{{ presetAgents.length }}
        </span>
      </div>
    </div>

    <!-- Agent List -->
    <div class="flex-1 overflow-y-auto p-4 space-y-3">
      <div
        v-for="agent in filteredAgents"
        :key="agent.id"
        :draggable="true"
        @dragstart="(e: DragEvent) => onDragStart(e, agent)"
        @dragend="onDragEnd"
        @dragover="onDragOver"
        @drop="(e: DragEvent) => onDrop(e, agent)"
      >
        <AgentStatusCard
          :agent="agent"
          :is-selected="isSelected(agent.id)"
          :show-details="showDetails"
          @select="toggleAgentSelection"
          @configure="$emit('configure', $event)"
        />
      </div>

      <!-- Empty State -->
      <div v-if="filteredAgents.length === 0" class="text-center py-8 text-gray-500 dark:text-gray-400">
        <svg class="mx-auto w-12 h-12 mb-3 opacity-50" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z"></path>
        </svg>
        <p class="text-sm">未找到匹配的智能体</p>
      </div>
    </div>

    <!-- Footer Info -->
    <div class="p-3 border-t border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-750 rounded-b-lg">
      <div class="flex items-center justify-between text-xs text-gray-500 dark:text-gray-400">
        <span>💡 提示：拖拽卡片可调整优先级</span>
        <label class="flex items-center gap-1 cursor-pointer">
          <input type="checkbox" v-model="showDetails" class="rounded" />
          <span>显示详情</span>
        </label>
      </div>
    </div>
  </div>
</template>

// apps/AgentPit/src/components/collaboration/AgentSelector.tsx
import { useState, useMemo } from 'react'
import type { Agent } from '../../data/mockCollaboration'
import { presetAgents, getRecommendedAgents, taskTypeRecommendations } from '../../data/mockCollaboration'

interface AgentSelectorProps {
  selectedAgents: string[]
  onSelectionChange: (agents: string[]) => void
  taskDescription?: string
}

const statusColors = {
  online: 'bg-green-500',
  busy: 'bg-yellow-500',
  offline: 'bg-gray-400',
  idle: 'bg-blue-500',
  working: 'bg-purple-500',
  waiting: 'bg-orange-500',
  error: 'bg-red-500',
}

const AgentSelector = ({ selectedAgents, onSelectionChange, taskDescription }: AgentSelectorProps) => {
  const [searchTerm, setSearchTerm] = useState('')
  const [filterRole, setFilterRole] = useState<string>('all')

  const recommendedAgentIds = useMemo(() => {
    if (!taskDescription) return []
    return getRecommendedAgents(taskDescription)
  }, [taskDescription])

  const filteredAgents = useMemo(() => {
    let agents = presetAgents

    if (filterRole !== 'all') {
      agents = agents.filter((agent) => agent.role === filterRole)
    }

    if (searchTerm) {
      const term = searchTerm.toLowerCase()
      agents = agents.filter(
        (agent) =>
          agent.name.toLowerCase().includes(term) ||
          agent.specialty.some((s) => s.toLowerCase().includes(term)) ||
          agent.skills.some((s) => s.toLowerCase().includes(term))
      )
    }

    return agents
  }, [searchTerm, filterRole])

  const uniqueRoles = useMemo(() => {
    return [...new Set(presetAgents.map((a) => a.role))]
  }, [])

  const toggleAgent = (agentId: string) => {
    if (selectedAgents.includes(agentId)) {
      onSelectionChange(selectedAgents.filter((id) => id !== agentId))
    } else {
      onSelectionChange([...selectedAgents, agentId])
    }
  }

  const selectAllRecommended = () => {
    onSelectionChange(recommendedAgentIds)
  }

  const clearSelection = () => {
    onSelectionChange([])
  }

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <h3 className="text-lg font-semibold text-gray-900">选择智能体</h3>
        <span className="text-sm text-gray-600">
          已选择 {selectedAgents.length} / {presetAgents.length}
        </span>
      </div>

      {taskDescription && recommendedAgentIds.length > 0 && (
        <div className="p-4 bg-gradient-to-r from-primary-50 to-purple-50 rounded-lg border border-primary-200">
          <div className="flex items-center justify-between mb-2">
            <p className="text-sm font-semibold text-primary-900 flex items-center">
              ✨ 智能推荐
            </p>
            <button
              onClick={selectAllRecommended}
              className="px-3 py-1 text-xs font-medium text-white bg-primary-600 rounded-full hover:bg-primary-700 transition-colors"
            >
              一键选择推荐
            </button>
          </div>
          <p className="text-xs text-primary-700 mb-2">
            根据任务描述，推荐以下智能体协作：
          </p>
          <div className="flex flex-wrap gap-2">
            {recommendedAgentIds.map((agentId) => {
              const agent = presetAgents.find((a) => a.id === agentId)
              if (!agent) return null
              return (
                <span
                  key={agentId}
                  className={`inline-flex items-center px-2.5 py-1 rounded-full text-xs font-medium ${
                    selectedAgents.includes(agentId)
                      ? 'bg-primary-100 text-primary-800 border border-primary-300'
                      : 'bg-white text-gray-700 border border-gray-300'
                  }`}
                >
                  {agent.avatar} {agent.name}
                </span>
              )
            })}
          </div>
        </div>
      )}

      <div className="flex space-x-3">
        <div className="flex-1 relative">
          <input
            type="text"
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            placeholder="搜索智能体名称、技能..."
            className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent text-sm"
          />
          <svg
            className="absolute left-3 top-2.5 w-5 h-5 text-gray-400"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
            />
          </svg>
        </div>
        <select
          value={filterRole}
          onChange={(e) => setFilterRole(e.target.value)}
          className="px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 text-sm bg-white"
        >
          <option value="all">全部角色</option>
          {uniqueRoles.map((role) => (
            <option key={role} value={role}>
              {role}
            </option>
          ))}
        </select>
        {selectedAgents.length > 0 && (
          <button
            onClick={clearSelection}
            className="px-4 py-2 text-red-600 hover:bg-red-50 rounded-lg transition-colors text-sm font-medium border border-red-200"
          >
            清空
          </button>
        )}
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 max-h-96 overflow-y-auto pr-2 custom-scrollbar">
        {filteredAgents.map((agent) => {
          const isSelected = selectedAgents.includes(agent.id)
          const isRecommended = recommendedAgentIds.includes(agent.id)

          return (
            <div
              key={agent.id}
              onClick={() => toggleAgent(agent.id)}
              className={`relative p-4 rounded-xl border-2 cursor-pointer transition-all duration-200 transform hover:scale-[1.02] ${
                isSelected
                  ? 'border-primary-500 bg-primary-50 shadow-md'
                  : 'border-gray-200 bg-white hover:border-gray-300 hover:shadow'
              }`}
            >
              {isRecommended && !isSelected && (
                <div className="absolute -top-2 -right-2 w-6 h-6 bg-yellow-400 rounded-full flex items-center justify-center text-xs text-white font-bold shadow-md z-10">
                  ⭐
                </div>
              )}

              <div className="flex items-start justify-between mb-3">
                <div className="flex items-center space-x-3">
                  <div
                    className={`w-12 h-12 rounded-xl flex items-center justify-center text-2xl ${
                      isSelected ? 'bg-primary-100' : 'bg-gray-100'
                    }`}
                  >
                    {agent.avatar}
                  </div>
                  <div>
                    <h4 className={`font-semibold text-sm ${isSelected ? 'text-primary-900' : 'text-gray-900'}`}>
                      {agent.name}
                    </h4>
                    <p className="text-xs text-gray-500">{agent.role}</p>
                  </div>
                </div>
                <div className="flex items-center space-x-2">
                  <div className={`w-2.5 h-2.5 ${statusColors[agent.status]} rounded-full`}></div>
                  {isSelected && (
                    <div className="w-6 h-6 bg-primary-500 rounded-full flex items-center justify-center">
                      <svg className="w-4 h-4 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" />
                      </svg>
                    </div>
                  )}
                </div>
              </div>

              <div className="mb-3">
                <p className="text-xs text-gray-600 line-clamp-2">{agent.description}</p>
              </div>

              <div className="flex flex-wrap gap-1">
                {agent.specialty.slice(0, 3).map((skill, idx) => (
                  <span
                    key={idx}
                    className={`px-2 py-0.5 rounded text-xs font-medium ${
                      isSelected
                        ? 'bg-primary-100 text-primary-700'
                        : 'bg-gray-100 text-gray-600'
                    }`}
                  >
                    {skill}
                  </span>
                ))}
                {agent.specialty.length > 3 && (
                  <span className="px-2 py-0.5 rounded text-xs text-gray-500">
                    +{agent.specialty.length - 3}
                  </span>
                )}
              </div>

              <div className="mt-3 pt-3 border-t border-gray-100 flex items-center justify-between">
                <div className="flex items-center space-x-1">
                  <span className="text-xs text-gray-500">能力等级:</span>
                  <span className="text-xs font-bold text-primary-600">{agent.level}</span>
                </div>
                <div className="flex items-center space-x-1">
                  <span className="text-xs text-gray-500">准确率:</span>
                  <span className="text-xs font-bold text-green-600">{agent.accuracy}%</span>
                </div>
              </div>
            </div>
          )
        })}
      </div>

      {selectedAgents.length > 0 && (
        <div className="mt-4 p-4 bg-blue-50 rounded-lg border border-blue-200">
          <p className="text-sm font-medium text-blue-900 mb-2">已选择的智能体团队：</p>
          <div className="flex flex-wrap gap-2">
            {selectedAgents.map((agentId) => {
              const agent = presetAgents.find((a) => a.id === agentId)
              if (!agent) return null
              return (
                <span
                  key={agentId}
                  className="inline-flex items-center px-3 py-1.5 bg-white rounded-full text-sm font-medium text-gray-800 shadow-sm border border-blue-200"
                >
                  {agent.avatar} {agent.name}
                  <button
                    onClick={(e) => {
                      e.stopPropagation()
                      toggleAgent(agentId)
                    }}
                    className="ml-2 text-gray-400 hover:text-red-500 transition-colors"
                  >
                    ×
                  </button>
                </span>
              )
            })}
          </div>
        </div>
      )}

      <style>{`
        .custom-scrollbar::-webkit-scrollbar {
          width: 6px;
        }
        .custom-scrollbar::-webkit-scrollbar-track {
          background: #f1f1f1;
          border-radius: 3px;
        }
        .custom-scrollbar::-webkit-scrollbar-thumb {
          background: #c1c1c1;
          border-radius: 3px;
        }
        .custom-scrollbar::-webkit-scrollbar-thumb:hover {
          background: #a1a1a1;
        }
        .line-clamp-2 {
          display: -webkit-box;
          -webkit-line-clamp: 2;
          -webkit-box-orient: vertical;
          overflow: hidden;
        }
      `}</style>
    </div>
  )
}

export default AgentSelector
