// apps/Flexloop/src/views/MemoryPage.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue';
import MainLayout from '@/components/layout/MainLayout.vue';
import FileManager from '@/components/memory/FileManager.vue';
import KnowledgeGraph from '@/components/memory/KnowledgeGraph.vue';
import MemorySearch from '@/components/memory/MemorySearch.vue';
import MemoryTimeline from '@/components/memory/MemoryTimeline.vue';
import BackupSettings from '@/components/memory/BackupSettings.vue';
import StorageQuota from '@/components/memory/StorageQuota.vue';
import {
  mockFileTree,
  mockKnowledgeNodes,
  mockKnowledgeEdges,
  mockMemoryItems,
  mockBackupHistory,
  mockStorageStats
} from '@/data/mockMemory';

type TabType = 'files' | 'graph' | 'search' | 'timeline' | 'backup' | 'quota';

const activeTab = ref<TabType>('files');
const isLoading = ref(true);

const tabs: { id: TabType; label: string; icon: string }[] = [
  { id: 'files', label: '文件管理', icon: '📁' },
  { id: 'graph', label: '知识图谱', icon: '🕸️' },
  { id: 'search', label: '记忆搜索', icon: '🔍' },
  { id: 'timeline', label: '时间线', icon: '📅' },
  { id: 'backup', label: '备份设置', icon: '💾' },
  { id: 'quota', label: '存储配额', icon: '💿' }
];

const stats = computed(() => ({
  totalFiles: countFiles(mockFileTree),
  knowledgeNodes: mockKnowledgeNodes.length,
  searchCount: 128,
  storageUsage: ((mockStorageStats.usedSpace / mockStorageStats.totalSpace) * 100).toFixed(1)
}));

function countFiles(nodes: typeof mockFileTree): number {
  let count = 0;
  nodes.forEach((node) => {
    if (node.type === 'file') count++;
    if (node.children) count += countFiles(node.children);
  });
  return count;
}

onMounted(() => {
  setTimeout(() => {
    isLoading.value = false;
  }, 500);
});
</script>

<template>
  <MainLayout>
    <div
      class="memory-page__wrapper min-h-screen bg-gradient-to-br from-slate-50 via-blue-50 to-purple-50 dark:from-gray-900 dark:via-blue-900/20 dark:to-purple-900/20"
    >
      <!-- 入场动画容器 -->
      <Transition name="page-fade" mode="out-in">
        <div v-if="!isLoading" key="content" class="max-w-7xl mx-auto px-4 py-8 space-y-6">
          <!-- 页面标题栏 -->
          <div
            class="memory-page__header flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4"
          >
            <div>
              <h1
                class="text-3xl md:text-4xl font-bold bg-gradient-to-r from-blue-600 via-purple-600 to-pink-600 bg-clip-text text-transparent"
              >
                🧠 存储记忆系统
              </h1>
              <p class="mt-2 text-gray-600 dark:text-gray-400 text-sm md:text-base">
                智能记忆存储和管理系统，助您高效管理知识资产
              </p>
            </div>

            <div class="flex items-center gap-3">
              <button
                class="px-4 py-2 text-sm font-medium text-white bg-gradient-to-r from-blue-500 to-cyan-500 rounded-lg hover:from-blue-600 hover:to-cyan-600 transition-all shadow-md hover:shadow-lg"
              >
                ⚡ 快速操作
              </button>
            </div>
          </div>

          <!-- 统计概览卡片 -->
          <div class="grid grid-cols-2 lg:grid-cols-4 gap-4">
            <div
              class="memory-page__stat-card group relative overflow-hidden bg-white dark:bg-gray-800 rounded-xl p-5 shadow-lg hover:shadow-xl transition-all duration-300 border border-gray-100 dark:border-gray-700"
            >
              <div
                class="absolute top-0 right-0 w-24 h-24 bg-blue-500/10 rounded-full -translate-y-1/2 translate-x-1/2 group-hover:scale-150 transition-transform duration-500"
              ></div>
              <div class="relative z-10">
                <div class="text-3xl mb-2">📁</div>
                <div class="text-2xl md:text-3xl font-bold text-gray-900 dark:text-white">
                  {{ stats.totalFiles }}
                </div>
                <div class="text-sm text-gray-500 dark:text-gray-400 mt-1">总文件数</div>
              </div>
            </div>

            <div
              class="memory-page__stat-card group relative overflow-hidden bg-white dark:bg-gray-800 rounded-xl p-5 shadow-lg hover:shadow-xl transition-all duration-300 border border-gray-100 dark:border-gray-700"
            >
              <div
                class="absolute top-0 right-0 w-24 h-24 bg-purple-500/10 rounded-full -translate-y-1/2 translate-x-1/2 group-hover:scale-150 transition-transform duration-500"
              ></div>
              <div class="relative z-10">
                <div class="text-3xl mb-2">🕸️</div>
                <div class="text-2xl md:text-3xl font-bold text-gray-900 dark:text-white">
                  {{ stats.knowledgeNodes }}
                </div>
                <div class="text-sm text-gray-500 dark:text-gray-400 mt-1">知识节点</div>
              </div>
            </div>

            <div
              class="memory-page__stat-card group relative overflow-hidden bg-white dark:bg-gray-800 rounded-xl p-5 shadow-lg hover:shadow-xl transition-all duration-300 border border-gray-100 dark:border-gray-700"
            >
              <div
                class="absolute top-0 right-0 w-24 h-24 bg-green-500/10 rounded-full -translate-y-1/2 translate-x-1/2 group-hover:scale-150 transition-transform duration-500"
              ></div>
              <div class="relative z-10">
                <div class="text-3xl mb-2">🔍</div>
                <div class="text-2xl md:text-3xl font-bold text-gray-900 dark:text-white">
                  {{ stats.searchCount }}
                </div>
                <div class="text-sm text-gray-500 dark:text-gray-400 mt-1">搜索次数</div>
              </div>
            </div>

            <div
              class="memory-page__stat-card group relative overflow-hidden bg-white dark:bg-gray-800 rounded-xl p-5 shadow-lg hover:shadow-xl transition-all duration-300 border border-gray-100 dark:border-gray-700"
            >
              <div
                class="absolute top-0 right-0 w-24 h-24 bg-orange-500/10 rounded-full -translate-y-1/2 translate-x-1/2 group-hover:scale-150 transition-transform duration-500"
              ></div>
              <div class="relative z-10">
                <div class="text-3xl mb-2">💿</div>
                <div class="text-2xl md:text-3xl font-bold text-gray-900 dark:text-white">
                  {{ stats.storageUsage }}%
                </div>
                <div class="text-sm text-gray-500 dark:text-gray-400 mt-1">存储使用率</div>
              </div>
            </div>
          </div>

          <!-- Tab 导航 -->
          <div
            class="bg-white dark:bg-gray-800 rounded-xl shadow-lg overflow-hidden border border-gray-200 dark:border-gray-700"
          >
            <!-- Tab 标签栏 -->
            <div
              class="memory-page__tabs flex flex-wrap gap-1 p-2 bg-gray-50 dark:bg-gray-900 border-b border-gray-200 dark:border-gray-700"
            >
              <button
                v-for="tab in tabs"
                :key="tab.id"
                class="flex-1 min-w-[120px] px-4 py-3 text-sm font-medium rounded-lg transition-all duration-200 flex items-center justify-center gap-2"
                :class="
                  activeTab === tab.id
                    ? 'bg-white dark:bg-gray-700 text-blue-600 dark:text-blue-400 shadow-md'
                    : 'text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-800'
                "
                @click="activeTab = tab.id"
              >
                <span>{{ tab.icon }}</span>
                <span class="hidden sm:inline">{{ tab.label }}</span>
              </button>
            </div>

            <!-- Tab 内容区域（KeepAlive 缓存） -->
            <div class="memory-page__content p-4 md:p-6">
              <KeepAlive :max="6">
                <Transition name="tab-fade" mode="out-in">
                  <!-- 文件管理器 -->
                  <FileManager v-if="activeTab === 'files'" key="files" :files="mockFileTree" />

                  <!-- 知识图谱 -->
                  <KnowledgeGraph
                    v-else-if="activeTab === 'graph'"
                    key="graph"
                    :nodes="mockKnowledgeNodes"
                    :edges="mockKnowledgeEdges"
                  />

                  <!-- 记忆搜索 -->
                  <MemorySearch
                    v-else-if="activeTab === 'search'"
                    key="search"
                    :data="mockMemoryItems"
                  />

                  <!-- 时间线 -->
                  <MemoryTimeline
                    v-else-if="activeTab === 'timeline'"
                    key="timeline"
                    :events="
                      mockMemoryItems.map((item) => ({
                        id: item.id,
                        title: item.title,
                        description: item.content.slice(0, 100),
                        timestamp: item.timestamp,
                        type: 'modification' as const,
                        isImportant: Math.random() > 0.7
                      }))
                    "
                  />

                  <!-- 备份设置 -->
                  <BackupSettings
                    v-else-if="activeTab === 'backup'"
                    key="backup"
                    :history="mockBackupHistory"
                    :estimated-size="mockStorageStats.usedSpace * 0.15"
                  />

                  <!-- 存储配额 -->
                  <StorageQuota
                    v-else-if="activeTab === 'quota'"
                    key="quota"
                    :stats="mockStorageStats"
                  />
                </Transition>
              </KeepAlive>
            </div>
          </div>
        </div>

        <!-- 加载状态 -->
        <div v-else key="loading" class="flex items-center justify-center min-h-[600px]">
          <div class="text-center space-y-4">
            <div
              class="w-16 h-16 mx-auto border-4 border-blue-200 dark:border-blue-800 border-t-blue-500 rounded-full animate-spin"
            ></div>
            <p class="text-gray-600 dark:text-gray-400 font-medium">加载中...</p>
          </div>
        </div>
      </Transition>
    </div>
  </MainLayout>
</template>

<style scoped>
.page-fade-enter-active,
.page-fade-leave-active {
  transition: opacity 0.3s ease;
}
.page-fade-enter-from,
.page-fade-leave-to {
  opacity: 0;
}

.tab-fade-enter-active,
.tab-fade-leave-active {
  transition: all 0.25s ease;
}
.tab-fade-enter-from {
  opacity: 0;
  transform: translateY(10px);
}
.tab-fade-leave-to {
  opacity: 0;
  transform: translateY(-10px);
}

@media (max-width: 768px) {
  .memory-page__stat-card {
    padding: 1rem;
  }

  .memory-page__stat-card .text-2xl {
    font-size: 1.5rem;
  }
}
</style>

// apps/Flexloop/src-react-backup-20260410/pages/MemoryPage.tsx
import { useState } from 'react'
import FileManager from '../components/memory/FileManager'
import KnowledgeGraph from '../components/memory/KnowledgeGraph'
import MemorySearch from '../components/memory/MemorySearch'
import MemoryTimeline from '../components/memory/MemoryTimeline'
import BackupSettings from '../components/memory/BackupSettings'
import StorageQuota from '../components/memory/StorageQuota'

type TabType = 'files' | 'knowledge' | 'search' | 'timeline' | 'backup' | 'storage'

const tabs: { id: TabType; label: string; icon: string; description: string }[] = [
  { id: 'files', label: '文件管理', icon: '☁️', description: '云存储文件管理' },
  { id: 'knowledge', label: '知识图谱', icon: '🕸️', description: '知识关系可视化' },
  { id: 'search', label: '记忆检索', icon: '🔍', description: '搜索和筛选记忆' },
  { id: 'timeline', label: '时间线', icon: '📅', description: '按时间浏览记忆' },
  { id: 'backup', label: '备份同步', icon: '💾', description: '数据备份设置' },
  { id: 'storage', label: '存储空间', icon: '💽', description: '存储空间管理' },
]

const MemoryPage = () => {
  const [activeTab, setActiveTab] = useState<TabType>('files')

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold text-gray-900">存储记忆</h1>
        <p className="mt-2 text-gray-600">管理智能体的持久化记忆数据、文件存储和知识图谱</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <div className="bg-gradient-to-br from-blue-500 to-blue-600 rounded-xl shadow-lg p-5 text-white">
          <div className="flex items-center justify-between mb-3">
            <span className="text-blue-100 text-sm font-medium">总存储量</span>
            <span className="text-2xl">💾</span>
          </div>
          <p className="text-3xl font-bold">67.9 GB</p>
          <p className="text-sm text-blue-200 mt-1">已使用 / 100 GB</p>
        </div>

        <div className="bg-gradient-to-br from-purple-500 to-purple-600 rounded-xl shadow-lg p-5 text-white">
          <div className="flex items-center justify-between mb-3">
            <span className="text-purple-100 text-sm font-medium">记忆条目</span>
            <span className="text-2xl">📝</span>
          </div>
          <p className="text-3xl font-bold">15,847</p>
          <p className="text-sm text-purple-200 mt-1">+234 今日新增</p>
        </div>

        <div className="bg-gradient-to-br from-emerald-500 to-emerald-600 rounded-xl shadow-lg p-5 text-white">
          <div className="flex items-center justify-between mb-3">
            <span className="text-emerald-100 text-sm font-medium">知识节点</span>
            <span className="text-2xl">🧠</span>
          </div>
          <p className="text-3xl font-bold">20</p>
          <p className="text-sm text-emerald-200 mt-1">35 条关联关系</p>
        </div>

        <div className="bg-gradient-to-br from-orange-500 to-orange-600 rounded-xl shadow-lg p-5 text-white">
          <div className="flex items-center justify-between mb-3">
            <span className="text-orange-100 text-sm font-medium">备份状态</span>
            <span className="text-2xl">✅</span>
          </div>
          <p className="text-3xl font-bold">正常</p>
          <p className="text-sm text-orange-200 mt-1">上次：今天 02:00</p>
        </div>
      </div>

      <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
        <div className="border-b border-gray-200 px-4 py-3 bg-gradient-to-r from-gray-50 to-white">
          <div className="flex gap-1 overflow-x-auto pb-0.5">
            {tabs.map((tab) => (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id)}
                className={`flex items-center gap-2 px-4 py-2.5 rounded-lg font-medium transition-all whitespace-nowrap ${
                  activeTab === tab.id
                    ? 'bg-primary-600 text-white shadow-md'
                    : 'text-gray-700 hover:bg-gray-100 hover:text-primary-600'
                }`}
              >
                <span>{tab.icon}</span>
                <span>{tab.label}</span>
              </button>
            ))}
          </div>
        </div>

        <div className="min-h-[600px]">
          {activeTab === 'files' && <FileManager />}
          {activeTab === 'knowledge' && <KnowledgeGraph />}
          {activeTab === 'search' && <MemorySearch />}
          {activeTab === 'timeline' && <MemoryTimeline />}
          {activeTab === 'backup' && <BackupSettings />}
          {activeTab === 'storage' && <StorageQuota />}
        </div>
      </div>

      <div className="bg-gradient-to-r from-primary-50 via-purple-50 to-pink-50 rounded-xl p-6 border border-primary-200">
        <h3 className="font-semibold text-gray-900 mb-3 flex items-center gap-2">
          <span>💡</span>
          使用提示
        </h3>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-sm text-gray-700">
          <div className="flex items-start gap-2">
            <span className="text-primary-500 mt-0.5">•</span>
            <span><strong>文件管理：</strong>支持拖拽上传、批量操作、文件夹导航和文件分享功能</span>
          </div>
          <div className="flex items-start gap-2">
            <span className="text-purple-500 mt-0.5">•</span>
            <span><strong>知识图谱：</strong>可视化展示知识节点间的关联关系，支持缩放、搜索和类型筛选</span>
          </div>
          <div className="flex items-start gap-2">
            <span className="text-pink-500 mt-0.5">•</span>
            <span><strong>记忆检索：</strong>强大的全文搜索引擎，支持模糊匹配、高级筛选和结果排序</span>
          </div>
          <div className="flex items-start gap-2">
            <span className="text-green-500 mt-0.5">•</span>
            <span><strong>时间线视图：</strong>按日/周/月/年维度展示记忆条目，便于回顾和整理</span>
          </div>
          <div className="flex items-start gap-2">
            <span className="text-orange-500 mt-0.5">•</span>
            <span><strong>数据备份：</strong>自动备份计划配置，多设备同步，版本历史回滚</span>
          </div>
          <div className="flex items-start gap-2">
            <span className="text-red-500 mt-0.5">•</span>
            <span><strong>存储优化：</strong>智能扫描重复文件和缓存垃圾，一键释放存储空间</span>
          </div>
        </div>
      </div>
    </div>
  )
}

export default MemoryPage
