// apps/AgentPit/src/components/memory/FileManager.vue
<script setup lang="ts">
import { ref, reactive, computed } from 'vue'
import type { FileNode, ContextMenuAction } from '@/types/memory'

interface Props {
  files?: FileNode[]
}

const props = withDefaults(defineProps<Props>(), {
  files: () => []
})

const emit = defineEmits<{
  fileSelect: [file: FileNode]
  fileUpload: [files: FileList]
  fileDelete: [file: FileNode]
  fileRename: [file: FileNode, newName: string]
  folderCreate: [parentPath: string, name: string]
}>()

const currentPath = ref<string[]>(['根目录'])
const selectedFile = ref<FileNode | null>(null)
const isDragging = ref(false)
const showContextMenu = ref(false)
const contextMenuPosition = reactive({ x: 0, y: 0 })
const contextMenuTarget = ref<FileNode | null>(null)
const isRenaming = ref(false)
const renameValue = ref('')
const isNewFolder = ref(false)
const newFolderName = ref('')

const currentFiles = computed(() => {
  let nodes = props.files
  for (let i = 1; i < currentPath.value.length; i++) {
    const folder = nodes.find(f => f.name === currentPath.value[i] && f.type === 'folder')
    if (folder?.children) {
      nodes = folder.children
    }
  }
  return nodes
})

const getFileIcon = (file: FileNode): string => {
  if (file.type === 'folder') return '📁'
  const ext = file.name.split('.').pop()?.toLowerCase()
  const iconMap: Record<string, string> = {
    pdf: '📄',
    doc: '📝',
    docx: '📝',
    txt: '📃',
    jpg: '🖼️',
    jpeg: '🖼️',
    png: '🖼️',
    gif: '🖼️',
    svg: '🎨',
    mp4: '🎬',
    avi: '🎬',
    mov: '🎬',
    js: '💻',
    ts: '💻',
    vue: '💚',
    py: '🐍',
    json: '📋',
    md: '📖'
  }
  return iconMap[ext || ''] || '📎'
}

const formatFileSize = (bytes: number): string => {
  if (bytes < 1024) return bytes + ' B'
  if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(1) + ' KB'
  return (bytes / (1024 * 1024)).toFixed(1) + ' MB'
}

const navigateToFolder = (folder: FileNode) => {
  if (folder.type === 'folder') {
    currentPath.value.push(folder.name)
    selectedFile.value = null
  } else {
    selectedFile.value = folder
    emit('fileSelect', folder)
  }
}

const navigateBreadcrumb = (index: number) => {
  currentPath.value = currentPath.value.slice(0, index + 1)
  selectedFile.value = null
}

const handleDragOver = (e: DragEvent) => {
  e.preventDefault()
  isDragging.value = true
}

const handleDragLeave = () => {
  isDragging.value = false
}

const handleDrop = (e: DragEvent) => {
  e.preventDefault()
  isDragging.value = false
  if (e.dataTransfer?.files) {
    emit('fileUpload', e.dataTransfer.files)
  }
}

const handleContextMenu = (e: MouseEvent, file: FileNode) => {
  e.preventDefault()
  contextMenuTarget.value = file
  contextMenuPosition.x = e.clientX
  contextMenuPosition.y = e.clientY
  showContextMenu.value = true
}

const closeContextMenu = () => {
  showContextMenu.value = false
  contextMenuTarget.value = null
}

const handleContextAction = (action: ContextMenuAction) => {
  if (!contextMenuTarget.value) return

  switch (action) {
    case 'rename':
      renameValue.value = contextMenuTarget.value.name
      isRenaming.value = true
      break
    case 'delete':
      emit('fileDelete', contextMenuTarget.value)
      break
    case 'download':
      console.log('下载文件:', contextMenuTarget.value.name)
      break
    case 'copy':
      console.log('复制文件:', contextMenuTarget.value.name)
      break
    case 'move':
      console.log('移动文件:', contextMenuTarget.value.name)
      break
    case 'properties':
      console.log('查看属性:', contextMenuTarget.value.name)
      break
  }
  closeContextMenu()
}

const confirmRename = () => {
  if (contextMenuTarget.value && renameValue.value.trim()) {
    emit('fileRename', contextMenuTarget.value, renameValue.value.trim())
  }
  isRenaming.value = false
  renameValue.value = ''
}

const createNewFolder = () => {
  newFolderName.value = ''
  isNewFolder.value = true
}

const confirmNewFolder = () => {
  if (newFolderName.value.trim()) {
    emit('folderCreate', currentPath.value.join('/'), newFolderName.value.trim())
  }
  isNewFolder.value = false
  newFolderName.value = ''
}
</script>

<template>
  <div class="file-manager__container bg-white dark:bg-gray-800 rounded-xl shadow-lg overflow-hidden">
    <!-- 工具栏 -->
    <div class="file-manager__toolbar flex items-center justify-between p-4 border-b border-gray-200 dark:border-gray-700">
      <div class="flex items-center gap-2">
        <button
          @click="createNewFolder"
          class="px-3 py-2 text-sm font-medium text-white bg-blue-500 hover:bg-blue-600 rounded-lg transition-colors"
        >
          📁 新建文件夹
        </button>
        <label class="px-3 py-2 text-sm font-medium text-white bg-green-500 hover:bg-green-600 rounded-lg transition-colors cursor-pointer">
          📤 上传文件
          <input type="file" multiple class="hidden" @change="(e: Event) => {
            const target = e.target as HTMLInputElement
            if (target.files) emit('fileUpload', target.files)
          }" />
        </label>
      </div>
      <div class="text-sm text-gray-500 dark:text-gray-400">
        共 {{ currentFiles.length }} 项
      </div>
    </div>

    <!-- 面包屑导航 -->
    <div class="file-manager__breadcrumb flex items-center gap-2 px-4 py-3 bg-gray-50 dark:bg-gray-900 border-b border-gray-200 dark:border-gray-700">
      <template v-for="(item, index) in currentPath" :key="index">
        <button
          @click="navigateBreadcrumb(index)"
          class="text-sm font-medium text-blue-600 dark:text-blue-400 hover:text-blue-700 dark:hover:text-blue-300 transition-colors"
        >
          {{ item }}
        </button>
        <span v-if="index < currentPath.length - 1" class="text-gray-400">/</span>
      </template>
    </div>

    <!-- 拖拽区域 -->
    <div
      class="file-manager__dropzone relative min-h-[400px] p-4"
      @dragover="handleDragOver"
      @dragleave="handleDragLeave"
      @drop="handleDrop"
      @click.self="selectedFile = null"
    >
      <!-- 拖拽提示 -->
      <Transition name="fade">
        <div
          v-if="isDragging"
          class="absolute inset-0 z-10 flex items-center justify-center bg-blue-50 dark:bg-blue-900/20 border-2 border-dashed border-blue-400 rounded-lg m-4"
        >
          <div class="text-center">
            <p class="text-2xl mb-2">📥</p>
            <p class="text-lg font-medium text-blue-600 dark:text-blue-400">释放以上传文件</p>
          </div>
        </div>
      </Transition>

      <!-- 文件列表 -->
      <div class="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-4">
        <TransitionGroup name="list">
          <!-- 新建文件夹输入框 -->
          <div v-if="isNewFolder" key="new-folder" class="file-manager__item flex flex-col items-center p-3 rounded-lg bg-yellow-50 dark:bg-yellow-900/20 border-2 border-yellow-400">
            <div class="text-4xl mb-2">📁</div>
            <input
              v-model="newFolderName"
              @keyup.enter="confirmNewFolder"
              @blur="confirmNewFolder"
              autofocus
              class="w-full text-xs text-center px-2 py-1 border border-gray-300 dark:border-gray-600 rounded bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-blue-500"
              placeholder="文件夹名称"
            />
          </div>

          <!-- 文件/文件夹项 -->
          <div
            v-for="file in currentFiles"
            :key="file.id"
            class="file-manager__item group relative flex flex-col items-center p-3 rounded-lg cursor-pointer transition-all duration-200 hover:bg-gray-100 dark:hover:bg-gray-700"
            :class="{ 'ring-2 ring-blue-500 bg-blue-50 dark:bg-blue-900/20': selectedFile?.id === file.id }"
            @click="navigateToFolder(file)"
            @contextmenu="handleContextMenu($event, file)"
            @dblclick="navigateToFolder(file)"
          >
            <div class="text-4xl mb-2">{{ getFileIcon(file) }}</div>
            <p class="text-xs text-center text-gray-700 dark:text-gray-300 truncate w-full px-1" :title="file.name">
              {{ file.name }}
            </p>
            <p class="text-xs text-gray-400 dark:text-gray-500 mt-1">
              {{ file.type === 'folder' ? '' : formatFileSize(file.size || 0) }}
            </p>
          </div>
        </TransitionGroup>
      </div>

      <!-- 空状态 -->
      <div v-if="currentFiles.length === 0 && !isDragging && !isNewFolder" class="flex flex-col items-center justify-center h-64 text-gray-400">
        <p class="text-5xl mb-4">📂</p>
        <p class="text-lg font-medium">此文件夹为空</p>
        <p class="text-sm mt-2">拖拽文件到此处或点击上方按钮上传</p>
      </div>
    </div>

    <!-- 右键菜单 -->
    <Teleport to="body">
      <Transition name="fade">
        <div
          v-if="showContextMenu"
          class="fixed z-50 min-w-[160px] bg-white dark:bg-gray-800 rounded-lg shadow-xl border border-gray-200 dark:border-gray-700 py-1"
          :style="{ left: contextMenuPosition.x + 'px', top: contextMenuPosition.y + 'px' }"
          @click.stop
        >
          <button
            v-for="action in ['rename', 'copy', 'move', 'download', 'delete', 'properties'] as ContextMenuAction[]"
            :key="action"
            @click="handleContextAction(action)"
            class="w-full px-4 py-2 text-left text-sm text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors flex items-center gap-2"
          >
            <span>{{ { rename: '✏️', copy: '📋', move: '📦', download: '⬇️', delete: '🗑️', properties: 'ℹ️' }[action] }}</span>
            {{ { rename: '重命名', copy: '复制', move: '移动', download: '下载', delete: '删除', properties: '属性' }[action] }}
          </button>
        </div>
      </Transition>
    </Teleport>

    <!-- 重命名对话框 -->
    <Teleport to="body">
      <Transition name="fade">
        <div v-if="isRenaming" class="fixed inset-0 z-50 flex items-center justify-center bg-black/50" @click="isRenaming = false">
          <div class="bg-white dark:bg-gray-800 rounded-xl p-6 shadow-2xl w-96" @click.stop>
            <h3 class="text-lg font-semibold text-gray-900 dark:text-white mb-4">重命名</h3>
            <input
              v-model="renameValue"
              @keyup.enter="confirmRename"
              autofocus
              class="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-blue-500"
            />
            <div class="flex justify-end gap-3 mt-6">
              <button @click="isRenaming = false" class="px-4 py-2 text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-lg transition-colors">
                取消
              </button>
              <button @click="confirmRename" class="px-4 py-2 bg-blue-500 text-white hover:bg-blue-600 rounded-lg transition-colors">
                确认
              </button>
            </div>
          </div>
        </div>
      </Transition>
    </Teleport>
  </div>
</template>

<style scoped>
.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.2s ease;
}
.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}

.list-enter-active,
.list-leave-active {
  transition: all 0.3s ease;
}
.list-enter-from {
  opacity: 0;
  transform: translateY(-10px);
}
.list-leave-to {
  opacity: 0;
  transform: translateX(20px);
}
.list-move {
  transition: transform 0.3s ease;
}
</style>

// apps/Flexloop/src-react-backup-20260410/components/memory/FileManager.tsx
import { useState, useRef, useCallback } from 'react'
import { fileSystemData, FileItem } from '../../data/mockMemory'

type ViewMode = 'list' | 'grid' | 'large'

const getFileIcon = (file: FileItem) => {
  if (file.type === 'folder') return '📁'

  const iconMap = {
    document: '📄',
    image: '🖼️',
    video: '🎬',
    audio: '🎵',
    code: '💻',
    archive: '📦',
    other: '📎'
  }

  return iconMap[file.fileType || 'other'] || '📎'
}

const formatFileSize = (bytes: number): string => {
  if (bytes === 0) return '0 B'
  const k = 1024
  const sizes = ['B', 'KB', 'MB', 'GB']
  const i = Math.floor(Math.log(bytes) / Math.log(k))
  return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i]
}

const FileManager = () => {
  const [currentPath, setCurrentPath] = useState<string>('/')
  const [viewMode, setViewMode] = useState<ViewMode>('list')
  const [selectedItems, setSelectedItems] = useState<Set<string>>(new Set())
  const [contextMenu, setContextMenu] = useState<{ x: number; y: number; fileId: string } | null>(null)
  const [isDragging, setIsDragging] = useState(false)
  const [showNewFolderModal, setShowNewFolderModal] = useState(false)
  const [showShareModal, setShowShareModal] = useState(false)
  const [newFolderName, setNewFolderName] = useState('')
  const fileInputRef = useRef<HTMLInputElement>(null)

  const getCurrentFiles = (): FileItem[] => {
    const currentFolder = fileSystemData.find(f => f.path === currentPath && f.type === 'folder')
    if (!currentFolder) {
      return fileSystemData.filter(f => f.parentId === null && f.type !== 'folder')
    }
    return fileSystemData.filter(f => f.parentId === currentFolder.id)
  }

  const navigateToFolder = (folderPath: string) => {
    setCurrentPath(folderPath)
    setSelectedItems(new Set())
    setContextMenu(null)
  }

  const goToParent = () => {
    if (currentPath === '/') return
    const parts = currentPath.split('/').filter(Boolean)
    parts.pop()
    navigateToFolder(parts.length > 0 ? '/' + parts.join('/') : '/')
  }

  const toggleSelection = (fileId: string, e: React.MouseEvent) => {
    e.stopPropagation()
    const newSelected = new Set(selectedItems)
    if (newSelected.has(fileId)) {
      newSelected.delete(fileId)
    } else {
      newSelected.add(fileId)
    }
    setSelectedItems(newSelected)
  }

  const handleSelectAll = () => {
    const currentFiles = getCurrentFiles()
    if (selectedItems.size === currentFiles.length) {
      setSelectedItems(new Set())
    } else {
      setSelectedItems(new Set(currentFiles.map(f => f.id)))
    }
  }

  const handleContextMenu = (e: React.MouseEvent, fileId: string) => {
    e.preventDefault()
    setContextMenu({ x: e.clientX, y: e.clientY, fileId })
  }

  const closeContextMenu = () => setContextMenu(null)

  const handleDrop = useCallback((e: React.DragEvent) => {
    e.preventDefault()
    setIsDragging(false)
  }, [])

  const handleDragOver = useCallback((e: React.DragEvent) => {
    e.preventDefault()
    setIsDragging(true)
  }, [])

  const handleDragLeave = useCallback(() => {
    setIsDragging(false)
  }, [])

  const getBreadcrumbs = () => {
    if (currentPath === '/') return [{ name: '我的云盘', path: '/' }]
    const parts = currentPath.split('/').filter(Boolean)
    const breadcrumbs = [{ name: '我的云盘', path: '/' }]
    let currentPathBuild = ''
    for (const part of parts) {
      currentPathBuild += '/' + part
      breadcrumbs.push({ name: part, path: currentPathBuild })
    }
    return breadcrumbs
  }

  const totalSize = fileSystemData.filter(f => f.type === 'file').reduce((sum, f) => sum + f.size, 0)
  const usedPercentage = Math.min((totalSize / (100 * 1024 * 1024 * 1024)) * 100, 100)

  return (
    <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden" onClick={closeContextMenu}>
      <div className="border-b border-gray-200 px-6 py-4">
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-xl font-semibold text-gray-900 flex items-center gap-2">
            <span>☁️</span>
            云存储文件管理
          </h2>

          <div className="flex items-center gap-2">
            <div className="flex bg-gray-100 rounded-lg p-1">
              {(['list', 'grid', 'large'] as ViewMode[]).map((mode) => (
                <button
                  key={mode}
                  onClick={() => setViewMode(mode)}
                  className={`px-3 py-1.5 rounded-md text-sm font-medium transition-all ${
                    viewMode === mode
                      ? 'bg-white text-primary-600 shadow-sm'
                      : 'text-gray-600 hover:text-gray-900'
                  }`}
                >
                  {mode === 'list' ? '☰' : mode === 'grid' ? '▦' : '⊞'}
                </button>
              ))}
            </div>
          </div>
        </div>

        <div className="flex items-center gap-3 mb-4">
          <div className="flex items-center gap-2 flex-1 bg-gray-50 rounded-lg px-4 py-2">
            <button onClick={goToParent} disabled={currentPath === '/'} className="text-gray-500 hover:text-gray-700 disabled:opacity-30">
              ←
            </button>
            <div className="flex items-center gap-1 text-sm flex-1 overflow-x-auto">
              {getBreadcrumbs().map((crumb, idx) => (
                <span key={idx} className="flex items-center gap-1">
                  {idx > 0 && <span className="text-gray-400">/</span>}
                  <button
                    onClick={() => navigateToFolder(crumb.path)}
                    className={`hover:text-primary-600 transition-colors ${
                      idx === getBreadcrumbs().length - 1 ? 'font-medium text-gray-900' : 'text-gray-600'
                    }`}
                  >
                    {crumb.name}
                  </button>
                </span>
              ))}
            </div>
          </div>
        </div>

        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-2">
            <button
              onClick={() => setShowNewFolderModal(true)}
              className="px-4 py-2 bg-primary-600 text-white rounded-lg text-sm font-medium hover:bg-primary-700 transition-colors flex items-center gap-2"
            >
              <span>📁</span> 新建文件夹
            </button>
            <button
              onClick={() => fileInputRef.current?.click()}
              className="px-4 py-2 bg-green-600 text-white rounded-lg text-sm font-medium hover:bg-green-700 transition-colors flex items-center gap-2"
            >
              <span>⬆️</span> 上传文件
            </button>
            <input ref={fileInputRef} type="file" multiple className="hidden" />
            {selectedItems.size > 0 && (
              <>
                <button className="px-4 py-2 bg-blue-600 text-white rounded-lg text-sm font-medium hover:bg-blue-700 transition-colors flex items-center gap-2">
                  <span>⬇️</span> 下载 ({selectedItems.size})
                </button>
                <button className="px-4 py-2 bg-purple-600 text-white rounded-lg text-sm font-medium hover:bg-purple-700 transition-colors flex items-center gap-2">
                  <span>📋</span> 复制
                </button>
                <button
                  onClick={() => setShowShareModal(true)}
                  className="px-4 py-2 bg-orange-600 text-white rounded-lg text-sm font-medium hover:bg-orange-700 transition-colors flex items-center gap-2"
                >
                  <span>🔗</span> 分享
                </button>
                <button className="px-4 py-2 bg-red-600 text-white rounded-lg text-sm font-medium hover:bg-red-700 transition-colors flex items-center gap-2">
                  <span>🗑️</span> 删除
                </button>
              </>
            )}
          </div>

          <div className="flex items-center gap-3">
            <div className="text-sm text-gray-600">
              已用: <span className="font-semibold text-gray-900">{formatFileSize(totalSize)}</span> / 100 GB
            </div>
            <div className="w-32 h-2 bg-gray-200 rounded-full overflow-hidden">
              <div
                className="h-full bg-gradient-to-r from-blue-500 to-purple-600 rounded-full transition-all"
                style={{ width: `${usedPercentage}%` }}
              />
            </div>
          </div>
        </div>
      </div>

      <div
        onDrop={handleDrop}
        onDragOver={handleDragOver}
        onDragLeave={handleDragLeave}
        className={`relative min-h-[400px] ${isDragging ? 'bg-blue-50 border-2 border-dashed border-blue-400' : ''}`}
      >
        {isDragging && (
          <div className="absolute inset-0 flex items-center justify-center z-10 bg-blue-50/90">
            <div className="text-center">
              <p className="text-2xl mb-2">📥</p>
              <p className="text-lg font-medium text-blue-600">拖拽文件到此处上传</p>
            </div>
          </div>
        )}

        {viewMode === 'list' && (
          <div>
            <div className="grid grid-cols-12 gap-4 px-6 py-3 bg-gray-50 border-b border-gray-200 text-xs font-medium text-gray-600 uppercase tracking-wider">
              <div className="col-span-1">
                <input type="checkbox" onChange={handleSelectAll} checked={selectedItems.size === getCurrentFiles().length && getCurrentFiles().length > 0} />
              </div>
              <div className="col-span-5">名称</div>
              <div className="col-span-2">大小</div>
              <div className="col-span-2">修改时间</div>
              <div className="col-span-2">类型</div>
            </div>
            {getCurrentFiles().map((file) => (
              <div
                key={file.id}
                onContextMenu={(e) => handleContextMenu(e, file.id)}
                onClick={(e) => toggleSelection(file.id, e)}
                onDoubleClick={() => file.type === 'folder' && navigateToFolder(file.path)}
                className={`grid grid-cols-12 gap-4 px-6 py-3 border-b border-gray-100 cursor-pointer transition-colors ${
                  selectedItems.has(file.id) ? 'bg-primary-50' : 'hover:bg-gray-50'
                }`}
              >
                <div className="col-span-1 flex items-center">
                  <input type="checkbox" checked={selectedItems.has(file.id)} readOnly />
                </div>
                <div className="col-span-5 flex items-center gap-3">
                  <span className="text-xl">{getFileIcon(file)}</span>
                  <span className="font-medium text-gray-900 truncate">{file.name}</span>
                </div>
                <div className="col-span-2 flex items-center text-sm text-gray-600">{formatFileSize(file.size)}</div>
                <div className="col-span-2 flex items-center text-sm text-gray-600">{file.modifiedTime.split(' ')[0]}</div>
                <div className="col-span-2 flex items-center">
                  <span className={`px-2 py-1 rounded-full text-xs font-medium ${
                    file.type === 'folder' ? 'bg-yellow-100 text-yellow-800' :
                    file.fileType === 'document' ? 'bg-blue-100 text-blue-800' :
                    file.fileType === 'image' ? 'bg-green-100 text-green-800' :
                    file.fileType === 'video' ? 'bg-red-100 text-red-800' :
                    file.fileType === 'audio' ? 'bg-purple-100 text-purple-800' :
                    file.fileType === 'code' ? 'bg-indigo-100 text-indigo-800' :
                    file.fileType === 'archive' ? 'bg-orange-100 text-orange-800' :
                    'bg-gray-100 text-gray-800'
                  }`}>
                    {file.type === 'folder' ? '文件夹' :
                     file.fileType === 'document' ? '文档' :
                     file.fileType === 'image' ? '图片' :
                     file.fileType === 'video' ? '视频' :
                     file.fileType === 'audio' ? '音频' :
                     file.fileType === 'code' ? '代码' :
                     file.fileType === 'archive' ? '压缩包' : '其他'}
                  </span>
                </div>
              </div>
            ))}
          </div>
        )}

        {(viewMode === 'grid' || viewMode === 'large') && (
          <div className={`grid gap-4 p-6 ${viewMode === 'grid' ? 'grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-6' : 'grid-cols-2 md:grid-cols-3 lg:grid-cols-4'}`}>
            {getCurrentFiles().map((file) => (
              <div
                key={file.id}
                onContextMenu={(e) => handleContextMenu(e, file.id)}
                onClick={(e) => toggleSelection(file.id, e)}
                onDoubleClick={() => file.type === 'folder' && navigateToFolder(file.path)}
                className={`relative group rounded-lg border-2 p-4 cursor-pointer transition-all ${
                  selectedItems.has(file.id)
                    ? 'border-primary-500 bg-primary-50 shadow-md'
                    : 'border-gray-200 hover:border-primary-300 hover:shadow-md'
                } ${viewMode === 'large' ? 'aspect-square flex flex-col items-center justify-center' : ''}`}
              >
                <div className={`absolute top-2 left-2 opacity-0 group-hover:opacity-100 transition-opacity`}>
                  <input type="checkbox" checked={selectedItems.has(file.id)} readOnly />
                </div>
                <div className={`${viewMode === 'large' ? 'text-6xl mb-3' : 'text-4xl mb-2'} text-center`}>
                  {getFileIcon(file)}
                </div>
                <div className={`text-center ${viewMode === 'large' ? '' : 'truncate'}`}>
                  <p className={`font-medium text-gray-900 ${viewMode === 'large' ? 'text-base' : 'text-sm'} break-words`}>
                    {file.name}
                  </p>
                  {viewMode === 'large' && (
                    <>
                      <p className="text-xs text-gray-500 mt-1">{formatFileSize(file.size)}</p>
                      <p className="text-xs text-gray-400 mt-0.5">{file.modifiedTime.split(' ')[0]}</p>
                    </>
                  )}
                </div>
              </div>
            ))}
          </div>
        )}

        {contextMenu && (
          <div
            className="fixed bg-white rounded-lg shadow-xl border border-gray-200 py-2 z-50 min-w-[180px]"
            style={{ left: contextMenu.x, top: contextMenu.y }}
          >
            <button className="w-full px-4 py-2 text-left text-sm text-gray-700 hover:bg-gray-100 flex items-center gap-2">
              ✏️ 重命名
            </button>
            <button className="w-full px-4 py-2 text-left text-sm text-gray-700 hover:bg-gray-100 flex items-center gap-2">
              📋 属性
            </button>
            <button className="w-full px-4 py-2 text-left text-sm text-gray-700 hover:bg-gray-100 flex items-center gap-2">
              📂 移动到
            </button>
            <button className="w-full px-4 py-2 text-left text-sm text-gray-700 hover:bg-gray-100 flex items-center gap-2">
              📄 复制到
            </button>
            <hr className="my-1" />
            <button className="w-full px-4 py-2 text-left text-sm text-red-600 hover:bg-red-50 flex items-center gap-2">
              🗑️ 删除
            </button>
          </div>
        )}
      </div>

      {showNewFolderModal && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50" onClick={() => setShowNewFolderModal(false)}>
          <div className="bg-white rounded-xl p-6 w-96 shadow-2xl" onClick={e => e.stopPropagation()}>
            <h3 className="text-lg font-semibold text-gray-900 mb-4">新建文件夹</h3>
            <input
              type="text"
              value={newFolderName}
              onChange={(e) => setNewFolderName(e.target.value)}
              placeholder="请输入文件夹名称"
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent outline-none"
              autoFocus
            />
            <div className="flex justify-end gap-3 mt-6">
              <button onClick={() => setShowNewFolderModal(false)} className="px-4 py-2 text-gray-700 hover:bg-gray-100 rounded-lg transition-colors">
                取消
              </button>
              <button
                onClick={() => {
                  setShowNewFolderModal(false)
                  setNewFolderName('')
                }}
                className="px-4 py-2 bg-primary-600 text-white rounded-lg hover:bg-primary-700 transition-colors"
              >
                创建
              </button>
            </div>
          </div>
        </div>
      )}

      {showShareModal && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50" onClick={() => setShowShareModal(false)}>
          <div className="bg-white rounded-xl p-6 w-[480px] shadow-2xl" onClick={e => e.stopPropagation()}>
            <h3 className="text-lg font-semibold text-gray-900 mb-4">分享文件</h3>
            <div className="bg-gray-50 rounded-lg p-4 mb-4">
              <p className="text-sm text-gray-600 mb-2">分享链接：</p>
              <div className="flex gap-2">
                <input
                  type="text"
                  value={`https://cloud.example.com/share/${Array.from(selectedItems)[0]}`}
                  readOnly
                  className="flex-1 px-3 py-2 bg-white border border-gray-300 rounded-lg text-sm"
                />
                <button className="px-4 py-2 bg-primary-600 text-white rounded-lg text-sm hover:bg-primary-700 transition-colors">
                  复制
                </button>
              </div>
            </div>
            <div className="space-y-3 mb-4">
              <label className="flex items-center gap-2 text-sm text-gray-700">
                <input type="checkbox" defaultChecked /> 设置密码保护
              </label>
              <label className="flex items-center gap-2 text-sm text-gray-700">
                <input type="checkbox" /> 允许下载
              </label>
              <label className="flex items-center gap-2 text-sm text-gray-700">
                <input type="checkbox" defaultChecked /> 7天后过期
              </label>
            </div>
            <div className="flex justify-end gap-3">
              <button onClick={() => setShowShareModal(false)} className="px-4 py-2 text-gray-700 hover:bg-gray-100 rounded-lg transition-colors">
                取消
              </button>
              <button
                onClick={() => setShowShareModal(false)}
                className="px-4 py-2 bg-primary-600 text-white rounded-lg hover:bg-primary-700 transition-colors"
              >
                生成链接
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

export default FileManager
