// apps/AgentPit/src/components/memory/KnowledgeGraph.vue
<script setup lang="ts">
import { ref, reactive, computed, onMounted, onUnmounted, watch } from 'vue'
import type { GraphNode, GraphEdge } from '@/types/memory'

interface Props {
  nodes?: GraphNode[]
  edges?: GraphEdge[]
}

const props = withDefaults(defineProps<Props>(), {
  nodes: () => [],
  edges: () => []
})

const emit = defineEmits<{
  nodeClick: [node: GraphNode]
}>()

const svgRef = ref<SVGSVGElement | null>(null)
const containerRef = ref<HTMLDivElement | null>(null)
const searchQuery = ref('')
const selectedNode = ref<GraphNode | null>(null)
const showNodeDetail = ref(false)

const transform = reactive({ x: 0, y: 0, scale: 1 })
const isDragging = ref(false)
const isPanning = ref(false)
const dragNode = ref<string | null>(null)
const lastMousePos = reactive({ x: 0, y: 0 })

const nodePositions = reactive<Map<string, { x: number; y: number }>>(new Map())
const nodeVelocities = reactive<Map<string, { vx: number; vy: number }>>(new Map())

const nodeTypeColors: Record<GraphNode['type'], string> = {
  concept: '#3b82f6',
  entity: '#10b981',
  event: '#f59e0b',
  document: '#8b5cf6',
  person: '#ef4444',
  location: '#06b6d4'
}

const edgeTypeColors: Record<GraphEdge['type'], string> = {
  related_to: '#94a3b8',
  contains: '#f97316',
  created_by: '#22c55e',
  located_at: '#0ea5e9',
  references: '#a855f7',
  belongs_to: '#ec4899'
}

const filteredNodes = computed(() => {
  if (!searchQuery.value) return props.nodes
  const query = searchQuery.value.toLowerCase()
  return props.nodes.filter(node =>
    node.label.toLowerCase().includes(query) ||
    node.description?.toLowerCase().includes(query)
  )
})

const filteredEdges = computed(() => {
  const nodeIdSet = new Set(filteredNodes.value.map(n => n.id))
  return props.edges.filter(edge => nodeIdSet.has(edge.source) && nodeIdSet.has(edge.target))
})

const initializePositions = () => {
  const width = containerRef.value?.clientWidth || 800
  const height = containerRef.value?.clientHeight || 600
  const centerX = width / 2
  const centerY = height / 2

  props.nodes.forEach((node, index) => {
    const angle = (2 * Math.PI * index) / props.nodes.length
    const radius = Math.min(width, height) * 0.3
    nodePositions.set(node.id, {
      x: centerX + radius * Math.cos(angle),
      y: centerY + radius * Math.sin(angle)
    })
    nodeVelocities.set(node.id, { vx: 0, vy: 0 })
  })
}

const applyForces = () => {
  const width = containerRef.value?.clientWidth || 800
  const height = containerRef.value?.clientHeight || 600

  props.nodes.forEach(node => {
    if (dragNode.value === node.id) return

    const pos = nodePositions.get(node.id)
    const vel = nodeVelocities.get(node.id)
    if (!pos || !vel) return

    let fx = 0
    let fy = 0

    // 斥力（节点之间）
    props.nodes.forEach(other => {
      if (other.id === node.id) return
      const otherPos = nodePositions.get(other.id)
      if (!otherPos) return

      const dx = pos.x - otherPos.x
      const dy = pos.y - otherPos.y
      const dist = Math.sqrt(dx * dx + dy * dy) || 1
      const force = 5000 / (dist * dist)

      fx += (dx / dist) * force
      fy += (dy / dist) * force
    })

    // 引力（边连接的节点）
    props.edges.forEach(edge => {
      let otherId: string | null = null
      if (edge.source === node.id) otherId = edge.target
      else if (edge.target === node.id) otherId = edge.source

      if (otherId) {
        const otherPos = nodePositions.get(otherId)
        if (!otherPos) return

        const dx = otherPos.x - pos.x
        const dy = otherPos.y - pos.y
        const dist = Math.sqrt(dx * dx + dy * dy) || 1
        const force = dist * 0.01

        fx += (dx / dist) * force
        fy += (dy / dist) * force
      }
    })

    // 向心力（向中心）
    const cx = width / 2
    const cy = height / 2
    fx += (cx - pos.x) * 0.001
    fy += (cy - pos.y) * 0.001

    vel.vx = (vel.vx + fx) * 0.9
    vel.vy = (vel.vy + fy) * 0.9

    pos.x += vel.vx
    pos.y += vel.vy

    // 边界约束
    pos.x = Math.max(50, Math.min(width - 50, pos.x))
    pos.y = Math.max(50, Math.min(height - 50, pos.y))
  })
}

let animationFrame: number | null = null

const startSimulation = () => {
  const simulate = () => {
    applyForces()
    animationFrame = requestAnimationFrame(simulate)
  }
  simulate()
}

const stopSimulation = () => {
  if (animationFrame) {
    cancelAnimationFrame(animationFrame)
    animationFrame = null
  }
}

const handleMouseDown = (e: MouseEvent, nodeId: string) => {
  e.stopPropagation()
  isDragging.value = true
  dragNode.value = nodeId
  lastMousePos.x = e.clientX
  lastMousePos.y = e.clientY
}

const handleMouseMove = (e: MouseEvent) => {
  if (isDragging.value && dragNode.value) {
    const pos = nodePositions.get(dragNode.value)
    if (pos) {
      const dx = e.clientX - lastMousePos.x
      const dy = e.clientY - lastMousePos.y
      pos.x += dx / transform.scale
      pos.y += dy / transform.scale
      nodeVelocities.set(dragNode.value, { vx: 0, vy: 0 })
      lastMousePos.x = e.clientX
      lastMousePos.y = e.clientY
    }
  } else if (isPanning.value) {
    const dx = e.clientX - lastMousePos.x
    const dy = e.clientY - lastMousePos.y
    transform.x += dx
    transform.y += dy
    lastMousePos.x = e.clientX
    lastMousePos.y = e.clientY
  }
}

const handleMouseUp = () => {
  isDragging.value = false
  isPanning.value = false
  dragNode.value = null
}

const handleWheel = (e: WheelEvent) => {
  e.preventDefault()
  const delta = e.deltaY > 0 ? 0.9 : 1.1
  const newScale = Math.max(0.2, Math.min(3, transform.scale * delta))

  if (containerRef.value) {
    const rect = containerRef.value.getBoundingClientRect()
    const mouseX = e.clientX - rect.left
    const mouseY = e.clientY - rect.top

    transform.x = mouseX - (mouseX - transform.x) * (newScale / transform.scale)
    transform.y = mouseY - (mouseY - transform.y) * (newScale / transform.scale)
  }

  transform.scale = newScale
}

const handleSvgMouseDown = (e: MouseEvent) => {
  if (e.target === svgRef.value) {
    isPanning.value = true
    lastMousePos.x = e.clientX
    lastMousePos.y = e.clientY
  }
}

const handleNodeClick = (node: GraphNode) => {
  selectedNode.value = node
  showNodeDetail.value = true
  emit('nodeClick', node)
}

const closeNodeDetail = () => {
  showNodeDetail.value = false
  selectedNode.value = null
}

const resetView = () => {
  transform.x = 0
  transform.y = 0
  transform.scale = 1
  initializePositions()
}

onMounted(() => {
  initializePositions()
  startSimulation()
  window.addEventListener('mousemove', handleMouseMove)
  window.addEventListener('mouseup', handleMouseUp)
})

onUnmounted(() => {
  stopSimulation()
  window.removeEventListener('mousemove', handleMouseMove)
  window.removeEventListener('mouseup', handleMouseUp)
})

watch([() => props.nodes, () => props.edges], () => {
  initializePositions()
})
</script>

<template>
  <div class="knowledge-graph__container bg-white dark:bg-gray-800 rounded-xl shadow-lg overflow-hidden">
    <!-- 工具栏 -->
    <div class="flex items-center justify-between p-4 border-b border-gray-200 dark:border-gray-700">
      <div class="flex items-center gap-3 flex-1">
        <div class="relative flex-1 max-w-md">
          <input
            v-model="searchQuery"
            type="text"
            placeholder="搜索知识节点..."
            class="w-full px-4 py-2 pl-10 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-blue-500"
          />
          <span class="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400">🔍</span>
        </div>
        <button
          @click="resetView"
          class="px-4 py-2 text-sm font-medium text-gray-700 dark:text-gray-300 bg-gray-100 dark:bg-gray-700 hover:bg-gray-200 dark:hover:bg-gray-600 rounded-lg transition-colors"
        >
          🔄 重置视图
        </button>
      </div>
      <div class="text-sm text-gray-500 dark:text-gray-400">
        {{ filteredNodes.length }} 节点 · {{ filteredEdges.length }} 关系
      </div>
    </div>

    <!-- 图例 -->
    <div class="flex flex-wrap gap-4 px-4 py-3 bg-gray-50 dark:bg-gray-900 border-b border-gray-200 dark:border-gray-700">
      <div class="text-xs font-medium text-gray-600 dark:text-gray-400">节点类型:</div>
      <div v-for="(color, type) in nodeTypeColors" :key="type" class="flex items-center gap-1.5">
        <span class="w-3 h-3 rounded-full" :style="{ backgroundColor: color }"></span>
        <span class="text-xs text-gray-700 dark:text-gray-300">{{ { concept: '概念', entity: '实体', event: '事件', document: '文档', person: '人物', location: '位置' }[type] }}</span>
      </div>
    </div>

    <!-- SVG 图谱区域 -->
    <div
      ref="containerRef"
      class="relative w-full h-[500px] overflow-hidden cursor-grab active:cursor-grabbing"
      @wheel="handleWheel"
      @mousedown="handleSvgMouseDown"
    >
      <svg
        ref="svgRef"
        class="w-full h-full"
        :viewBox="`0 0 ${containerRef?.clientWidth || 800} ${containerRef?.clientHeight || 600}`"
      >
        <g :transform="`translate(${transform.x}, ${transform.y}) scale(${transform.scale})`">
          <!-- 边 -->
          <g class="edges">
            <line
              v-for="edge in filteredEdges"
              :key="edge.id"
              :x1="nodePositions.get(edge.source)?.x"
              :y1="nodePositions.get(edge.source)?.y"
              :x2="nodePositions.get(edge.target)?.x"
              :y2="nodePositions.get(edge.target)?.y"
              :stroke="edgeTypeColors[edge.type]"
              stroke-width="2"
              opacity="0.6"
              class="transition-opacity duration-200"
            />
            <!-- 边标签 -->
            <text
              v-for="edge in filteredEdges"
              :key="'label-' + edge.id"
              :x="(nodePositions.get(edge.source)!.x! + nodePositions.get(edge.target)!.x!) / 2"
              :y="(nodePositions.get(edge.source)!.y! + nodePositions.get(edge.target)!.y!) / 2 - 5"
              text-anchor="middle"
              class="text-[10px] fill-gray-500 dark:fill-gray-400 pointer-events-none"
            >
              {{ edge.label }}
            </text>
          </g>

          <!-- 节点 -->
          <g class="nodes">
            <g
              v-for="node in filteredNodes"
              :key="node.id"
              class="cursor-pointer transition-all duration-200"
              :class="{ 'opacity-40': searchQuery && !node.label.toLowerCase().includes(searchQuery.toLowerCase()) }"
              :transform="`translate(${nodePositions.get(node.id)?.x}, ${nodePositions.get(node.id)?.y})`"
              @mousedown="(e: MouseEvent) => handleMouseDown(e, node.id)"
              @click="handleNodeClick(node)"
            >
              <!-- 节点圆圈 -->
              <circle
                r="25"
                :fill="nodeTypeColors[node.type]"
                class="hover:r-30 transition-all duration-200"
                :stroke="selectedNode?.id === node.id ? '#1e40af' : 'white'"
                :stroke-width="selectedNode?.id === node.id ? 3 : 2"
              />
              <!-- 节点图标 -->
              <text
                text-anchor="middle"
                dominant-baseline="central"
                class="fill-white text-sm font-medium pointer-events-none select-none"
              >
                {{ { concept: '💡', entity: '📦', event: '⚡', document: '📄', person: '👤', location: '📍' }[node.type] }}
              </text>
              <!-- 节点标签 -->
              <text
                y="38"
                text-anchor="middle"
                class="fill-gray-700 dark:fill-gray-300 text-xs font-medium pointer-events-none select-none"
              >
                {{ node.label }}
              </text>
            </g>
          </g>
        </g>
      </svg>

      <!-- 缩放提示 -->
      <div class="absolute bottom-4 right-4 bg-white dark:bg-gray-800 rounded-lg shadow-lg px-3 py-2 text-xs text-gray-600 dark:text-gray-400">
        缩放: {{ (transform.scale * 100).toFixed(0) }}%
      </div>
    </div>

    <!-- 节点详情弹窗 -->
    <Teleport to="body">
      <Transition name="fade">
        <div v-if="showNodeDetail && selectedNode" class="fixed inset-0 z-50 flex items-center justify-center bg-black/50" @click="closeNodeDetail">
          <div class="bg-white dark:bg-gray-800 rounded-xl shadow-2xl p-6 max-w-md w-full mx-4" @click.stop>
            <div class="flex items-start justify-between mb-4">
              <div class="flex items-center gap-3">
                <div
                  class="w-12 h-12 rounded-full flex items-center justify-center text-2xl"
                  :style="{ backgroundColor: nodeTypeColors[selectedNode.type] + '20' }"
                >
                  {{ { concept: '💡', entity: '📦', event: '⚡', document: '📄', person: '👤', location: '📍' }[selectedNode.type] }}
                </div>
                <div>
                  <h3 class="text-lg font-semibold text-gray-900 dark:text-white">{{ selectedNode.label }}</h3>
                  <p class="text-sm text-gray-500 dark:text-gray-400">
                    {{ { concept: '概念', entity: '实体', event: '事件', document: '文档', person: '人物', location: '位置' }[selectedNode.type] }}
                  </p>
                </div>
              </div>
              <button @click="closeNodeDetail" class="text-gray-400 hover:text-gray-600 dark:hover:text-gray-200 text-xl">×</button>
            </div>

            <div v-if="selectedNode.description" class="mb-4">
              <p class="text-sm text-gray-600 dark:text-gray-300">{{ selectedNode.description }}</p>
            </div>

            <div class="border-t border-gray-200 dark:border-gray-700 pt-4">
              <h4 class="text-sm font-medium text-gray-900 dark:text-white mb-2">关联关系</h4>
              <div class="space-y-2">
                <div
                  v-for="edge in edges.filter(e => e.source === selectedNode?.id || e.target === selectedNode?.id)"
                  :key="edge.id"
                  class="flex items-center gap-2 text-sm"
                >
                  <span class="w-2 h-2 rounded-full" :style="{ backgroundColor: edgeTypeColors[edge.type] }"></span>
                  <span class="text-gray-600 dark:text-gray-400">{{ edge.label }}</span>
                  <span class="text-gray-900 dark:text-white font-medium">
                    {{ edge.source === selectedNode.id ? nodes.find(n => n.id === edge.target)?.label : nodes.find(n => n.id === edge.source)?.label }}
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </Transition>
    </Teleport>
  </div>
</template>

<style scoped>
.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.2s ease;
}
.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}
</style>

// apps/Flexloop/src-react-backup-20260410/components/memory/KnowledgeGraph.tsx
import { useState, useEffect, useRef, useCallback } from 'react'
import { knowledgeNodes, knowledgeEdges, KnowledgeNode } from '../../data/mockMemory'

interface NodePosition {
  x: number
  y: number
  vx: number
  vy: number
}

const typeColors = {
  concept: '#3b82f6',
  entity: '#10b981',
  event: '#f59e0b',
  person: '#ef4444',
  location: '#8b5cf6',
  skill: '#06b6d4',
  organization: '#ec4899'
}

const typeLabels = {
  concept: '概念',
  entity: '实体',
  event: '事件',
  person: '人物',
  location: '地点',
  skill: '技能',
  organization: '组织'
}

const KnowledgeGraph = () => {
  const svgRef = useRef<SVGSVGElement>(null)
  const [nodes, setNodes] = useState<(KnowledgeNode & NodePosition)[]>([])
  const [selectedNode, setSelectedNode] = useState<KnowledgeNode | null>(null)
  const [searchQuery, setSearchQuery] = useState('')
  const [filterType, setFilterType] = useState<string>('all')
  const [zoom, setZoom] = useState(1)
  const [pan, setPan] = useState({ x: 0, y: 0 })
  const [isDragging, setIsDragging] = useState(false)
  const [dragStart, setDragStart] = useState({ x: 0, y: 0 })
  const animationRef = useRef<number>()
  const width = 900
  const height = 600

  useEffect(() => {
    const initializedNodes = knowledgeNodes.map((node, i) => ({
      ...node,
      x: width / 2 + Math.cos(i * 2 * Math.PI / knowledgeNodes.length) * 200,
      y: height / 2 + Math.sin(i * 2 * Math.PI / knowledgeNodes.length) * 200,
      vx: 0,
      vy: 0
    }))
    setNodes(initializedNodes)
  }, [])

  const simulateForces = useCallback(() => {
    setNodes(prevNodes => {
      const newNodes = prevNodes.map(node => ({ ...node }))
      const centerX = width / 2
      const centerY = height / 2

      newNodes.forEach(node => {
        node.vx *= 0.9
        node.vy *= 0.9

        const dxCenter = centerX - node.x
        const dyCenter = centerY - node.y
        const distCenter = Math.sqrt(dxCenter * dxCenter + dyCenter * dyCenter)
        if (distCenter > 0) {
          node.vx += (dxCenter / distCenter) * 0.01
          node.vy += (dyCenter / distCenter) * 0.01
        }

        newNodes.forEach(other => {
          if (node.id === other.id) return
          let dx = other.x - node.x
          let dy = other.y - node.y
          let dist = Math.sqrt(dx * dx + dy * dy)
          if (dist < 100 && dist > 0) {
            node.vx -= (dx / dist) * 0.5
            node.vy -= (dy / dist) * 0.5
          }
        })

        knowledgeEdges.forEach(edge => {
          let other = null
          if (edge.source === node.id) other = newNodes.find(n => n.id === edge.target)
          else if (edge.target === node.id) other = newNodes.find(n => n.id === edge.source)

          if (other) {
            let dx = other.x - node.x
            let dy = other.y - node.y
            let dist = Math.sqrt(dx * dx + dy * dy)
            if (dist > 80) {
              node.vx += (dx / dist) * 0.02 * edge.strength
              node.vy += (dy / dist) * 0.02 * edge.strength
            }
          }
        })
      })

      newNodes.forEach(node => {
        node.x += node.vx
        node.y += node.vy
        node.x = Math.max(50, Math.min(width - 50, node.x))
        node.y = Math.max(50, Math.min(height - 50, node.y))
      })

      return newNodes
    })

    animationRef.current = requestAnimationFrame(simulateForces)
  }, [])

  useEffect(() => {
    animationRef.current = requestAnimationFrame(simulateForces)
    return () => {
      if (animationRef.current) cancelAnimationFrame(animationRef.current)
    }
  }, [simulateForces])

  const handleWheel = (e: React.WheelEvent) => {
    e.preventDefault()
    const delta = e.deltaY > 0 ? 0.9 : 1.1
    setZoom(zoom => Math.max(0.3, Math.min(3, zoom * delta)))
  }

  const handleMouseDown = (e: React.MouseEvent) => {
    if (e.target === svgRef.current || (e.target as HTMLElement).tagName === 'rect') {
      setIsDragging(true)
      setDragStart({ x: e.clientX - pan.x, y: e.clientY - pan.y })
      setSelectedNode(null)
    }
  }

  const handleMouseMove = (e: React.MouseEvent) => {
    if (isDragging) {
      setPan({
        x: e.clientX - dragStart.x,
        y: e.clientY - dragStart.y
      })
    }
  }

  const handleMouseUp = () => {
    setIsDragging(false)
  }

  const filteredNodes = nodes.filter(node => {
    const matchesSearch = !searchQuery || node.label.toLowerCase().includes(searchQuery.toLowerCase())
    const matchesType = filterType === 'all' || node.type === filterType
    return matchesSearch && matchesType
  })

  const filteredNodeIds = new Set(filteredNodes.map(n => n.id))
  const filteredEdges = knowledgeEdges.filter(edge =>
    filteredNodeIds.has(edge.source) && filteredNodeIds.has(edge.target)
  )

  const highlightedNodeIds = searchQuery ? new Set(
    filteredNodes.filter(n =>
      n.label.toLowerCase().includes(searchQuery.toLowerCase())
    ).map(n => n.id)
  ) : null

  const connectedIds = highlightedNodeIds ? new Set([
    ...Array.from(highlightedIds),
    ...filteredEdges
      .filter(e => highlightedNodeIds.has(e.source) || highlightedNodeIds.has(e.target))
      .map(e => highlightedNodeIds.has(e.source) ? e.target : e.source)
  ]) : null

  return (
    <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
      <div className="border-b border-gray-200 px-6 py-4">
        <h2 className="text-xl font-semibold text-gray-900 flex items-center gap-2 mb-4">
          <span>🕸️</span>
          知识图谱
        </h2>

        <div className="flex items-center gap-4 mb-4">
          <div className="flex-1 relative">
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="搜索知识节点..."
              className="w-full px-4 py-2 pl-10 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent outline-none"
            />
            <span className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400">🔍</span>
          </div>

          <select
            value={filterType}
            onChange={(e) => setFilterType(e.target.value)}
            className="px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 outline-none"
          >
            <option value="all">全部类型</option>
            {Object.entries(typeLabels).map(([key, label]) => (
              <option key={key} value={key}>{label}</option>
            ))}
          </select>

          <div className="flex items-center gap-2 bg-gray-100 rounded-lg p-1">
            <button onClick={() => setZoom(z => Math.max(0.3, z - 0.2))} className="px-3 py-1 hover:bg-white rounded transition-colors">−</button>
            <span className="px-2 text-sm font-medium">{Math.round(zoom * 100)}%</span>
            <button onClick={() => setZoom(z => Math.min(3, z + 0.2))} className="px-3 py-1 hover:bg-white rounded transition-colors">+</button>
            <button onClick={() => { setZoom(1); setPan({ x: 0, y: 0 }) }} className="px-3 py-1 hover:bg-white rounded transition-colors">↺</button>
          </div>
        </div>

        <div className="flex items-center gap-4 flex-wrap">
          <span className="text-sm font-medium text-gray-700">图例：</span>
          {Object.entries(typeColors).map(([type, color]) => (
            <div key={type} className="flex items-center gap-1.5">
              <span className="w-3 h-3 rounded-full" style={{ backgroundColor: color }} />
              <span className="text-sm text-gray-600">{typeLabels[type as keyof typeof typeLabels]}</span>
            </div>
          ))}
        </div>
      </div>

      <div className="relative bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900 overflow-hidden" style={{ minHeight: '600px' }}>
        <svg
          ref={svgRef}
          width={width}
          height={height}
          viewBox={`0 0 ${width} ${height}`}
          onMouseDown={handleMouseDown}
          onMouseMove={handleMouseMove}
          onMouseUp={handleMouseUp}
          onMouseLeave={handleMouseUp}
          onWheel={handleWheel}
          className="cursor-grab active:cursor-grabbing w-full h-full"
          style={{ transform: `translate(${pan.x}px, ${pan.y}px) scale(${zoom})`, transformOrigin: 'center' }}
        >
          <defs>
            {Object.entries(typeColors).map(([type, color]) => (
              <radialGradient key={type} id={`glow-${type}`}>
                <stop offset="0%" stopColor={color} stopOpacity="0.8" />
                <stop offset="100%" stopColor={color} stopOpacity="0" />
              </radialGradient>
            ))}
            <filter id="glow">
              <feGaussianBlur stdDeviation="3" result="coloredBlur" />
              <feMerge>
                <feMergeNode in="coloredBlur" />
                <feMergeNode in="SourceGraphic" />
              </feMerge>
            </filter>
          </defs>

          <rect x={0} y={0} width={width} height={height} fill="transparent" />

          {filteredEdges.map((edge, idx) => {
            const sourceNode = nodes.find(n => n.id === edge.source)
            const targetNode = nodes.find(n => n.id === edge.target)
            if (!sourceNode || !targetNode) return null

            const isHighlighted = !connectedIds ||
              (connectedIds.has(edge.source) && connectedIds.has(edge.target))
            const opacity = isHighlighted ? edge.strength : 0.08

            return (
              <g key={`edge-${idx}`}>
                <line
                  x1={sourceNode.x} y1={sourceNode.y}
                  x2={targetNode.x} y2={targetNode.y}
                  stroke={isHighlighted ? '#64748b' : '#334155'}
                  strokeWidth={Math.max(1, edge.strength * 3)}
                  opacity={opacity}
                />
                {isHighlighted && (
                  <line
                    x1={sourceNode.x} y1={sourceNode.y}
                    x2={targetNode.x} y2={targetNode.y}
                    stroke="#94a3b8"
                    strokeWidth={Math.max(0.5, edge.strength * 2)}
                    opacity={opacity * 0.5}
                    strokeDasharray="4,4"
                  />
                )}
              </g>
            )
          })}

          {filteredNodes.map((node) => {
            const isConnected = !connectedIds || connectedIds.has(node.id)
            const isSelected = selectedNode?.id === node.id
            const radius = 8 + (node.importance / 100) * 20
            const color = typeColors[node.type as keyof typeof typeColors] || '#64748b'

            return (
              <g
                key={node.id}
                onClick={(e) => {
                  e.stopPropagation()
                  setSelectedNode(node)
                }}
                style={{ cursor: 'pointer', transition: 'transform 0.2s' }}
                opacity={isConnected ? 1 : 0.15}
              >
                <circle
                  cx={node.x}
                  cy={node.y}
                  r={radius + 8}
                  fill={`url(#glow-${node.type})`}
                  opacity={isSelected ? 0.6 : 0.3}
                />

                <circle
                  cx={node.x}
                  cy={node.y}
                  r={radius}
                  fill={color}
                  stroke={isSelected ? '#fff' : 'rgba(255,255,255,0.3)'}
                  strokeWidth={isSelected ? 3 : 1.5}
                  filter={isSelected ? 'url(#glow)' : undefined}
                  style={{
                    transition: 'all 0.3s ease',
                    transformOrigin: `${node.x}px ${node.y}px`
                  }}
                />

                <text
                  x={node.x}
                  y={node.y + radius + 16}
                  textAnchor="middle"
                  fill={isConnected ? '#e2e8f0' : '#475569'}
                  fontSize={11}
                  fontWeight={isSelected ? 600 : 400}
                  style={{ pointerEvents: 'none' }}
                >
                  {node.label.length > 8 ? node.label.slice(0, 7) + '...' : node.label}
                </text>
              </g>
            )
          })}
        </svg>

        {selectedNode && (
          <div className="absolute top-4 right-4 bg-white/95 backdrop-blur-md rounded-xl p-5 shadow-2xl max-w-xs z-10">
            <button
              onClick={() => setSelectedNode(null)}
              className="absolute top-2 right-2 text-gray-400 hover:text-gray-600 text-xl leading-none"
            >
              ×
            </button>
            <div className="flex items-center gap-2 mb-3">
              <span
                className="w-4 h-4 rounded-full"
                style={{ backgroundColor: typeColors[selectedNode.type as keyof typeof typeColors] }}
              />
              <span className="text-sm font-semibold text-gray-700">
                {typeLabels[selectedNode.type as keyof typeof typeLabels]}
              </span>
            </div>
            <h3 className="text-lg font-bold text-gray-900 mb-2">{selectedNode.label}</h3>
            <p className="text-sm text-gray-600 mb-4 line-clamp-3">{selectedNode.description}</p>
            <div className="grid grid-cols-2 gap-3 text-sm">
              <div className="bg-gray-50 rounded-lg p-2">
                <p className="text-gray-500 text-xs">重要程度</p>
                <p className="font-semibold text-gray-900">{selectedNode.importance}/100</p>
              </div>
              <div className="bg-gray-50 rounded-lg p-2">
                <p className="text-gray-500 text-xs">关联数量</p>
                <p className="font-semibold text-gray-900">{selectedNode.connections} 个</p>
              </div>
            </div>
            <div className="mt-3 pt-3 border-t border-gray-200">
              <p className="text-xs text-gray-500">创建时间：{selectedNode.createdAt}</p>
            </div>
          </div>
        )}
      </div>

      <div className="border-t border-gray-200 px-6 py-3 bg-gray-50">
        <div className="flex items-center justify-between text-sm text-gray-600">
          <span>共 {knowledgeNodes.length} 个节点，{knowledgeEdges.length} 条关系</span>
          <span>{searchQuery ? `找到 ${filteredNodes.length} 个匹配节点` : '拖拽平移 · 滚轮缩放 · 点击查看详情'}</span>
        </div>
      </div>
    </div>
  )
}

export default KnowledgeGraph
