// apps/AgentPit/src/components/settings/UserProfileSettings.vue
<script setup lang="ts">
import { ref, reactive } from 'vue'
import { defaultUserProfile, cities, type UserProfile } from '../../data/mockSettings'

const profile = reactive<UserProfile>({ ...defaultUserProfile })
const originalProfile = ref(JSON.stringify(profile))
const showSuccessToast = ref(false)
const avatarPreview = ref('')
const hasUnsavedChanges = ref(false)

function handleAvatarUpload(e: Event) {
  const input = e.target as HTMLInputElement
  if (input.files && input.files[0]) {
    const reader = new FileReader()
    reader.onload = (ev) => {
      avatarPreview.value = ev.target?.result as string
      profile.avatar = avatarPreview.value
    }
    reader.readAsDataURL(input.files[0])
  }
}

const emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
const phonePattern = /^1[3-9]\d{9}$/

const emailValid = computed(() => !profile.email || emailPattern.test(profile.email))
const phoneValid = computed(() => !profile.phone || phonePattern.test(profile.phone))
const nicknameValid = computed(() => profile.nickname.length >= 2 && profile.nickname.length <= 30)
const bioValid = computed(() => profile.bio.length <= 200)

const isFormValid = computed(() => nicknameValid.value && emailValid.value && phoneValid.value && bioValid.value)

watch(() => JSON.stringify(profile), () => {
  hasUnsavedChanges.value = JSON.stringify(profile) !== originalProfile.value
}, { deep: true })

function saveProfile() {
  if (!isFormValid.value) return
  originalProfile.value = JSON.stringify(profile)
  hasUnsavedChanges.value = false
  showSuccessToast.value = true
  setTimeout(() => { showSuccessToast.value = false }, 3000)
}

function resetForm() {
  Object.assign(profile, { ...defaultUserProfile })
  avatarPreview.value = ''
}

import { watch, computed } from 'vue'
</script>

<template>
  <div class="user-profile-settings">
    <h3 class="text-lg font-bold text-gray-900 dark:text-white mb-4">👤 个人资料设置</h3>

    <!-- 头像上传 -->
    <div class="flex items-center gap-5 mb-6 p-4 bg-gray-50 dark:bg-gray-700/50 rounded-xl">
      <div class="relative group">
        <div class="w-20 h-20 rounded-full bg-gradient-to-br from-indigo-400 to-purple-500 flex items-center justify-center overflow-hidden cursor-pointer ring-4 ring-white dark:ring-gray-800 shadow-lg">
          <img v-if="profile.avatar" :src="profile.avatar" alt="头像" class="w-full h-full object-cover" />
          <span v-else class="text-3xl">👤</span>
        </div>
        <label class="absolute inset-0 bg-black/40 rounded-full opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center cursor-pointer">
          <span class="text-white text-xs font-medium">更换</span>
          <input type="file" accept="image/*" @change="handleAvatarUpload" class="hidden" />
        </label>
      </div>
      <div>
        <p class="font-medium text-gray-900 dark:text-white">{{ profile.nickname }}</p>
        <p class="text-sm text-gray-500 mt-0.5">点击头像更换照片</p>
        <p class="text-xs text-gray-400 mt-1">支持 JPG、PNG 格式，建议尺寸 200x200</p>
      </div>
    </div>

    <!-- 表单字段 -->
    <div class="space-y-4">
      <!-- 昵称 -->
      <div>
        <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
          昵称 <span class="text-red-500">*</span>
        </label>
        <input v-model="profile.nickname" type="text" placeholder="请输入昵称（2-30字符）"
          maxlength="30"
          :class="[
            'w-full px-3 py-2.5 rounded-lg border bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 focus:ring-indigo-400 outline-none transition-colors',
            nicknameValid ? 'border-gray-300 dark:border-gray-600' : 'border-red-400'
          ]" />
        <p class="text-xs mt-1" :class="nicknameValid ? 'text-gray-500' : 'text-red-500'">
          {{ profile.nickname.length }}/30 字符 {{ nicknameValid ? '' : '- 昵称长度需在2-30个字符之间' }}
        </p>
      </div>

      <!-- 个人简介 -->
      <div>
        <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">个人简介</label>
        <textarea v-model="profile.bio" rows="3" placeholder="介绍一下自己吧..." maxlength="200"
          :class="[
            'w-full px-3 py-2.5 rounded-lg border bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 focus:ring-indigo-400 outline-none resize-none transition-colors',
            bioValid ? 'border-gray-300 dark:border-gray-600' : 'border-red-400'
          ]"></textarea>
        <p class="text-xs mt-1 text-gray-500">{{ profile.bio.length }}/200 字符</p>
      </div>

      <!-- 邮箱和手机 -->
      <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div>
          <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">邮箱地址</label>
          <input v-model="profile.email" type="email" placeholder="example@email.com"
            :class="[
              'w-full px-3 py-2.5 rounded-lg border bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 focus:ring-indigo-400 outline-none',
              emailValid ? 'border-gray-300 dark:border-gray-600' : 'border-red-400'
            ]" />
          <p v-if="!emailValid && profile.email" class="text-xs mt-1 text-red-500">请输入有效的邮箱地址</p>
        </div>
        <div>
          <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">手机号码</label>
          <input v-model="profile.phone" type="tel" placeholder="13800138000"
            :class="[
              'w-full px-3 py-2.5 rounded-lg border bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 focus:ring-indigo-400 outline-none',
              phoneValid ? 'border-gray-300 dark:border-gray-600' : 'border-red-400'
            ]" />
          <p v-if="!phoneValid && profile.phone" class="text-xs mt-1 text-red-500">请输入有效的手机号</p>
        </div>
      </div>

      <!-- 所在城市 -->
      <div>
        <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">所在城市</label>
        <select v-model="profile.location"
          class="w-full px-3 py-2.5 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 focus:ring-indigo-400 outline-none">
          <option value="">请选择城市</option>
          <option v-for="city in cities" :key="city" :value="city">{{ city }}</option>
        </select>
      </div>

      <!-- 个人网站 -->
      <div>
        <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">个人网站 <span class="text-gray-400">(可选)</span></label>
        <input v-model="profile.website" type="url" placeholder="https://example.com"
          class="w-full px-3 py-2.5 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 focus:ring-indigo-400 outline-none" />
      </div>
    </div>

    <!-- 操作按钮 -->
    <div class="flex items-center justify-between mt-6 pt-4 border-t border-gray-200 dark:border-gray-700">
      <button @click="resetForm" class="px-4 py-2 text-sm text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white transition-colors">
        重置
      </button>
      <div class="flex items-center gap-3">
        <span v-if="hasUnsavedChanges" class="text-xs text-orange-500 font-medium animate-pulse">* 有未保存的更改</span>
        <button @click="saveProfile" :disabled="!isFormValid"
          class="px-6 py-2.5 rounded-lg font-medium text-sm transition-all"
          :class="isFormValid
            ? 'bg-indigo-500 text-white hover:bg-indigo-600 shadow-md hover:shadow-lg'
            : 'bg-gray-200 text-gray-400 cursor-not-allowed'">
          保存修改
        </button>
      </div>
    </div>

    <!-- 成功提示 Toast -->
    <Transition name="toast">
      <div v-if="showSuccessToast" class="fixed top-4 right-4 z-50 bg-green-500 text-white px-5 py-3 rounded-xl shadow-lg flex items-center gap-2">
        <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"/></svg>
        <span class="font-medium">保存成功！</span>
      </div>
    </Transition>
  </div>
</template>

<style scoped>
.toast-enter-active, .toast-leave-active { transition: all 0.3s ease; }
.toast-enter-from { transform: translateX(100%); opacity: 0; }
.toast-leave-to { transform: translateX(100%); opacity: 0; }

@keyframes pulse {
  50% { opacity: 0.5; }
}
.animate-pulse { animation: pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite; }
</style>

// apps/AgentPit/src-react-backup-20260410/components/settings/UserProfileSettings.tsx
import { useState } from 'react'
import { type UserProfile, defaultUserProfile, presetInterests } from '../../data/mockSettings'

const UserProfileSettings = () => {
  const [profile, setProfile] = useState<UserProfile>(defaultUserProfile)
  const [showSuccessMessage, setShowSuccessMessage] = useState(false)
  const [showAvatarModal, setShowAvatarModal] = useState(false)
  const [customInterest, setCustomInterest] = useState('')

  const handleSave = () => {
    setShowSuccessMessage(true)
    setTimeout(() => setShowSuccessMessage(false), 3000)
  }

  const toggleInterest = (interest: string) => {
    if (profile.interests.includes(interest)) {
      setProfile({ ...profile, interests: profile.interests.filter(i => i !== interest) })
    } else {
      setProfile({ ...profile, interests: [...profile.interests, interest] })
    }
  }

  const addCustomInterest = () => {
    if (customInterest.trim() && !profile.interests.includes(customInterest.trim())) {
      setProfile({ ...profile, interests: [...profile.interests, customInterest.trim()] })
      setCustomInterest('')
    }
  }

  const socialPlatforms = [
    { key: 'wechat' as const, name: '微信', icon: '💬', color: 'bg-green-500' },
    { key: 'qq' as const, name: 'QQ', icon: '🐧', color: 'bg-blue-500' },
    { key: 'weibo' as const, name: '微博', icon: '📱', color: 'bg-red-500' },
    { key: 'github' as const, name: 'GitHub', icon: '💻', color: 'bg-gray-800' },
  ]

  return (
    <div className="space-y-6">
      <div className="bg-white rounded-xl shadow p-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-6">个人资料</h2>

        <div className="space-y-8">
          <div className="flex items-center space-x-6">
            <div className="relative group">
              <div className="w-32 h-32 bg-gradient-to-br from-primary-400 to-primary-600 rounded-full flex items-center justify-center text-5xl font-bold text-white cursor-pointer overflow-hidden">
                {profile.avatar ? (
                  <img src={profile.avatar} alt="头像" className="w-full h-full object-cover" />
                ) : (
                  profile.nickname[0]
                )}
              </div>
              <button
                onClick={() => setShowAvatarModal(true)}
                className="absolute inset-0 bg-black/50 rounded-full flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity"
              >
                <span className="text-white text-sm font-medium">更换头像</span>
              </button>
            </div>

            <div className="flex-1">
              <h3 className="text-xl font-semibold text-gray-900">{profile.nickname}</h3>
              <p className="text-gray-500 mt-1">@{profile.email.split('@')[0]}</p>
              <button
                onClick={() => setShowAvatarModal(true)}
                className="mt-3 px-4 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 transition-colors text-sm"
              >
                上传新头像
              </button>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">昵称 *</label>
              <input
                type="text"
                value={profile.nickname}
                onChange={(e) => setProfile({ ...profile, nickname: e.target.value })}
                className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500"
                placeholder="输入您的昵称"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">真实姓名</label>
              <input
                type="text"
                value={profile.realName}
                onChange={(e) => setProfile({ ...profile, realName: e.target.value })}
                className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500"
                placeholder="输入您的真实姓名（可选）"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">性别</label>
              <select
                value={profile.gender}
                onChange={(e) => setProfile({ ...profile, gender: e.target.value as UserProfile['gender'] })}
                className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500"
              >
                <option value="other">保密</option>
                <option value="male">男</option>
                <option value="female">女</option>
              </select>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">生日</label>
              <input
                type="date"
                value={profile.birthday}
                onChange={(e) => setProfile({ ...profile, birthday: e.target.value })}
                className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">所在地</label>
              <input
                type="text"
                value={profile.location}
                onChange={(e) => setProfile({ ...profile, location: e.target.value })}
                className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500"
                placeholder="例如：北京"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">手机号</label>
              <input
                type="tel"
                value={profile.phone}
                onChange={(e) => setProfile({ ...profile, phone: e.target.value })}
                className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500"
                placeholder="输入您的手机号"
              />
            </div>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">邮箱地址</label>
            <input
              type="email"
              value={profile.email}
              onChange={(e) => setProfile({ ...profile, email: e.target.value })}
              className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500"
              placeholder="输入您的邮箱"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">个人简介</label>
            <textarea
              value={profile.bio}
              onChange={(e) => setProfile({ ...profile, bio: e.target.value })}
              rows={4}
              maxLength={200}
              className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 resize-none"
              placeholder="介绍一下自己吧..."
            />
            <p className="text-sm text-gray-500 mt-1 text-right">{profile.bio.length}/200</p>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-3">兴趣标签</label>
            <div className="flex flex-wrap gap-2 mb-3">
              {presetInterests.map(interest => (
                <button
                  key={interest}
                  onClick={() => toggleInterest(interest)}
                  className={`px-4 py-2 rounded-full text-sm font-medium transition-all ${
                    profile.interests.includes(interest)
                      ? 'bg-primary-100 text-primary-700 border-2 border-primary-300'
                      : 'bg-gray-100 text-gray-600 border-2 border-transparent hover:bg-gray-200'
                  }`}
                >
                  {interest}
                </button>
              ))}
            </div>
            <div className="flex space-x-2">
              <input
                type="text"
                value={customInterest}
                onChange={(e) => setCustomInterest(e.target.value)}
                onKeyPress={(e) => e.key === 'Enter' && addCustomInterest()}
                placeholder="添加自定义标签..."
                className="flex-1 px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500"
              />
              <button
                onClick={addCustomInterest}
                className="px-4 py-2 bg-primary-600 text-white rounded-lg hover:bg-primary-700 transition-colors"
              >
                添加
              </button>
            </div>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-3">社交账号绑定</label>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              {socialPlatforms.map(platform => (
                <div
                  key={platform.key}
                  className={`border-2 rounded-xl p-4 ${
                    profile.socialAccounts[platform.key].bound
                      ? 'border-green-300 bg-green-50'
                      : 'border-gray-200 bg-white hover:border-gray-300'
                  } transition-all`}
                >
                  <div className={`w-12 h-12 ${platform.color} rounded-full flex items-center justify-center text-2xl mx-auto mb-2`}>
                    {platform.icon}
                  </div>
                  <p className="text-center font-medium text-gray-900 text-sm">{platform.name}</p>
                  {profile.socialAccounts[platform.key].bound ? (
                    <>
                      <p className="text-xs text-green-600 text-center mt-1 truncate">
                        {profile.socialAccounts[platform.key].username}
                      </p>
                      <button className="w-full mt-2 py-1.5 text-xs border border-green-300 text-green-700 rounded-lg hover:bg-green-100 transition-colors">
                        已绑定
                      </button>
                    </>
                  ) : (
                    <button className="w-full mt-2 py-1.5 text-xs border border-gray-300 text-gray-600 rounded-lg hover:bg-gray-50 transition-colors">
                      绑定账号
                    </button>
                  )}
                </div>
              ))}
            </div>
          </div>

          <div className="flex justify-end pt-4 border-t border-gray-200">
            <button
              onClick={handleSave}
              className="px-8 py-3 bg-primary-600 text-white rounded-lg hover:bg-primary-700 transition-colors font-medium shadow-md hover:shadow-lg"
            >
              保存更改
            </button>
          </div>
        </div>
      </div>

      {showSuccessMessage && (
        <div className="fixed top-20 right-6 bg-green-500 text-white px-6 py-4 rounded-xl shadow-2xl flex items-center space-x-3 animate-slide-in z-50">
          <span className="text-2xl">✓</span>
          <span className="font-medium">个人资料保存成功！</span>
        </div>
      )}

      {showAvatarModal && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50" onClick={() => setShowAvatarModal(false)}>
          <div className="bg-white rounded-2xl shadow-2xl w-full max-w-lg p-8" onClick={(e) => e.stopPropagation()}>
            <h3 className="text-2xl font-bold text-gray-900 mb-6">更换头像</h3>

            <div className="space-y-6">
              <div className="border-2 border-dashed border-gray-300 rounded-xl p-12 text-center hover:border-primary-400 hover:bg-primary-50 transition-all cursor-pointer">
                <p className="text-5xl mb-4">📷</p>
                <p className="font-medium text-gray-900 mb-2">点击或拖拽上传图片</p>
                <p className="text-sm text-gray-500">支持 JPG、PNG 格式，最大 5MB</p>
              </div>

              <div className="bg-gray-50 rounded-xl p-4">
                <p className="text-sm font-medium text-gray-700 mb-3">预览效果</p>
                <div className="flex items-center justify-center space-x-6">
                  <div className="text-center">
                    <div className="w-24 h-24 bg-gradient-to-br from-primary-400 to-primary-600 rounded-full flex items-center justify-center text-3xl font-bold text-white mx-auto mb-2">
                      {profile.nickname[0]}
                    </div>
                    <p className="text-xs text-gray-500">大尺寸</p>
                  </div>
                  <div className="text-center">
                    <div className="w-16 h-16 bg-gradient-to-br from-primary-400 to-primary-600 rounded-full flex items-center justify-center text-xl font-bold text-white mx-auto mb-2">
                      {profile.nickname[0]}
                    </div>
                    <p className="text-xs text-gray-500">中尺寸</p>
                  </div>
                  <div className="text-center">
                    <div className="w-10 h-10 bg-gradient-to-br from-primary-400 to-primary-600 rounded-full flex items-center justify-center text-sm font-bold text-white mx-auto mb-2">
                      {profile.nickname[0]}
                    </div>
                    <p className="text-xs text-gray-500">小尺寸</p>
                  </div>
                </div>
              </div>

              <div className="flex space-x-3">
                <button
                  onClick={() => setShowAvatarModal(false)}
                  className="flex-1 py-3 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 transition-colors font-medium"
                >
                  取消
                </button>
                <button
                  onClick={() => {
                    setShowAvatarModal(false)
                    handleSave()
                  }}
                  className="flex-1 py-3 bg-primary-600 text-white rounded-lg hover:bg-primary-700 transition-colors font-medium"
                >
                  确认上传
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

export default UserProfileSettings
