// apps/Flexloop/src/components/collaboration/AgentStatusCard.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { Agent } from '../../data/mockCollaboration';

const props = defineProps<{
  agent: Agent;
  isSelected?: boolean;
  showDetails?: boolean;
}>();

const emit = defineEmits<{
  (e: 'select', agent: Agent): void;
  (e: 'configure', agent: Agent): void;
}>();

const statusConfig = computed(() => {
  const configs: Record<string, { color: string; bg: string; label: string }> = {
    online: { color: 'text-green-500', bg: 'bg-green-100 dark:bg-green-900/30', label: '在线' },
    busy: { color: 'text-red-500', bg: 'bg-red-100 dark:bg-red-900/30', label: '忙碌' },
    offline: { color: 'text-gray-400', bg: 'bg-gray-100 dark:bg-gray-800', label: '离线' },
    idle: { color: 'text-yellow-500', bg: 'bg-yellow-100 dark:bg-yellow-900/30', label: '空闲' },
    working: { color: 'text-blue-500', bg: 'bg-blue-100 dark:bg-blue-900/30', label: '工作中' },
    waiting: {
      color: 'text-orange-500',
      bg: 'bg-orange-100 dark:bg-orange-900/30',
      label: '等待中'
    },
    error: { color: 'text-red-600', bg: 'bg-red-200 dark:bg-red-900/40', label: '错误' }
  };
  return configs[props.agent.status] || configs.offline;
});

const modeConfig = computed(() => {
  const configs: Record<string, { icon: string; label: string }> = {
    leader: { icon: '👑', label: '领导者' },
    collaborator: { icon: '🤝', label: '协作者' },
    reviewer: { icon: '🔍', label: '审核者' }
  };
  return configs[props.agent.collaborationMode] || configs.collaborator;
});

const formatTime = (timestamp: number) => {
  const now = Date.now();
  const diff = now - timestamp;
  if (diff < 60000) return '刚刚';
  if (diff < 3600000) return `${Math.floor(diff / 60000)}分钟前`;
  if (diff < 86400000) return `${Math.floor(diff / 3600000)}小时前`;
  return `${Math.floor(diff / 86400000)}天前`;
};

const lastActiveTime = computed(() => {
  return formatTime(Date.now() - Math.random() * 3600000);
});
</script>

<template>
  <div
    class="relative rounded-lg border transition-all duration-200 cursor-pointer hover:shadow-md"
    :class="[
      isSelected
        ? 'border-blue-500 bg-blue-50 dark:bg-blue-950/20 shadow-md'
        : 'border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 hover:border-gray-300 dark:hover:border-gray-600'
    ]"
    @click="$emit('select', props.agent)"
  >
    <!-- Header -->
    <div class="p-3 border-b border-gray-100 dark:border-gray-700">
      <div class="flex items-start justify-between mb-2">
        <div class="flex items-center gap-2">
          <span class="text-2xl">{{ props.agent.avatar }}</span>
          <div>
            <h3 class="font-semibold text-sm text-gray-900 dark:text-white">{{ props.agent.name }}</h3>
            <span class="text-xs text-gray-500 dark:text-gray-400">{{ props.agent.role }}</span>
          </div>
        </div>
        <div class="flex items-center gap-1.5">
          <span
            :class="[
              statusConfig?.color,
              statusConfig?.bg,
              'px-2 py-0.5 rounded-full text-xs font-medium'
            ]"
          >
            {{ statusConfig?.label }}
          </span>
        </div>
      </div>

      <!-- Mode Badge -->
      <div class="flex items-center gap-1 text-xs text-gray-600 dark:text-gray-400">
        <span>{{ modeConfig?.icon }}</span>
        <span>{{ modeConfig?.label }}</span>
      </div>
    </div>

    <!-- Stats -->
    <div v-if="showDetails" class="p-3 space-y-3">
      <!-- Level & Accuracy -->
      <div class="grid grid-cols-2 gap-2">
        <div class="text-center p-2 rounded bg-gray-50 dark:bg-gray-700/50">
          <div class="text-xs text-gray-500 dark:text-gray-400">能力等级</div>
          <div class="text-lg font-bold text-blue-600 dark:text-blue-400">{{ props.agent.level }}</div>
        </div>
        <div class="text-center p-2 rounded bg-gray-50 dark:bg-gray-700/50">
          <div class="text-xs text-gray-500 dark:text-gray-400">准确率</div>
          <div class="text-lg font-bold text-green-600 dark:text-green-400">
            {{ props.agent.accuracy }}%
          </div>
        </div>
      </div>

      <!-- CPU Usage Gauge -->
      <div>
        <div class="flex items-center justify-between text-xs mb-1">
          <span class="text-gray-600 dark:text-gray-400">CPU 使用率</span>
          <span class="font-medium text-gray-900 dark:text-white"
            >{{ Math.floor(Math.random() * 60 + 20) }}%</span
          >
        </div>
        <div class="w-full h-2 bg-gray-200 dark:bg-gray-700 rounded-full overflow-hidden">
          <div
            class="h-full bg-gradient-to-r from-green-400 to-blue-500 rounded-full transition-all duration-300"
            :style="{ width: `${Math.floor(Math.random() * 60 + 20)}%` }"
          ></div>
        </div>
      </div>

      <!-- Memory Usage -->
      <div>
        <div class="flex items-center justify-between text-xs mb-1">
          <span class="text-gray-600 dark:text-gray-400">内存使用</span>
          <span class="font-medium text-gray-900 dark:text-white"
            >{{ Math.floor(Math.random() * 50 + 30) }}%</span
          >
        </div>
        <div class="w-full h-2 bg-gray-200 dark:bg-gray-700 rounded-full overflow-hidden">
          <div
            class="h-full bg-gradient-to-r from-purple-400 to-pink-500 rounded-full transition-all duration-300"
            :style="{ width: `${Math.floor(Math.random() * 50 + 30)}%` }"
          ></div>
        </div>
      </div>

      <!-- Current Task Progress -->
      <div v-if="props.agent.status === 'working' || props.agent.status === 'busy'">
        <div class="flex items-center justify-between text-xs mb-1">
          <span class="text-gray-600 dark:text-gray-400">当前任务</span>
          <span class="font-medium text-blue-600 dark:text-blue-400"
            >{{ Math.floor(Math.random() * 80 + 10) }}%</span
          >
        </div>
        <div class="w-full h-2 bg-gray-200 dark:bg-gray-700 rounded-full overflow-hidden">
          <div
            class="h-full bg-gradient-to-r from-blue-400 to-cyan-500 rounded-full transition-all duration-300 animate-pulse"
            :style="{ width: `${Math.floor(Math.random() * 80 + 10)}%` }"
          ></div>
        </div>
      </div>

      <!-- Additional Info -->
      <div class="pt-2 border-t border-gray-100 dark:border-gray-700 space-y-1">
        <div class="flex items-center justify-between text-xs">
          <span class="text-gray-500 dark:text-gray-400">已完成任务</span>
          <span class="font-medium text-gray-900 dark:text-white"
            >{{ props.agent.completedTasks }} 个</span
          >
        </div>
        <div class="flex items-center justify-between text-xs">
          <span class="text-gray-500 dark:text-gray-400">平均耗时</span>
          <span class="font-medium text-gray-900 dark:text-white">{{ props.agent.avgTime }} 分钟</span>
        </div>
        <div class="flex items-center justify-between text-xs">
          <span class="text-gray-500 dark:text-gray-400">最后活跃</span>
          <span class="font-medium text-gray-900 dark:text-white">{{ lastActiveTime }}</span>
        </div>
      </div>
    </div>

    <!-- Configure Button -->
    <div v-if="showDetails" class="px-3 pb-3">
      <button
        class="w-full px-3 py-1.5 text-xs font-medium text-blue-600 dark:text-blue-400 bg-blue-50 dark:bg-blue-900/20 hover:bg-blue-100 dark:hover:bg-blue-900/30 rounded transition-colors"
        @click.stop="$emit('configure', props.agent)"
      >
        ⚙️ 配置参数
      </button>
    </div>
  </div>
</template>

// apps/AgentPit/src-react-backup-20260410/components/collaboration/AgentStatusCard.tsx
import { useState, useEffect } from 'react'
import type { Agent, Task } from '../../data/mockCollaboration'

interface AgentStatusCardProps {
  agent: Agent
  currentTask?: Task
  onPause?: () => void
  onStop?: () => void
  onReassign?: () => void
  isSelected?: boolean
  onSelect?: () => void
}

const statusConfig = {
  online: { color: 'bg-green-500', text: '在线', textColor: 'text-green-700' },
  busy: { color: 'bg-yellow-500', text: '忙碌', textColor: 'text-yellow-700' },
  offline: { color: 'bg-gray-400', text: '离线', textColor: 'text-gray-600' },
  idle: { color: 'bg-blue-500', text: '空闲', textColor: 'text-blue-700' },
  working: { color: 'bg-purple-500', text: '工作中', textColor: 'text-purple-700' },
  waiting: { color: 'bg-orange-500', text: '等待中', textColor: 'text-orange-700' },
  error: { color: 'bg-red-500', text: '错误', textColor: 'text-red-700' },
}

const AgentStatusCard = ({
  agent,
  currentTask,
  onPause,
  onStop,
  onReassign,
  isSelected,
  onSelect,
}: AgentStatusCardProps) => {
  const [isAnimating, setIsAnimating] = useState(false)
  const [progress, setProgress] = useState(currentTask?.progress || 0)

  useEffect(() => {
    if (agent.status === 'working') {
      setIsAnimating(true)
      const interval = setInterval(() => {
        setProgress((prev) => {
          if (prev >= (currentTask?.progress || 100)) return prev
          return prev + Math.random() * 2
        })
      }, 500)
      return () => clearInterval(interval)
    } else {
      setIsAnimating(false)
    }
  }, [agent.status, currentTask?.progress])

  const status = statusConfig[agent.status]

  return (
    <div
      className={`relative bg-white rounded-xl shadow-sm border-2 transition-all duration-300 hover:shadow-lg cursor-pointer ${
        isSelected ? 'border-primary-500 ring-2 ring-primary-200' : 'border-gray-200 hover:border-gray-300'
      }`}
      onClick={onSelect}
    >
      <div className="p-4">
        <div className="flex items-start justify-between mb-3">
          <div className="flex items-center space-x-3">
            <div className="relative">
              <div
                className={`w-12 h-12 rounded-full flex items-center justify-center text-2xl ${
                  isAnimating ? 'animate-pulse bg-gradient-to-br from-primary-100 to-purple-100' : 'bg-gray-100'
                }`}
              >
                {agent.avatar}
              </div>
              <div
                className={`absolute -bottom-0.5 -right-0.5 w-3.5 h-3.5 ${status.color} rounded-full border-2 border-white ${
                  isAnimating ? 'animate-ping' : ''
                }`}
              ></div>
            </div>
            <div>
              <h3 className="font-semibold text-gray-900 text-sm">{agent.name}</h3>
              <p className={`text-xs ${status.textColor} font-medium`}>{status.text}</p>
            </div>
          </div>
          <span className="px-2 py-1 bg-primary-50 text-primary-700 text-xs font-medium rounded-full">
            Lv.{agent.level}
          </span>
        </div>

        <div className="mb-3">
          <p className="text-xs text-gray-600 mb-1">当前任务</p>
          <p className="text-sm font-medium text-gray-800 truncate">{currentTask?.title || '暂无任务'}</p>
        </div>

        {currentTask && agent.status === 'working' && (
          <div className="mb-3">
            <div className="flex justify-between items-center mb-1">
              <span className="text-xs text-gray-600">进度</span>
              <span className="text-xs font-semibold text-primary-600">
                {Math.min(Math.round(progress), 100)}%
              </span>
            </div>
            <div className="w-full h-2 bg-gray-200 rounded-full overflow-hidden">
              <div
                className="h-full bg-gradient-to-r from-primary-400 to-primary-600 transition-all duration-500 ease-out rounded-full"
                style={{ width: `${Math.min(progress, 100)}%` }}
              ></div>
            </div>
          </div>
        )}

        <div className="grid grid-cols-3 gap-2 mb-3 pt-3 border-t border-gray-100">
          <div className="text-center">
            <p className="text-lg font-bold text-gray-900">{agent.completedTasks}</p>
            <p className="text-xs text-gray-500">完成任务</p>
          </div>
          <div className="text-center">
            <p className="text-lg font-bold text-gray-900">{agent.avgTime}s</p>
            <p className="text-xs text-gray-500">平均耗时</p>
          </div>
          <div className="text-center">
            <p className="text-lg font-bold text-gray-900">{agent.accuracy}%</p>
            <p className="text-xs text-gray-500">准确率</p>
          </div>
        </div>

        {(agent.status === 'working' || agent.status === 'waiting') && (
          <div className="flex space-x-2 pt-3 border-t border-gray-100">
            <button
              onClick={(e) => {
                e.stopPropagation()
                onPause?.()
              }}
              className="flex-1 px-3 py-1.5 text-xs font-medium text-yellow-700 bg-yellow-50 rounded-lg hover:bg-yellow-100 transition-colors"
            >
              ⏸️ 暂停
            </button>
            <button
              onClick={(e) => {
                e.stopPropagation()
                onStop?.()
              }}
              className="flex-1 px-3 py-1.5 text-xs font-medium text-red-700 bg-red-50 rounded-lg hover:bg-red-100 transition-colors"
            >
              ⏹️ 停止
            </button>
            <button
              onClick={(e) => {
                e.stopPropagation()
                onReassign?.()
              }}
              className="flex-1 px-3 py-1.5 text-xs font-medium text-blue-700 bg-blue-50 rounded-lg hover:bg-blue-100 transition-colors"
            >
              🔄 重分配
            </button>
          </div>
        )}
      </div>

      <style>{`
        @keyframes ping {
          75%, 100% {
            transform: scale(2);
            opacity: 0;
          }
        }
        .animate-ping {
          animation: ping 1s cubic-bezier(0, 0, 0.2, 1) infinite;
        }
      `}</style>
    </div>
  )
}

export default AgentStatusCard
